ros2/rclcpp

- rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
> [foxy backport] Add missing RCLCPP_PUBLIC to ~StaticExecutorEntitiesCollector (#1227)

- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
This adds the remaining tests for allocator_memory_strategy.hpp and is directly dependent on #1197. The new commit is https://github.com/ros2/rclcpp/commit/5a88b09bfe0ad7f068f5d53b7f6de04f69f58a65
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11300)](http://ci.ros2.org/job/ci_linux/11300/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6546)](http://ci.ros2.org/job/ci_linux-aarch64/6546/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9258)](http://ci.ros2.org/job/ci_osx/9258/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11204)](http://ci.ros2.org/job/ci_windows/11204/)
> Unittests for allocator_memory_strategy.hpp part 2

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
This adds a unit test for StaticSingleThreadedExecutor's StaticExecutorEntityCollector class. Between this and the expanded executors test, this adds gets coverage to 90-95% for this class.
> Add unit test for static_executor_entities_collector

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/strategies/test_message_pool_memory_strategy.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
- rclcpp/test/rclcpp/test_message_memory_strategy.cpp
Adds several tests for memory strategy. I will likely split this up into a couple of PRs. I still need to add coverage for memory_strategy.cpp.
> Unittests for memory strategy files, except allocator_memory_strategy

- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
If the user doesn't retain a reference to the returned shared pointer there will be zero references and their callback will be unregistered.
I think it would be good to backport this change to Foxy and Eloquent.
> Warn about unused result of add_on_set_parameters_callback

- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
The failing test was introduced by #1202.
Failing tests:
* Connext: http://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/29/testReport/rclcpp/TestNodeGraph/get_info_by_topic/
* Cyclone DDS: http://build.ros2.org/view/Rci/job/Rci__nightly-cyclonedds_ubuntu_focal_amd64/31/testReport/rclcpp/TestNodeGraph/get_info_by_topic/
> fix node graph test with Connext and CycloneDDS returning actual data

- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
The failing test was introduced by #1202.
Failing tests:
* Connext: http://build.ros2.org/view/Rci/job/Rci__nightly-connext_ubuntu_focal_amd64/29/testReport/rclcpp/TestNodeGraph/get_service_names_and_types_by_node/
> fix failing test with Connext since it doesn't wait for discovery

- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
It turns out rmw_connext_cpp adds a default waitable that other rmw implementations do not. Adjusting the unit test to take this into account, but in a non-rmw specific manner.
Non connext rmw implementations (testing `--packages-select` rclcpp)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11734)](http://ci.ros2.org/job/ci_linux/11734/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6815)](http://ci.ros2.org/job/ci_linux-aarch64/6815/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9572)](http://ci.ros2.org/job/ci_osx/9572/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11672)](http://ci.ros2.org/job/ci_windows/11672/)
connext only rmw …
> Adjust test_static_executor_entities_collector for rmw_connext_cpp

- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
Backport #1238 to Foxy
If the user doesn't retain a reference to the returned shared pointer there will be zero references and their callback will be unregistered.
> [foxy backport] Warn about unused result of add_on_set_parameters_callback (#1238)

- rclcpp/test/CMakeLists.txt
Destroying nodes takes upwards of 3 seconds, which can cause many unit tests to take inordinate amount of time (#1250) with rmw_connext_cpp. Currently only `test_executors` and `test_allocator_memory_strategy` timeout, so the timeout is being increased here.
> Increase timeouts for connext for long tests

- rclcpp/include/rclcpp/parameter_client.hpp
Similar to https://github.com/ros2/rclcpp/pull/929, but for the subscription.
This fixes an issue listening to parameter events from a remote node when the local node has a different namespace.
Originally reported here: https://answers.ros.org/question/358170/parameter-events-on-foxy/
> Use global namespace for parameter events subscription topic

- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
Due to a difference between connext and other rmw implementations, this unit test was failing. I decided to modify this test so that all callback groups are set so `group->can_be_taken_from()` is set to false before adding one callback group and the associated entities. This let me remove the logic that tracks how many entities are in the basic nodes, since the memory strategy will only ever find those that belong to the callback_group that can be taken from.
Failing example:
https://ci.ros2.org/job/ci_linux/11735/testReport/junit/projectroot/test/test_allocator_memory_strategy/
FastRTPS (plus others)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11737)](http://ci.ros2.org/job/ci_linux/11737/)
* Linux-aarch64 [![Build …
> Simplify and fix allocator memory strategy unit test for connext

- rclcpp/include/rclcpp/parameter_client.hpp
- rclcpp/src/rclcpp/parameter_client.cpp
Fixes #855 for both synchronous or asynchronous parameter clients.
> Make parameter clients use template constructors

- rclcpp/include/rclcpp/any_service_callback.hpp
- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
- rclcpp/include/rclcpp/service.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/include/rclcpp/timer.hpp
Some stricter linters prefer this instead of C-style casts in C++.
> Use static_cast instead of C-style cast for instrumentation

- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
Addresses #1268 and #1269
Default build/test testing `--packages-select rclcpp`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11863)](http://ci.ros2.org/job/ci_linux/11863/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6915)](http://ci.ros2.org/job/ci_linux-aarch64/6915/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9667)](http://ci.ros2.org/job/ci_osx/9667/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11806)](http://ci.ros2.org/job/ci_windows/11806/)
* Linux cyclonedds only [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11864)](https://ci.ros2.org/job/ci_linux/11864/)
* Linux connext only [![Build …
> Fixes for unit tests that fail under cyclonedds

- rclcpp/include/rclcpp/context.hpp
- rclcpp/src/rclcpp/context.cpp
follow-up PR after https://github.com/ros2/rclcpp/pull/1165.
> add get_domain_id method to rclcpp::Context.

- rclcpp_lifecycle/test/test_lifecycle_service_client.cpp
- remove_on_set_parameters_callback
- notify_graph_change
- get_service_names_and_types_by_node
Related to this https://ci.ros2.org/job/nightly_linux_coverage/lastBuild/cobertura/src_ros2_rclcpp_rclcpp_lifecycle_src/lifecycle_node_cpp/lifecycle_node_cpp/
> Added missing tests for rclcpp lifecycle

- rclcpp/include/rclcpp/time_source.hpp
- rclcpp/src/rclcpp/time_source.cpp
> Fix clock thread issue (#1266)

- rclcpp/include/rclcpp/duration.hpp
- rclcpp/src/rclcpp/duration.cpp
- rclcpp/test/rclcpp/test_duration.cpp
I'm not sure why it wasn't there in the first place and couldn't find an (obvious) reason.
Unfortunately I cannot build/test the current master branch (still running melodic and eloquent) so PR against "eloquent"
> add operator!= for duration

- rclcpp/include/rclcpp/duration.hpp
- rclcpp/src/rclcpp/duration.cpp
- rclcpp/test/test_duration.cpp
Backports https://github.com/ros2/rclcpp/pull/1236.
This is an addition, not a bug fix.
It makes sense to me to backport this for consistency. It's weird to have all comparison operators except !=.
> (foxy) Add operator!= to Duration

- rclcpp/include/rclcpp/duration.hpp
- rclcpp/src/rclcpp/duration.cpp
- rclcpp/test/test_duration.cpp
Backports https://github.com/ros2/rclcpp/pull/1236.
This is an addition, not a bug fix.
It makes sense to me to backport this for consistency. It's weird to have all comparison operators except !=.
> (dashing) Add operator!= to Duration

- rclcpp/test/rclcpp/topic_statistics/test_subscription_topic_statistics.cpp
- rclcpp/test/rclcpp/topic_statistics/test_topic_stats_utils.hpp
As discussed in #1274 [(here)](https://github.com/ros2/rclcpp/pull/1274#discussion_r469641061), update topic statistics test to be correct and refactor duplicate logic.
> Refactor Subscription Topic Statistics Tests

- rclcpp_lifecycle/test/test_lifecycle_node.cpp
It looks some rmw-dependent checks made it into this unit test and has started showing up on build.ros2.org.
Example failure:
http://build.ros2.org/job/Fci__nightly-cyclonedds_ubuntu_focal_amd64/181/testReport/(root)/rclcpp_lifecycle/test_lifecycle_node_gtest_missing_result/
> Remove rmw-dependent unit-test checks

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_serialized_message.cpp
- rclcpp/test/rclcpp/test_service.cpp
First round of tests for increasing coverage of `rclcpp`, those are tackling some basic getter functions, let me know if you think I can easily improve those tests.
In particular, I added this test:
``` cpp
size_t publisher_queue_size = publisher->get_queue_size();
// TODO(blast545): get default rmw qos options to compare here
EXPECT_NE(800u, publisher_queue_size);
```
If you guys know to get default QOS configuration please let me know, otherwise I'll check this out before merging.
> Adding tests basic getters

- rclcpp/include/rclcpp/node.hpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
This function `group_in_node` is declared private, but is otherwise unused. This is a PR for removing it, but I can also move it to protected or public if it's inclusion might be helpful.
> Remove unused private function (rclcpp::Node and rclcpp_lifecycle::Node)

- rclcpp_lifecycle/include/rclcpp_lifecycle/state.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/transition.hpp
- rclcpp_lifecycle/src/state.cpp
- rclcpp_lifecycle/src/transition.cpp
This was discovered during fault injection testing, but if for some reason `rcl_lifecycle_state_fini` fails during `rclcpp::Transition::reset()` or `rclcpp::State::reset()`, these destructors will throw an uncatchable exception because destructors are `noexcept` by default.
There are other potential resolutions to this issue, like marking these destructors `noexcept(false)`, but that has performance side effects by poisoning the chain of destructors that eventually call these.
> Log error instead of throwing exception in Transition and State reset(), mark no except

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_executors.cpp
Without this change, I am unable to build locally.
std_msgs is not declared as a test dependency or find_package'd anywhere, so
I'm not sure why CI ever passed the build phase. @brawner any ideas?
> Replace std_msgs with test_msgs in executors test

- rclcpp_action/include/rclcpp_action/client_goal_handle.hpp
- rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp
The method was deprecated in Foxy.
> Remove deprecated client goal handle method for getting result

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_service.cpp
- rclcpp/test/rclcpp/test_type_support.cpp
As the title says. Also adds a `service_fini` that I missed in #1291
> Add tests type_support module

- rclcpp/src/rclcpp/time_source.cpp
This PRs proposes changing the default QoS profile for `/clock` subscriptions.
The reasons:
- `history_depth = 10` doesn't seem to make sense, if a newer message was received it seems ok to use it directly.
- reliable communication is typically problematic in high hz problems, like clock is.
- Repair traffic will increase jitter and likely congest the network
- If nodes are depending on /clock for their event loops, things are likely to a grinding halt.
I'm not quite sure what would the effect of this change in all users, so this need some discussion before being merged.
> Use best effort, keep last, history depth 1 QoS Profile for '/clock' subscriptions

- rclcpp/include/rclcpp/wait_set_policies/dynamic_storage.hpp
In the case where the predicate `p` is false for all elements or these vectors are empty, these calls to std::remove_if will return the `std::vector::end()`, which is not a valid iterator position to `std::vector::erase(std::iterator)` and in turn an exception will be thrown. However, passing two `end()` iterators to `std::vector::erase` is ok.
Testing this PR, which doesn't include the failing unit test. Those will be added separately (`--packages-select rclcpp`)
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12330)](http://ci.ros2.org/job/ci_linux/12330/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7299)](http://ci.ros2.org/job/ci_linux-aarch64/7299/)
* macOS [![Build …
> Call two iterator overload of vector::erase with end iterator in dynamic_storage.hpp

- rclcpp/include/rclcpp/wait_set_policies/detail/storage_policy_common.hpp
Construction of `StoragePolicyCommon` checks shared_ptr for null during `storage_rebuild_rcl_wait_set_with_sets`, which works fine, except for waitables which are also iterated and accessed. This adds a nullptr check similar to those in `storage_rebuild_rcl_wait_set_with_sets` where appropriate.
> Check waitable for nullptr during constructor

- rclcpp/include/rclcpp/wait_set_template.hpp
`SubscriptionBase::exchange_in_use_by_wait_set_state` does not allow nullptr's, but `SubscriptionWaitSetMask` defaults to true so an exception will be thrown in WaitSet::remove_subscription in a simple use case:
```
rclcpp::WaitSet wait_set;
auto subscription = node->create_subscription<test_msgs::msg::Empty>(
"topic", 10, [](test_msgs::msg::Empty::SharedPtr) {});
wait_set.add_subscription(subscription);
wait_set.remove_subscription(subscription);  // throws here
```
> Only exchange subscription intra_process waitable if nonnull

- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/package.xml
- rclcpp_lifecycle/test/mocking_utils/patch.hpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_publisher.cpp
- rclcpp_lifecycle/test/test_lifecycle_service_client.cpp
- rclcpp_lifecycle/test/test_transition_wrapper.cpp
This PR increases the test coverage of rclcpp_lifecycle to about 96% across both the include and src directories. 
It directly depends on #1297
`patch.hpp` contributes about 50% of the additions and that's pretty much unmodified except where indicated.
> Increase test coverage of rclcpp_lifecycle to 96%

- rclcpp/test/rclcpp/test_publisher_subscription_count_api.cpp
- rclcpp/test/rclcpp/test_subscription_publisher_count_api.cpp
> [foxy backport] Fix pub/sub count API tests (#1203)

- rclcpp/include/rclcpp/node_interfaces/node_graph.hpp
- rclcpp/include/rclcpp/node_interfaces/node_graph_interface.hpp
- rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
The method `count_graph_users()` only calls `std::atomic_size_t::load()` which is const, so this method can be made const as well.
> Make node_graph::count_graph_users() const

- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/include/rclcpp_action/client_goal_handle.hpp
- rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp
- rclcpp_action/include/rclcpp_action/exceptions.hpp
- rclcpp_action/test/test_client.cpp
This resolves an issue where `promise->set_value` is called before a potential call to `promise->set_exception`.
If there is an issue sending a result request, set the exception on the future to the result in the goal handle, instead of the future to the goal handle itself.
Alternative to https://github.com/ros2/rclcpp/pull/1292.
> Pass goal handle to goal response callback instead of a future

- rclcpp_action/CMakeLists.txt
- rclcpp_action/package.xml
- rclcpp_action/test/mocking_utils/patch.hpp
- rclcpp_action/test/test_client.cpp
- rclcpp_action/test/test_server.cpp
- rclcpp_action/test/test_server_goal_handle.cpp
This adds unit tests for rclcpp_action and increases the coverage to just bit over 95%. As part of this work, an issue was found with the client implementation, which is potentially addressed in #1292. This branch is currently targeting that PR branch for easy review.
Testing `--packages-select rclcpp_action`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12240)](http://ci.ros2.org/job/ci_linux/12240/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7218)](http://ci.ros2.org/job/ci_linux-aarch64/7218/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9960)](http://ci.ros2.org/job/ci_osx/9960/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12134 …
> Increase coverage rclcpp_action to 95%

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/node_interfaces/test_node_base.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_parameters.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_services.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_timers.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_topics.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_waitables.cpp
This PR boosts the coverage of the node_interface classes to about 96%. It follows up #1202.
> Increase coverage of node_interfaces, including with mocking rcl errors

- rclcpp/src/rclcpp/publisher_base.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/test/rclcpp/test_qos_event.cpp
This small PR adds the topic name to the console warning about QoS mismatch, to help debugging this type of thing.
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>
> Include topic name in QoS mismatch warning messages

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/allocator/test_allocator_common.cpp
- rclcpp/test/rclcpp/allocator/test_allocator_deleter.cpp
- rclcpp/test/rclcpp/exceptions/test_exceptions.cpp
- rclcpp/test/rclcpp/test_future_return_code.cpp
- rclcpp/test/rclcpp/test_node_options.cpp
- rclcpp/test/rclcpp/test_parameter.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
- rclcpp/test/rclcpp/test_rate.cpp
- rclcpp/test/rclcpp/test_timer.cpp
This adds coverage for most of the missing API that I've been able to identify, which were for the most part simple methods. There is still a largish chunk related to executors that is to come.
> Add coverage for missing API (except executors)

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_subscription.cpp
This increases the test coverage of the publisher/subscription API. It also adds coverage for missing public API functions.
> Increase coverage of publisher/subscription API

- rclcpp/include/rclcpp/future_return_code.hpp
- rclcpp/test/rclcpp/test_future_return_code.cpp
While we are here, add in another test for the stream operator for future_return_code.cpp
> Remove deprecated executor::FutureReturnCode APIs

- rclcpp/include/rclcpp/callback_group.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
- rclcpp/test/rclcpp/executors/test_static_single_threaded_executor.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
This PR adds in tests for the `StaticSingleThreadedExecutor` and a helper class, `StaticExecutorEntitiesCollector`.  With this PR in place, I see 97% line coverage on static_single_threaded_executor.cpp and 97% line coverage on static_executor_entities_collector.cpp.
Along the way, I found a few bugs and other problems that I've fixed:
1.  There were some typos in comments.
1.  There were a bunch of places where we could add `const` to variables to give the compiler a bit more of a hint.
1.  There were a couple of places where we were calling the copy constructor when passing a map into a method.
1.  There was a bug when calculating whether to add a guard condition after adding a new node.
Note that this is still in draft because I want to run CI on it (particularly for Windows).  I'll …
> Add in tests for the static executor

- rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
Do three different things in here:
1.  Use const references on the StaticExecutorEntityCollector APIs wherever possible.  This avoids the copy constructor.
1.  Use `const auto` everywhere possible within the StaticExecutorEntityCollector class.
1.  Make more of the StaticExecutorEntityCollector class private.
This was broken out of #1331 .  @brawner @Blast545 FYI.
> Cleanup the static executor API

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_service.cpp
This PR adds coverage for rclcpp::Service API. It should fully cover service.hpp and service.cpp nearly 100%. It's just missing one protected function :(
> Increase service coverage

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_client.cpp
Adding some small coverage for client.hpp/client.cpp. It adds missing coverage for take_response and one async_send_request that was missing.
> Add coverage for client API

- rclcpp/src/rclcpp/executor.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/mocking_utils/patch.hpp
- rclcpp/test/rclcpp/test_executor.cpp
This PR adds in unit tests for the Executor class.  With this change in place, I'm seeing 91% line coverage of the executor.cpp file.
Besides a handful of single lines that aren't being covered, there is a big chunk of missing coverage in the `execute_subscription` method.  I think this is going to be a lot of work to cover, so I figured I would open what I have so far and we can iterate on that later.
> Add executor unit tests

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_graph_listener.cpp
Checking with CI coverage, I think I have a coverage issue with my local environment at the moment:
* Linux coverage [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux_coverage&build=207)](http://ci.ros2.org/job/ci_linux_coverage/207/)
> Add coverage tests graph_listener

- rclcpp/test/rclcpp/test_expand_topic_or_service_name.cpp
This gets us to 100% line coverage.
> Add in two more tests for expand_topic_or_service_name.

- rclcpp/test/rclcpp/test_parameter.cpp
This PR adds several more tests to complete the testing of Parameter's and ParameterValue's API. Tests were added for the `<<` operator for both types and a vector of parameters, as well as the `==` and `!=` operators for Parameters. 
> Complete coverage of Parameter and ParameterValue API

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_node.cpp
This adds tests for the remaining public API in node.hpp/node.cpp.
> Test the remaining node public API

- rclcpp/test/rclcpp/test_subscription_options.cpp
I runned lcov locally, some lines are missing here:
> Improved test_subscription_options

- rclcpp/test/rclcpp/test_subscription.cpp
Covered resolve_use_intra_process. Invalid use_intra_process_comm
> Covered resolve_use_intra_process

- rclcpp/src/rclcpp/parameter_client.cpp
- rclcpp/src/rclcpp/parameter_service.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
This small PR adds some additional tests to the parameter client, and brings us up to 96% line coverage on that file.  It also fixes two very small issues in parameter_server.cpp
> Additional parameter client tests

- rclcpp/src/rclcpp/timer.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_timer.cpp
Add a few missing API tests and coverage tests for missing error throws.
Commit ace8406 reformats the error reporting style to match most recent API usage, let me know if I'm missing something there.
> Add timer coverage tests

- rclcpp/include/rclcpp/time.hpp
- rclcpp/src/rclcpp/time.cpp
- rclcpp/test/rclcpp/test_duration.cpp
- rclcpp/test/rclcpp/test_time.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
> Add time API coverage tests

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_parameter_service.cpp
This increases the coverage of ParameterService to 100% with simple tests to just check basic functionality of the parameter services. 
I'm not sure if describe_parameters is intentionally left out of the ParameterClient, but I opened a related issue here:
https://github.com/ros2/rclcpp/issues/1354
> Add test for ParameterService

- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_executor.cpp
In particular, add API coverage for spin_node_until_future_complete,
spin_until_future_complete, and spin_node_once.
> Finish API coverage on executors.

- rclcpp/include/rclcpp/qos.hpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_qos.cpp
- rclcpp/test/rclcpp/test_qos_event.cpp
This PR add coverage for the remaining lines and functions in qos.hpp, qos.cpp, qos_event.hpp, qos_event.cpp
> Add unit tests for qos and qos_event files

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_loaned_message.cpp
This PR adds coverage for LoanedMessage. Importantly it sets up with mocking a publisher that "supports" loaned messages, so some of the more important parts of this class are actually tested.
> Tests for LoanedMessage with mocked loaned message publisher

- rclcpp_components/src/component_manager.cpp
* Include original exception in ComponentManagerException
Signed-off-by: Martijn Buijs <martijn.buijs@gmail.com>
* Update rclcpp_components/src/component_manager.cpp
Co-authored-by: tomoya <Tomoya.Fujita@sony.com>
Signed-off-by: Martijn Buijs <martijn.buijs@gmail.com>
Co-authored-by: tomoya <Tomoya.Fujita@sony.com>
> [Foxy Backport] Include original exception in ComponentManagerException (#1157)

- rclcpp/test/rclcpp/test_wait_set.cpp
This adds another test to `test_wait_set.cpp` to test the situation when subscriptions have event handlers. I noticed some event_callbacks were rmw implementation dependent, so I hope I only included the ones that are available for each implementation. 
> Increase coverage of WaitSetTemplate

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/duration.hpp
- rclcpp/include/rclcpp/time.hpp
- rclcpp/src/rclcpp/duration.cpp
- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
- rclcpp/src/rclcpp/node_options.cpp
- rclcpp/src/rclcpp/time.cpp
- rclcpp/test/executors/test_multi_threaded_executor.cpp
- rclcpp/test/test_duration.cpp
- rclcpp/test/test_parameter.cpp
- rclcpp/test/test_time.cpp
* Fix conversion from negative Duration or Time to the respective message type and throw in Duration::to_rmw_time() if the duration is negative.
rmw_time_t cannot represent negative durations.
Constructors and assignment operators can be just defaulted.
Other changes are mainly cosmetical, to make conversions between signed
and unsigned types and between 32-bit and 64-bit types more explicit.
Signed-off-by: Johannes Meyer <johannes@intermodalics.eu>
* Add -Wconversion compiler option and fix implicit conversions that might alter the value
Signed-off-by: Johannes Meyer <johannes@intermodalics.eu>
* Fix usage of fixture class in some unit tests by using gtest macro TEST_F() instead of TEST().
Signed-off-by: Johannes Meyer <johannes@intermodalics.eu>
* Add compiler option …
> [dashing backport] Fix conversion of negative durations to messages (#1188)

- rclcpp/src/rclcpp/node_options.cpp
- rclcpp/test/rclcpp/test_node_options.cpp
`this->node_options_` might still be `nullptr` for a default initialized NodeOptions instance.
`use_global_arguments()` must return `this->use_global_arguments_`, in analogy to `NodeOptions::enable_rosout()`.
Signed-off-by: Johannes Meyer <johannes@intermodalics.eu>
> [dashing backport] Fix implementation of NodeOptions::use_global_arguments() (#1176)

- rclcpp_lifecycle/test/test_lifecycle_node.cpp
* Remove rmw-dependent unit-test checks
* Address feedback
* PR Fixup
> [foxy backport] Remove rmw-dependent unit-test checks (#1293)

- rclcpp/include/rclcpp/wait_set_policies/dynamic_storage.hpp
> [foxy backport] Call vector.erase with end iterator overload (#1314)

- rclcpp/src/rclcpp/node_options.cpp
- rclcpp/test/rclcpp/test_node_options.cpp
> [foxy] Fix implementation of NodeOptions::use_global_arguments() (#1176)

- rclcpp/include/rclcpp/node_interfaces/node_time_source.hpp
- rclcpp/include/rclcpp/node_options.hpp
- rclcpp/include/rclcpp/qos.hpp
- rclcpp/include/rclcpp/time_source.hpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp
- rclcpp/src/rclcpp/node_options.cpp
- rclcpp/src/rclcpp/qos.cpp
- rclcpp/src/rclcpp/time_source.cpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
Fixes https://github.com/ros2/rclcpp/issues/1318.
I will open a similar PR in `rclpy`.
(edit) Edited title, as this is allowing to configure the clock qos and not the rosout qos.
> Add clock qos to node options

- rclcpp/include/rclcpp/exceptions/exceptions.hpp
- rclcpp/include/rclcpp/executors/static_single_threaded_executor.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_static_single_threaded_executor.cpp
This PR replaces #1229 in favor of a solution that doesn't affect ABI compatibility, but accomplishes a similar result.
Edit: This backports #1220 to foxy
> [foxy backport] Derive and throw exception in spin_some spin_all for StaticSingleThreadedExecutor

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/strategies/test_message_pool_memory_strategy.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
- rclcpp/test/rclcpp/test_message_memory_strategy.cpp
- rclcpp/test/utils/rclcpp_gtest_macros.hpp
- rclcpp/test/utils/test_rclcpp_gtest_macros.cpp
This backports another chunk of PRs for unit test coverage. It also includes several test failure bug fixes.
Coverage PRs: #1221, #1189
New testing features: #1232
Bug fix PRs: #1245, #1246, #1251, #1253, #1252
> [foxy backport] Backport various commits for unit tests and coverage

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/allocator/test_allocator_common.cpp
- rclcpp/test/rclcpp/allocator/test_allocator_deleter.cpp
- rclcpp/test/rclcpp/exceptions/test_exceptions.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_base.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_parameters.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_services.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_timers.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_topics.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_waitables.cpp
- rclcpp/test/rclcpp/test_future_return_code.cpp
- rclcpp/test/rclcpp/test_node_options.cpp
- rclcpp/test/rclcpp/test_parameter.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_rate.cpp
- rclcpp/test/rclcpp/test_subscription.cpp
- rclcpp/test/rclcpp/test_timer.cpp
- rclcpp/test/rclcpp/test_utilities.cpp
This continues the PRs for coverage. They are unchanged except for the commit for #1322, where I had to make a small change in `test_node_graph.cpp` for API compatibility (`count_graph_users()` is not const in foxy)
Coverage PRs: #1322, #1321, #1326, #1325
> [foxy backport] Backport various unit tests part for coverage part 4-ish

- rclcpp/include/rclcpp/future_return_code.hpp
- rclcpp/test/rclcpp/test_future_return_code.cpp
This backports the unit test introduced it #1327 without removing the deprecation warning.
This will be squash merged into #1383, which will be ultimate be rebase merged back into foxy
> [foxy backport] Add ostream test for FutureReturnCode (#1327)

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_client.cpp
- rclcpp/test/rclcpp/test_service.cpp
This backports #1332 and #1329 for foxy. This will be rebase and merged into #1383 for final staging before rebase and merging onto foxy.
> [foxy backport] Add coverage for service and client API (#1332, #1329)

- rclcpp/src/rclcpp/executor.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/mocking_utils/patch.hpp
- rclcpp/test/rclcpp/test_executor.cpp
This backports #1336 for foxy. This will be squash merged into #1384, which will in turn be rebase and merged onto foxy.
Edit: I meant #1336 not #1331 (which likely won't be backported)
> [foxy backport] Add executor unit tests #1336

- rclcpp/include/rclcpp/create_subscription.hpp
> [subscription_topic_stats] Avoid reference cycle to fix memory leak

- rclcpp/include/rclcpp/time.hpp
- rclcpp/src/rclcpp/parameter_client.cpp
- rclcpp/src/rclcpp/parameter_service.cpp
- rclcpp/src/rclcpp/timer.cpp
- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_duration.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
- rclcpp/test/rclcpp/test_parameter_service.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_subscription.cpp
- rclcpp/test/rclcpp/test_subscription_options.cpp
- rclcpp/test/rclcpp/test_time.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
- rclcpp/test/rclcpp/test_timer.cpp
More tests and minor code fixes for backporting into foxy. This will be rebased and merged into #1383 before ultimate rebase and merging onto foxy.
Coverage PRs: #1358, #1359, #1360, #1361, #1363, #1347, #1355
> [foxy backport] Backport unit tests for coverage into foxy

- rclcpp/src/rclcpp/graph_listener.cpp
The unit test `error_run_graph_listener_destroy_context` (copied below) was added in #1330 which tests destroying a context before calling `run()` on the graph_listener (and ultimately shutdown). This was leading to a memory read error in the `shutdown_guard_condition_` when trying to finalize it. A special case was added in #906, which would try to finalize this guard_condition in the event that the context was already destroyed. 
This addresses https://github.com/ros2/rclcpp/issues/1391
However, I'm not sure if this PR is the correct solution. In #906, this situation was specifically called out in (https://github.com/ros2/rclcpp/pull/906#issuecomment-556238265) and its reply.
@wjwwood 
> @ivanpauno well... there may still be a resource ownership issue here. The context owns the guard …
> [foxy] Remove finalization of guard_condition from GraphListener::__shutdown()

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_subscription.cpp
- rclcpp_action/CMakeLists.txt
- rclcpp_action/test/test_server.cpp
- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_service_client.cpp
There are several tests in rclcpp that timeout with rmw_connext_cpp. This PR increases the timeouts and adds hopefully helpful comments to the offending tests.
> Increase test timeouts of slow running tests with rmw_connext_cpp

- rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
- rclcpp/include/rclcpp/executors/static_single_threaded_executor.hpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
> Clear members for StaticExecutorEntitiesCollector to avoid shared_ptr dependency

- rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
- rclcpp/include/rclcpp/executors/static_single_threaded_executor.hpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
This backports #1303 to the main foxy unit test backport PR #1383, where it's being staged to make sure test failures are minimized before final merging onto foxy.
> [foxy backport] Clear members for StaticExecutorEntitiesCollector to avoid shared_ptr dependency (#1303)

- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_publisher_subscription_count_api.cpp
- rclcpp/test/rclcpp/test_subscription.cpp
- rclcpp/test/rclcpp/test_subscription_publisher_count_api.cpp
Update `INSTANTIATE_TEST_CASE_P` to `INSTANTIATE_TEST_SUITE_P` and `TYPED_TEST_CASE` to `TYPED_TEST_SUITE`.
> Update deprecated gtest macros

- rclcpp/include/rclcpp/node_interfaces/node_base.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
- rclcpp/include/rclcpp/node_interfaces/node_services.hpp
- rclcpp/include/rclcpp/node_interfaces/node_services_interface.hpp
- rclcpp/include/rclcpp/node_interfaces/node_topics.hpp
- rclcpp/include/rclcpp/node_interfaces/node_topics_interface.hpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/src/rclcpp/node_interfaces/node_services.cpp
- rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_services.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_topics.cpp
Follow-up of https://github.com/ros2/rcl/pull/835#issue-505063024.
Prerequisite of https://github.com/ros2/rclcpp/pull/1408.
> Add methods in topic and service interface to resolve a name

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/CMakeLists.txt
These interfaces are needed by the test_subscription_topic_statistics test, but somehow generating them at a different scope than where the `rosidl_target_interfaces` call occurs doesn't correctly target the libraries.
Fixes #1423 
Testing `--packages-select rclcpp`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12861)](http://ci.ros2.org/job/ci_linux/12861/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7816)](http://ci.ros2.org/job/ci_linux-aarch64/7816/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10572)](http://ci.ros2.org/job/ci_osx/10572/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12804)](http://ci.ros2.org/job/ci_windows/12804 …
> Address #1423 by moving rosidl_generate_interfaces call

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
- rclcpp_action/src/server.cpp
This patch actually does 4 related things:
1.  Renames the recursive mutex in the ServerBaseImpl class
to action_server_reentrant_mutex_, which makes it a lot
clearer what it is meant to lock.
2.  Adds some additional error checking where checks were missed.
3.  Moves the mutex in execute_check_expired_goals out of the
loop so we aren't constantly locking and unlocking it.
4.  Adds a lock to publish_status so that the action_server
structure is protected.
I found this problem while trying to reproduce https://github.com/ros2/rclcpp/pull/1313 .  It manifested as a segfault that happened sometimes when running a client over and over against a server.  Before this patch, that test would crash within minutes.  With this patch in …
> Add missing locking to the rclcpp_action::ServerBase.

- rclcpp_action/src/client.cpp
Add missing backport of commit 6ef2384: Fix typo in action client logger name (#937) to branch `dashing`.
> [Dashing] Fix typo

- rclcpp/test/benchmark/CMakeLists.txt
After discussions with @cottsay @clalancette @chapulina and @ahcorde it was decided to run these benchmarks only for the default rmw implementation.
Running with benchmarks on and testing `--packages-select rclcpp`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12893)](http://ci.ros2.org/job/ci_linux/12893/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7847)](http://ci.ros2.org/job/ci_linux-aarch64/7847/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10609)](http://ci.ros2.org/job/ci_osx/10609/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12835)](http://ci.ros2.org/job/ci_windows/12835/)
Signed-off-by: Stephen Brawner …
> Set CMakeLists to only use default rmw for benchmarks

- rclcpp/test/benchmark/CMakeLists.txt
- rclcpp/test/benchmark/benchmark_client.cpp
- rclcpp/test/benchmark/benchmark_service.cpp
PR for adding high-level client and service benchmarks. These services use a `test_msg::srv::Empty` as I couldn't find any performance difference between `Empty` and something more complicated like a ListParameters service type. 
> Add service and client benchmarks

- rclcpp/src/rclcpp/utilities.cpp
- rclcpp/test/rclcpp/test_utilities.cpp
> Avoid parsing arguments twice

- rclcpp/include/rclcpp/duration.hpp
- rclcpp/src/rclcpp/duration.cpp
- rclcpp/src/rclcpp/time.cpp
- rclcpp/test/rclcpp/test_duration.cpp
- rclcpp/test/rclcpp/test_time.cpp
[ros::Duration::Duration(double seconds)](http://docs.ros.org/en/latest/api/rostime/html/classros_1_1Duration.html#ab097cc53395335730c081b6a13d0a12e) provides a constructor from a floating point number, which equivalent in ROS 2 is an static method [rclcpp::Duration::from_seconds](https://github.com/ros2/rclcpp/blob/2309811814b80ad241448aebf51eebd8db17d826/rclcpp/include/rclcpp/duration.hpp#L129-L130).
The only provided constructor from numeric values in rclcpp is [rclcpp::Duration::Duration(rcl_duration_value_t)](https://github.com/ros2/rclcpp/blob/2309811814b80ad241448aebf51eebd8db17d826/rclcpp/include/rclcpp/duration.hpp#L42) (`rcl_duration_value_t -> int64_t`).
The lack of a constructor accepting a `double seconds` together with cpp implicit narrowing conversions might make the user …
> rclcpp::Duration constructors might be confusing to users migrating from ROS 1

- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
Older versions of MSVC 2019 can't figure out the correct namespace.
Just to keep them happy, add a fully-qualified namespace.
> Add fully-qualified namespace to WeakCallbackGroupsToNodesMap

- rclcpp/test/benchmark/CMakeLists.txt
- rclcpp/test/benchmark/benchmark_executor.cpp
This PR buils in top of this other PR https://github.com/ros2/rclcpp/pull/1411
This one includes benchmark tests for executors
> Added executor benchmark tests

- rclcpp_action/test/benchmark/CMakeLists.txt
- rclcpp_action/test/benchmark/benchmark_action_client.cpp
- rclcpp_action/test/benchmark/benchmark_action_server.cpp
This PR adds benchmarks for rclcpp_action's action server.
Building with benchmarks and testing `--packages-select rclcpp_action`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12930)](http://ci.ros2.org/job/ci_linux/12930/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7882)](http://ci.ros2.org/job/ci_linux-aarch64/7882/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10649)](http://ci.ros2.org/job/ci_osx/10649/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12880)](http://ci.ros2.org/job/ci_windows/12880/)
> Add rclcpp_action action_server benchmarks

- rclcpp/include/rclcpp/parameter_client.hpp
Backport #1257 to Foxy.
This changes default behavior and could consequently break application code that is relying on the assumption that the parameter events subscription uses a relative namespace (but the publisher is using a global namespace), therefore I'm hesitant about backporting. On the other hand, without the patch it can lead to buggy behavior when trying to use parameter events for the first time in Foxy.
Dashing and Eloquent don't have the same problem since both the publisher and subscription are using relative namespaces.
@ros2/team I'm looking for opinions on whether this fix should be backported or not.
> [Foxy] Use global namespace for parameter events subscription topic (#1257)

- rclcpp/package.xml
- rclcpp/test/CMakeLists.txt
- rclcpp/test/benchmark/CMakeLists.txt
- rclcpp/test/benchmark/benchmark_init_shutdown.cpp
- rclcpp/test/benchmark/benchmark_node.cpp
Adding two commits here, the initial benchmarks and the followup commit that sets the benchmarks to only be tested on the default rmw_implementation.
> [foxy backport] Initial benchmark tests for rclcpp::init/shutdown create/destroy node (#1411, #1427)

- rclcpp/test/benchmark/CMakeLists.txt
- rclcpp/test/benchmark/benchmark_executor.cpp
Backport executor benchmarks from #1413
> [foxy backport] Added executor benchmark tests (#1413)

- rclcpp_action/CMakeLists.txt
- rclcpp_action/package.xml
- rclcpp_action/test/benchmark/CMakeLists.txt
- rclcpp_action/test/benchmark/benchmark_action_client.cpp
- rclcpp_action/test/benchmark/benchmark_action_server.cpp
This backports rclcpp_action benchmarks for both action_client and action_server. I included #1256 for easy merging.
This PR will be rebase merged instead of squash merged.
> [foxy backport] backport benchmarks for rclcpp_action client and server, #1256, #1429, #1433

- rclcpp/QUALITY_DECLARATION.md
- rclcpp/README.md
- rclcpp_action/QUALITY_DECLARATION.md
- rclcpp_action/README.md
- rclcpp_components/QUALITY_DECLARATION.md
- rclcpp_components/README.md
- rclcpp_lifecycle/QUALITY_DECLARATION.md
- rclcpp_lifecycle/README.md
All dependencies are QL2 or higher, so all rclcpp packages can be bumped as well.
Note that `libstatistics_collector` needs this PR merged first: https://github.com/ros-tooling/libstatistics_collector/pull/64
All that's missing for level 1 are performance tests, which are in the works (see #1036, #1037, #1038, #1039).
> Bump rclcpp packages to Quality Level 2

- rclcpp/include/rclcpp/graph_listener.hpp
- rclcpp/src/rclcpp/graph_listener.cpp
- rclcpp/test/rclcpp/test_graph_listener.cpp
- rclcpp_action/test/test_client.cpp
- rclcpp_action/test/test_server.cpp
CentOS7 has been having test failures for a while; see https://ci.ros2.org/view/nightly/job/nightly_linux-centos_debug/589/#showFailuresLink for the latest example.
The problem ends up being that the mocking_utils `inject_on_return` doesn't work on CentOS7 (https://github.com/ros2/rclcpp/blob/06465ba827da0ce018199fb0f80d15ffe6fc26fd/rclcpp/test/mocking_utils/patch.hpp#L550).  This PR addresses that by changing to `patch_and_return` (which does work on CentOS7), and doing a slight class refactoring so we can stop abusing `inject_on_return` to do partial initialization.  In my testing on CentOS7, this fixes all of the current crashes we are seeing (in rclcpp and rclcpp_action, at least).
> Fix test crashes on CentOS 7

- rclcpp/src/rclcpp/executor.cpp
I noticed this allocation while running benchmark tests with updated pause/resume heap allocations. Creating a std::vector and appending to it allocates on the heap. There is a way of removing these items while iterating through the map to erase from. 
> Remove allocation from executor::remove_node()

- rclcpp/include/rclcpp/any_executable.hpp
- rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/include/rclcpp/waitable.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/test/benchmark/benchmark_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_waitables.cpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_qos_event.cpp
- rclcpp/test/rclcpp/wait_set_policies/test_dynamic_storage.cpp
- rclcpp/test/rclcpp/wait_set_policies/test_static_storage.cpp
- rclcpp/test/rclcpp/wait_set_policies/test_storage_policy_common.cpp
- rclcpp/test/rclcpp/wait_set_policies/test_thread_safe_synchronization.cpp
- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
Fixes #1212.  This PR extends the `Waitable` class with a `take_data` method and the `AnyExecutable` struct with a `data` field.  `take_data` places the data to be executed in `AnyExecutable.data`, which is then used in the `execute` method.
> Add `take_data` to `Waitable` and `data` to `AnyExecutable`

- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
This is a small theoretical issue I found. The type of `states_size` and `transitions_size` is `unsigned int`, but the for loop int type is `uint8_t`. While `default_state_machine` has only 11 states and 25 transitions, looping with a small integer type that is compared to a larger type could lead to an infinite loop. While `size_t` here is large enough to avoid problems, I'd also be happy to use also `unsigned int`.
> [rclcpp_lifecycle] Change uint8_t iterator variables to size_t

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/create_publisher.hpp
- rclcpp/include/rclcpp/create_subscription.hpp
- rclcpp/include/rclcpp/detail/qos_parameters.hpp
- rclcpp/include/rclcpp/exceptions/exceptions.hpp
- rclcpp/include/rclcpp/publisher_options.hpp
- rclcpp/include/rclcpp/qos_overriding_options.hpp
- rclcpp/include/rclcpp/subscription_options.hpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
- rclcpp/src/rclcpp/qos_overriding_options.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_create_subscription.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_qos_overriding_options.cpp
- rclcpp/test/rclcpp/test_qos_parameters.cpp
Reapply #1408.
Fixes:
- Windows visibility issues.
- Windows ABI issues.
Structs with public members that are from `std` generate a lot of warnings on Windows, so `QosOverridingOptions` is now a `class`.
- Fixes bug in `check_if_stringified_policy_is_null`.
Cosmetic changes:
- `QosOverridingOptions::with_default_policies(...)` instead of `QosOverridingOptions{QosOverridingOptions::kDefaultPolicies, ...}`
I will try to run CI in the correct branch this time :joy:
> Qos configurability (take 2)

- rclcpp/include/rclcpp/context.hpp
- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/graph_listener.hpp
- rclcpp/src/rclcpp/context.cpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/graph_listener.cpp
- rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
- rclcpp/test/rclcpp/test_executor.cpp
- rclcpp/test/rclcpp/test_graph_listener.cpp
- rclcpp/test/rclcpp/test_utilities.cpp
Ownership of the shutdown guard conditions used by the graph_listener and the executor base class was in rclcpp::Context, which would lead to memory errors if the context was cleaned up first. 
This moves ownership of the guard_condition to the executor and graph_listener classes, and removes the guard_condition API from Context.
I'm marking this as a draft PR so I can get some initial review on it since I'm not terribly familiar with rclcpp's API.
Addresses #1391 and #1340
> Move ownership of shutdown_guard_condition to executors/graph_listener

- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
While benchmarking, I noticed some good performance improvements with `get_available_states` and `get_available_transitions`. By reserving, allocations can be reduced and using emplace_back where possible can save a duplicate construction. The biggest benefits are in the `get_available_states()` and `get_available_transitions()` method, where there is a 3-5x performance increase.
Target branch benchmarks:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13075)](http://ci.ros2.org/job/ci_linux/13075/)
This branch:
* Linux [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13077)](https://ci.ros2.org/job/ci_linux/13077/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8021)](http://ci.ros2.or …
> Reserve vector capacities and use emplace_back for constructing vectors

- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/package.xml
- rclcpp_lifecycle/test/benchmark/benchmark_lifecycle_client.cpp
- rclcpp_lifecycle/test/benchmark/benchmark_lifecycle_node.cpp
- rclcpp_lifecycle/test/benchmark/benchmark_state.cpp
- rclcpp_lifecycle/test/benchmark/benchmark_transition.cpp
This PR adds benchmarks for lifecycle node features, including rclcpp::LifecycleNode construction/destruction, state machine methods, and construction+destruction for State/Transition types.
Much of the API of rclcpp::LifecycleNode calls the node interface's API, which are benchmarked elsewhere, so I did not include those here.
> Benchmark lifecycle features

- rclcpp/test/benchmark/CMakeLists.txt
- rclcpp/test/benchmark/benchmark_parameter_client.cpp
Note that these tests are written without using performance_test_fixture. Because the parameter server is running in the same process, any allocations happening in the spin thread for the server get picked up by the allocation statistics even though those functions aren't invoked in the tests.
If we can find a way to turn off the memory tracking on a per-thread basis, we can enable memory tracking. Until then, leaving the memory statistics enabled could be misleading.
> Add performance tests for parameter transport

- rclcpp/test/benchmark/CMakeLists.txt
- rclcpp/test/benchmark/benchmark_node_parameters_interface.cpp
- rclcpp/test/benchmark/benchmark_parameter_client.cpp
Backport of #1444 and #1463 from Rolling to Foxy.
> [foxy] Add benchmarks for parameters

- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/package.xml
- rclcpp_lifecycle/test/benchmark/benchmark_lifecycle_client.cpp
- rclcpp_lifecycle/test/benchmark/benchmark_lifecycle_node.cpp
- rclcpp_lifecycle/test/benchmark/benchmark_state.cpp
- rclcpp_lifecycle/test/benchmark/benchmark_transition.cpp
This backports the lifecycle benchmarks from #1462. This should probably wait for merging until `performance_test_fixture` is released into foxy as merging this PR will break rpr jobs.
* Benchmark lifecycle features
> [foxy backport] Benchmark lifecycle features (#1462)

- rclcpp_components/CMakeLists.txt
- rclcpp_components/package.xml
- rclcpp_components/test/benchmark/benchmark_components.cpp
Cherry-picked from #1476
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13176)](http://ci.ros2.org/job/ci_linux/13176/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8107)](http://ci.ros2.org/job/ci_linux-aarch64/8107/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10892)](http://ci.ros2.org/job/ci_osx/10892/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13190)](http://ci.ros2.org/job/ci_windows/13190/)
> [foxy] Add benchmarks for components

- rclcpp/src/rclcpp/executor.cpp
Windows debug has been complaining about dereferencing a value initialized map/set iterator, which just meant it was dereferencing `std::map::end()` after the find. This PR adds logic to check the result of find, dereference, then erase. This issue existed on other platforms as well, windows just had the particular assert statement enabled during debug. 
Example failure:
https://ci.ros2.org/view/nightly/job/ci_windows/13158/testReport/junit/projectroot.test/rclcpp/test_executors/
Fixes #1456 
Build with debug, testing `--packages-select rclcpp`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13160)](http://ci.ros2.org/job/ci_linux/13160/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8091)](http://ci.ros2.org …
> Adjust logic around finding and erasing guard_condition

- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
Backport #1238 to Eloquent.
If the user doesn't retain a reference to the returned shared pointer there will be zero references and their callback will be unregistered.
> [eloquent backport] Warn about unused result of add_on_set_parameters_callback (#1238)

- rclcpp/test/rclcpp/allocator/test_allocator_common.cpp
- rclcpp/test/rclcpp/allocator/test_allocator_deleter.cpp
clang static analysis gets a bit confused going through the
gtest macros, so switch from ASSERT_NE to ASSERT_TRUE as
we've done elsewhere.
> Change nullptr checks to use ASSERT_TRUE.

- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
> [foxy] Reserve vector capacities and use emplace_back for constructing vectors (#1464)

- rclcpp/include/rclcpp/duration.hpp
- rclcpp/include/rclcpp/qos.hpp
- rclcpp/src/rclcpp/duration.cpp
- rclcpp/src/rclcpp/qos.cpp
- rclcpp/test/rclcpp/test_duration.cpp
- rclcpp/test/rclcpp/test_qos.cpp
This will be useful in things like https://github.com/ros2/demos/pull/474.
> Add getters to rclcpp::qos and rclcpp::*Policy enum classes

- rclcpp/resource/logging.hpp.em
- rclcpp/src/rclcpp/logger.cpp
- rclcpp/src/rclcpp/signal_handler.cpp
- rclcpp/test/rclcpp/test_logger.cpp
- rclcpp/test/rclcpp/test_logging.cpp
- rclcpp_components/CMakeLists.txt
- rclcpp_components/src/component_manager.cpp
- rclcpp_components/test/test_component_manager.cpp
- rclcpp_components/test/test_component_manager_api.cpp
This PR fixes the `-Wformat-nonliteral` warnings seen in #1406 and #1405 by changing the generated macros in `rclcpp` for logging. This approach will force changes to several tests, specifically in [`test_logging.cpp`](https://github.com/ros2/rclcpp/blob/d9d67e68131bb0c815dd7494846da390b6c12648/rclcpp/test/rclcpp/test_logging.cpp).
I've made this a draft PR to make it easier to discuss the changes and tradeoffs of this approach and to make a spot for recording CI runs.
> Fix string literal warnings

- rclcpp/include/rclcpp/create_publisher.hpp
- rclcpp/include/rclcpp/create_subscription.hpp
Addresses [this comment](https://github.com/ros2/rclcpp/pull/1465#discussion_r545395921).
> Update create_publisher/subscription documentation, clarifying when a parameters interface is required

- rclcpp_action/CMakeLists.txt
- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/src/server.cpp
- rclcpp_action/test/benchmark/benchmark_action_client.cpp
- rclcpp_action/test/benchmark/benchmark_action_server.cpp
- rclcpp_action/test/test_client.cpp
- rclcpp_action/test/test_types.cpp
This PR enables `-Wformat=2`, `-Wconversion`, `-Wshadow`, `-Wsign-conversion`, and `-Wcast-qual` in `rclcpp_action`. This PR relies on using gtest v1.10.0, see https://github.com/ament/googletest/pull/8.
> [rclcpp_action] Add warnings

- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/test/test_client.cpp
https://github.com/ros2/rclcpp/pull/1311 broke the goal response callback signature, this adds a compatibility shim so we affect less users in the next galactic release (see [this comment](https://github.com/ros2/rclcpp/pull/1311#issuecomment-728841765)).
I think this is a good idea, but there's a minor caveat: `goal_response_callback` was before a `std::function<>`, with the full `std::function` API available, and now there are a few things that the shim type doesn't implement (e.g.: `assign`, `swap`), though we could try to implement all of them.
> Goal response callback compatibility shim with deprecation of old signature

- rclcpp/test/rclcpp/test_publisher.cpp
Fixes https://github.com/ros2/rclcpp/issues/1475.
The test was passing with fastrtps, because it does nothing in that case :smile: (fastrtps doesn't implement the incompatible qos event).
> Fix wrong test expectations

- rclcpp/include/rclcpp/parameter_client.hpp
- rclcpp/src/rclcpp/parameter_client.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
- rclcpp/test/rclcpp/test_parameter_service.cpp
address https://github.com/ros2/rclcpp/issues/360
> add timeout to SyncParametersClient methods

- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
While debugging something else, I came across this fairly rare
flake in the test_node_graph tests.  Essentially, it may take
some time for node changes to propagate into the graph.  If
the NodeGraph client asks for data before the changes are
in the graph, they may get something they don't expect.  The
fix is to wait for an event on the NodeGraph to happen, and
then look for the data you are interested in.
Before this change, I could get the flake to happen on a loaded
aarch64 system fairly regularly.  After this change, I can no
longer make the flake happen on a loaded system.
@eboasson FYI, this should fix the aarch64 failures we are seeing in the tests in https://github.com/ros2/rmw/pull/293 .
> Make sure to wait for graph change events in test_node_graph.

- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
In particular, we don't know for sure that the graph will only
have 1 user; we just know that it should have *at least* one
user.  So change that check to be more robust.  This also
lets us get rid of the slightly strange call to 'notify_graph_change'
that was being used to cleanup graph users.
This is a followup to #1503
> Make the test of graph users more robust.

- rclcpp/include/rclcpp/subscription.hpp
Closes #1491
Change the execution order of callback dispatch and topic statistic calculating
Signed-off-by: hsgwa <hasegawa@isp.co.jp>
Current topic statistics include callback duration.
To measure communication latency, this patch moves topic statics calculation before callback execution.
It excludes callback duration from statistics results and enables finding whether a specific callback duration is a bottleneck or not.
> modify excluding callback duration from topic statistics

- rclcpp/include/rclcpp/qos.hpp
When I learned ROS2, this was one of the things that annoyed me, so I hope to spare others the experience. There is a tutorial, but I think it's best to keep documentation close to the code.
BTW, I think it would be great to link to hpp & cpp files in Doxygen. That would make having sparse documentation much more bearable.
> Better documentation for the QoS class

- rclcpp/include/rclcpp/logger.hpp
- rclcpp/src/rclcpp/logger.cpp
- rclcpp/test/rclcpp/test_logger.cpp
Revert #1509.
Reverting as the inclusion of `windows.h` broke downstream code.
> Revert "Add get_logging_directory method to rclcpp::Logger (#1509)"

- rclcpp/test/rclcpp/test_parameter_service.cpp
@brawner could you take a look at this? follow-up for https://github.com/ros2/rclcpp/issues/1354
> use describe_parameters of parameter client for test

- rclcpp/include/rclcpp/logger.hpp
- rclcpp/src/rclcpp/logger.cpp
- rclcpp/test/rclcpp/test_logger.cpp
This should be safe to reapply now that https://github.com/ros2/rcpputils/pull/118 went in.
> Reapply "Add get_logging_directory method to rclcpp::Logger (#1509)"

- rclcpp/test/rclcpp/test_node.cpp
The graph_listener thread is started in the background in some of the tests and this thread is killed by Windows prior to executing global destructors if it is still running when leaving main().  This then corrupts state because the RMW layer is blocking in a waitset and causes Cyclone to hang trying to destroy the waitset.
This fixes the issue mentioned in https://github.com/ros2/rmw/pull/293#issuecomment-758322651 (for me locally anyway!)
> Call rclcpp::shutdown in test_node for clean shutdown on Windows

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/test/rclcpp/test_executor.cpp
This PR makes `Executor::add_node()` and `Executor::remove_node()` thread safe.
`memory_strategy_mutex_` was renamed to `mutex_` and now it's used to protect all internal collections.
Thread safety annotations were added mainly because of documentation purposes, we're not running the thread sanitizer in CI.
> Allow to add/remove nodes thread safely in rclcpp::Executor 

- rclcpp_action/src/server.cpp
- rclcpp_action/test/test_server.cpp
To fix the issue https://github.com/ros2/rclcpp/issues/1285
I think the problem is that the server can let the next goal accept during processing `on_terminal_state` callback.
It can be solved by putting them in a single `reentrant_mutex_` context.
This does not make any deadlock with [my test code](https://gist.github.com/daisukes/46298b083a48e5db7016f3c0efba7e2d) so far.
> Fix action server deadlock (#1285)

- rclcpp/include/rclcpp/time_source.hpp
- rclcpp/src/rclcpp/time_source.cpp
We should probably document what policies are reconfigurable for built-in topics somewhere ...
> Allow reconfiguring 'clock' topic qos

- rclcpp/test/rclcpp/test_executor.cpp
clang static analysis suggested that there was a possible memory
leak here, and it is right.  The test is expecting to throw during
the constructor, in which case the memory would be automatically
freed.  However, if the test did *not* throw for some reason,
we would leak the memory.  Switch to using a unique_ptr here
which will free the memory in all cases at the end of the scope.
> Change to using unique_ptrs for DummyExecutor.

- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
Currently trying to use IPC with the **StaticSingleThreadExecutor** yields:
```
terminate called after throwing an instance of 'std::runtime_error'
what():  'data' is empty
Aborted (core dumped)
```
This is because the new API `execute(data)` for waitables requires `data` to be non `nullptr`. This PR makes the waitable to take the data (the message itself, on a intra-process subscription) before using it as the `execute` parameter on the static executor.
Taking the oportunity also fixing here a `cppcheck` which was failing:
```
[static_executor_entities_collector.cpp:327]: (error: deallocuse) Dereferencing 'node_ptr' after it is deallocated / released
```
> Fix error when using IPC with StaticSingleThreadExecutor

- rclcpp/src/rclcpp/node_interfaces/node_timers.cpp
Relates to https://gitlab.com/ros-tracing/tracetools_analysis/-/issues/41
Relates to https://gitlab.com/ros-tracing/ros2_tracing/-/issues/111
Requires https://gitlab.com/ros-tracing/ros2_tracing/-/merge_requests/219
This adds instrumentation for linking a timer to a node.
As mentioned in the linked `tracetools_analysis` issue, from my understanding, timers don't belong to a node in the same way that a publisher/subscriber belongs to a node, at least at the `rcl` level. We can only get the "link" between a node and a timer in `rclcpp`.
> Add instrumentation for linking a timer to a node

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
- rclcpp_action/src/server.cpp
This is a backport of #1313
I didn't include 8c8c268aad3e243ddb7e2717b5c46044db34e055 and 543a3c39c16fdeb3f0109d0e906105870f547fe1, but 579e9d01d6810e5f60a76f896f440b191514aab5 and modified ca3ad7da2fa62f089ff00661ac24295019d946f0.
> [Backport] Fix action server deadlock (#1285) (#1313) 

- rclcpp_action/src/server.cpp
Fixes #1526.
As action_server_ depends on clock_, we declare clock_ first.
Then the order of deletion becomes action_server_, clock_.
There are still errors in the following test, but we have solved errors for test_server.
- test_client
- test_server_goal_handle
> Fix #1526.

- rclcpp/include/rclcpp/loaned_message.hpp
- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/test/rclcpp/test_loaned_message.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
> Destroy msg extracted from LoanedMessage.

- rclcpp/test/rclcpp/test_serialized_message.cpp
According to the documentation at
https://en.cppreference.com/w/cpp/utility/move,
the "moved-from" objects are "in a valid but unspecified
state" after the move.  Thus, we shouldn't assume anything
about them, since it could be implementation-defined behavior.
> Don't access objects after they have been std::move

- rclcpp/test/rclcpp/test_node.cpp
If we just EXPECT it, then we continue running tests below
and eventually dereference an empty list.
> Assert that the publisher_list size is 1.

- rclcpp/src/rclcpp/parameter_value.cpp
> Avoid an object copy in parameter_value.cpp.

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/src/rclcpp/intra_process_manager.cpp
Fixes #1519 
NOTE: To reproduce the issue, please refer to https://github.com/ros2/rclcpp/issues/1519#issuecomment-768817649.
> Avoid `Resource deadlock avoided` if use intra_process_comms

- rclcpp/include/rclcpp/create_subscription.hpp
- rclcpp/include/rclcpp/topic_statistics/subscription_topic_statistics.hpp
- rclcpp/test/rclcpp/topic_statistics/test_subscription_topic_statistics.cpp
Closes #1531 
Signed-off-by: hsgwa <hasegawa@isp.co.jp>
> clear statistics after window reset (#1531)

- rclcpp/test/CMakeLists.txt
- rclcpp/test/rclcpp/CMakeLists.txt
The CMake `install` command should never be used to copy content from the source tree to the build directory like this. The destination directory is affected by the `DESTDIR` variable on UNIX platforms, which will get prefixed onto the destination directory and we'll end up installing the test resources into the target install space.
This change will eliminate the excess test collateral present in the rclcpp deb packages being installed to `/tmp/binarydeb`:
```
$ dpkg-query -L ros-rolling-rclcpp
/.
/opt
/opt/ros
/opt/ros/rolling
...
/tmp
/tmp/binarydeb
/tmp/binarydeb/ros-rolling-rclcpp-6.3.0
/tmp/binarydeb/ros-rolling-rclcpp-6.3.0/obj-x86_64-linux-gnu
/tmp/binarydeb/ros-rolling-rclcpp-6.3.0/obj-x86_64-linux-gnu/test
/tmp/binarydeb/ros-rolling-rclcpp-6.3.0/obj-x86_64-linux-gnu/test/resource …
```
> Reference test resources directly from source tree

- rclcpp/include/rclcpp/publisher_options.hpp
- rclcpp/include/rclcpp/subscription_options.hpp
foxy backport of https://github.com/ros2/rclcpp/pull/1547 (original issue is https://github.com/ros2/rclcpp/issues/1544)
>  [foxy] Fix runtime error: reference binding to null pointer of type (#1547)

- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/test/rclcpp/test_any_subscription_callback.cpp
When running the rclcpp tests under UBSAN, it complained that
the AnySubscriptionCallback tests were using an uninitialized
allocator.
Reviewing the code there, it also looks like the AnySubscriptionCallback
constructor wasn't checking for a null allocator.
Fix this by doing 3 things:
1.  Add a check for a null allocator in the AnySubscriptionCallback
constructor.
2.  Add a new test to test_any_subscription_callback that tests the new
nullptr handling.
3.  Fix the test fixture to initialize the allocator before trying to
call the AnySubscriptionCallback constructor.
> Fix UBSAN warnings in any_subscription_callback.

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/detail/mutex_two_priorities.hpp
- rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
- rclcpp/src/rclcpp/detail/mutex_two_priorities.cpp
- rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
Fixes https://github.com/ros2/rclcpp/issues/1487.
Something in between https://github.com/ros2/rclcpp/pull/621 and https://github.com/ros2/rclcpp/pull/1168.
The whole idea of the `scheduled_timers_` container seems wrong, but this works around the issue.
> Allow timers to keep up the intended rate in MultiThreadedExecutor

- rclcpp/include/rclcpp/node.hpp
`volatile()` is not the name of the method.
> Fix documented example in create_publisher

- rclcpp_action/src/client.cpp
address https://github.com/ros2/rclcpp/issues/1545
> node_handle must be destroyed after client_handle to prevent memory leak

- rclcpp_action/src/client.cpp
foxy backport for https://github.com/ros2/rclcpp/pull/1562, address https://github.com/ros2/rclcpp/issues/1545.
> [foxy] node_handle must be destroyed after client_handle to prevent memory leak (#1562)

- rclcpp/include/rclcpp/service.hpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
I think this is high impact but may have gone somewhat unnoticed since most ROS setups probably only tear-down Nodes on termination. Please see description and related issues in #1468.
> SEGV is caused due to some sub-iface destructor code expecting living references to the node base or other interface but it was already released earlier in the Node destructor. Memory corruption occurs and eventually malloc checks abort later in the execution, usually somewhere in malloc_consolidate, FastRTPS library or waitfor collection resizing.
I have based this fix to foxy branch as I think it should be applied there and then brought forward to master. I can rebase to master though if you want.
This fix explicitly releases the shared_ptrs to sub interfaces in the reverse order of creation. This …
> Fix SEGV caused by order of destruction of Node sub-interfaces

- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
- rclcpp/test/rclcpp/test_node.cpp
When working on https://github.com/ros2/rclpy/pull/683 I realized of a few problems in https://github.com/ros2/rclcpp/pull/1522:
- The `NoParameterOverrideProvided` exception was being thrown in some cases where it shouldn't. See [this](https://github.com/ros2/rclcpp/blob/2036857e92a1c0a96c4626272724be3e0f267964/rclcpp/test/rclcpp/test_node.cpp#L625-L628) new test case.
- `node->declare_parameter("my_param", rclcpp::ParameterType::PARAMETER_INTEGER, descriptor_dynamic_typing_on` shouldn't be valid. Discussion in [rclpy PR](https://github.com/ros2/rclpy/pull/683#discussion_r585039574). See [this other](https://github.com/ros2/rclcpp/blob/2036857e92a1c0a96c4626272724be3e0f267964/rclcpp/test/rclcpp/test_node.cpp#L632-L637) new test case.
And when working on this, I find a super old bug which …
> Static parameter type fixes

- rclcpp/test/benchmark/benchmark_node.cpp
When building rclcpp under clang static analysis, it complains
that the "DoNotOptimize" function from Google benchmark can
cause a memory leak.  I can't see how this is possible, so I
can only assume that the inline assembly that is used to implement
"DoNotOptimize" is causing a false positive.  Just quite the
warning here when building under clang static analysis.
> Quiet clang memory leak warning on "DoNotOptimize".

- rclcpp/test/rclcpp/test_node.cpp
Add tests checking that declaring an statically typed parameter when undeclared parameters are allowed works as described in https://github.com/ros2/rclcpp/pull/1568#discussion_r588763935.
Pending: add test case for https://github.com/ros2/rclcpp/pull/1568#discussion_r589713118.
> Add tests for declaring statically typed parameters when undeclared parameters are allowed

- rclcpp/include/rclcpp/clock.hpp
- rclcpp/src/rclcpp/clock.cpp
> Remove 'struct' from the rcl_time_jump_t.

- rclcpp/test/rclcpp/executors/test_multi_threaded_executor.cpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_subscription.cpp
- rclcpp_action/test/test_server.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_service_client.cpp
This PR removes all references to `rmw_connext_cpp`, so that it may be replaced by `rmw_connextdds`.
Changes mostly involved getting rid of several comments about "long running tests", and re-enabling a test in `test_allocator_memory_strategy.cpp`.
The PR also includes a fix for `test_multi_threaded_executor.cpp`, to avoid an implicit conversion from integer to double which was causing the test to fail.
See [rticommunity/rmw_connextdds #9](https://github.com/rticommunity/rmw_connextdds/issues/9) for a list of related PRs, and an overview of all the changes required to replace [ros2/rmw_connext](https://github.com/ros2/rmw_connext) (`rmw_connext_cpp`) with [rticommunity/rmw_connextdds](https://github.com/rticommunity/rmw_connextdds) in the ROS2 source tree.
> Add support for rmw_connextdds

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
- rclcpp/src/rclcpp/detail/resolve_parameter_overrides.cpp
- rclcpp/src/rclcpp/detail/resolve_parameter_overrides.hpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
- rclcpp/test/rclcpp/test_qos_parameters.cpp
This is a bit complex because the final qos profile is needed before a parameters node interface is created.
For `/rosout` it will even be more complex, because the final profile is needed even before a `rcl_node_t` is written!! (it's possible, but it requires some surgery probably involving `rcl`).
I'm not sure what's the best way to handle that one, opinions welcomed!
> Enable qos parameter overrides for the /parameter_events topic 

- rclcpp/doc/notes_on_statically_typed_parameters.md
Document some of the decisions that were made in https://github.com/ros2/rclcpp/pull/1522, https://github.com/ros2/rclpy/pull/683.
There's also a question in the document.
> Document design decisions that were made for statically typed parameters

- rclcpp/src/rclcpp/parameter_service.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
address https://github.com/ros2/rclcpp/issues/1510
> get_parameters_service_ should return empty if allow_undeclared_ is false

- rclcpp/src/rclcpp/duration.cpp
- rclcpp/test/rclcpp/test_duration.cpp
Guard against overflow when converting from rclcpp::Duration to builtin_interfaces::msg::Duration,
which is a unsigned to signed conversion.
---
I discovered this bug when making a copy of a `rclcpp::QoS` object with default duration values. Since default durations are max int64 values, they end up overflowing during the copy which uses `rclcpp::Duration::from_rmw_time()` internally.
We can easily see the issue with this reproduction, where we would expect `foo` and `baz` to be equivalent, but they are not:
```c++
auto foo = rclcpp::Duration::from_nanoseconds(9223372036854775807u);
auto bar = foo.to_rmw_time();
rclcpp::Duration baz = rclcpp::Duration::from_rmw_time(bar);
std::cerr << "foo: " << foo.nanoseconds() << std::endl;
std::cerr << "baz: " << baz.nanoseconds() << std::endl;
```
> Guard against integer overflow in duration conversion

- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
- rclcpp_lifecycle/test/mocking_utils/patch.hpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
> make rcl_lifecyle_com_interface optional in lifecycle nodes

- rclcpp/src/rclcpp/parameter_service.cpp
Clang is complaining about the looping variable being referenced as `const val` but should rather be `const ref`.
```
/Users/karsten/workspace/ros2/ros2_master/src/ros2/rclcpp/rclcpp/src/rclcpp/parameter_service.cpp:46:25: error: loop variable 'param' of type 'const rclcpp::Parameter' creates a copy from type 'const rclcpp::Parameter' [-Werror,-Wrange-loop-construct]
for (const auto param : parameters) {
^
/Users/karsten/workspace/ros2/ros2_master/src/ros2/rclcpp/rclcpp/src/rclcpp/parameter_service.cpp:46:14: note: use reference type 'const rclcpp::Parameter &' to prevent copying
for (const auto param : parameters) {
^~~~~~~~~~~~~~~~~~
&
1 error generated.
```
> use const auto & to iterate over parameters

- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
> Remove rmw_connext_cpp references.

- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
This PR tries to implement #1589
It adds the `automatically_add_executor_with_node` option when creating a callback_group for a LifecycleNode.
> add automatically_add_executor_with_node option

- rclcpp/include/rclcpp/node_interfaces/node_time_source.hpp
- rclcpp/include/rclcpp/node_options.hpp
- rclcpp/include/rclcpp/time_source.hpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp/src/rclcpp/node_interfaces/node_time_source.cpp
- rclcpp/src/rclcpp/node_options.cpp
- rclcpp/src/rclcpp/time_source.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
Good morning,
this pull request is motivated by the #1540 issue. In short, we would like the node's clock behavior to be consistent, independently from the `use_sim_time` parameter value. Currently, if using simulation time, the node's clock time won't be updated within callbacks. 
To always keep node's clock time up to date, we added a callback group to the existing clock subscription's options and make this callback group spins in its own thread, in [`TimeSource::create_clock_sub` method](https://github.com/wyca-robotics/rclcpp/blob/10ae308afd4194aab65b0dc9fd30d118425e272e/rclcpp/src/rclcpp/time_source.cpp#L249). The thread is cleanly finished in the [class destructor](https://github.com/wyca-robotics/rclcpp/blob/10ae308afd4194aab65b0dc9fd30d118425e272e/rclcpp/src/rclcpp/time_source.cpp# …
> Clock subscription callback group spins in its own thread

- rclcpp_lifecycle/test/test_lifecycle_node.cpp
Apparently, the topics and services that LifecycleNode provides are not
available immediately after creating a node.
Fix flaky tests by accounting for some delay between the LifecycleNode
constructor and queries about its topics and services.
Fixes #1605
> Fix flaky lifecycle node tests

- rclcpp/include/rclcpp/any_service_callback.hpp
- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/include/rclcpp/timer.hpp
2nd try for #1603 / #1607
The upstream ros2_tracing MR has been merged: https://gitlab.com/ros-tracing/ros2_tracing/-/merge_requests/229
This makes the hundreds of deprecation warnings go away.
> Namespace tracetools C++ util functions

- rclcpp/test/rclcpp/test_parameter_event_handler.cpp
Likely fixes https://ci.ros2.org/view/nightly/job/nightly_linux_release/1870/testReport/junit/projectroot.test/rclcpp/test_parameter_event_handler/
I have only see that once, it's probably flaky due to the variables not being initialized.
> Initialize integers in test_parameter_event_handler.cpp to avoid undefined behavior

- rclcpp/include/rclcpp/time_source.hpp
- rclcpp/src/rclcpp/time_source.cpp
address https://github.com/ros2/rclcpp/pull/1556#issuecomment-812256630
this is bugfix introduced originally from https://github.com/ros2/rclcpp/pull/1556
> use context from `node_base_` for clock executor.

- rclcpp/include/rclcpp/parameter_client.hpp
- rclcpp/include/rclcpp/parameter_map.hpp
- rclcpp/src/rclcpp/parameter_client.cpp
- rclcpp/src/rclcpp/parameter_map.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
- rclcpp/test/resources/test_node/load_parameters.yaml
> Create load_parameters and delete_parameters methods

- rclcpp/include/rclcpp/publisher.hpp
This adds publishing instrumentation, with the goal being to be able to track a message across all the layers.
Note that we're only supporting "normal," inter-process publishing for now.
Requires https://gitlab.com/ros-tracing/ros2_tracing/-/merge_requests/227
> Add publishing instrumentation

- rclcpp/src/rclcpp/time_source.cpp
This patch hopefully (as I cannot even locally reproduce CI failures) fixes what appears to be a race condition introduced by #1556, which is causing [test timeouts in CI](https://ci.ros2.org/view/nightly/job/nightly_linux_repeated/lastCompletedBuild/testReport/projectroot.test/rclcpp/test_time_source/). See https://github.com/ros2/rclcpp/pull/1556#issuecomment-814255120 for further reference.
Repeated CI up to `rclcpp`:
* Linux [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14267)](https://ci.ros2.org/job/ci_linux/14267/)
> Fix race condition in TimeSource clock thread setup

- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
This PR restores an exception for Connext in test `TestAllocatorMemoryStrategy::number_of_entities_with_subscription` which was [deleted](https://github.com/ros2/rclcpp/pull/1595/files#diff-4e1d578c35ec70e95e1a61099f536a316415483223a17061108a1a4e3f379a5bL514) in the process of replacing `rmw_connext_cpp` with `rmw_connextdds`.
The fix will enable `rmw_connextdds` to pass the test, as discovered while working on [rmw_connextdds#22](https://github.com/ros2/rmw_connextdds/pull/22).
> Restore test exception for Connext

- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
Based on @jacobperron comment:
```cpp
node->declare_parameter("my_int", 42);
node->add_on_set_parameters_callback([](const std::vector<rclcpp::Parameter> & params) {
for (const auto & param : params) {
if (param.get_name() == "my_int") {
param.as_int();
}
}
});
```
This could throw as the parameter type was checked after calling the user provided "on set" parameters callback.
Inver the order so parameter type is checked first (integer/floating point range will also be checked before user callbacks now).
This is also consistent with the current `rclpy` behavior: https://github.com/ros2/rclpy/blob/e938f92933a6919b8f277b17e5cd7deb18d75da1/rclpy/rclpy/node.py#L795-L811.
> Check first parameter type and range before calling the user validation callbacks

- rclcpp/include/rclcpp/detail/mutex_two_priorities.hpp
- rclcpp/src/rclcpp/detail/mutex_two_priorities.cpp
Fixes #1008 
The naive implementation added in https://github.com/ros2/rclcpp/pull/1516 doesn't work as well as I expected.
Even though only one "low priority thread" can be waiting in the "data mutex", it's still pretty likely to find the following behavior:
- low priority thread releases data mutex and then the "barrier" mutex
- another low priority thread releases takes the barrier mutex and then also takes the "data" mutex, even when there was a "high priority" thread waiting.
i.e.: the "high priority" take isn't always as "high priority" as we wanted.
Investigating https://github.com/ros2/rclcpp/issues/1008, I realized that the problem was that the executor was taking too long to schedule a timer callback (see investigation in https://github.com/ros2/rclcpp/pull/1624).
After some …
> Use a different implementation of mutex two priorities

- rclcpp/src/rclcpp/executor.cpp
While testing ros2/rmw_fastrtps#523 I saw the following error message several times during the execution of `test_communication`
```
[ERROR] [rclcpp]: rcl_return_loaned_message_from_subscription() failed for subscription on topic '/test_message_BasicTypes': loaned_message argument is null
```
I discovered that `Executor::execute_subscription` was trying to return a loaned message, even when none was obtained (i.e. there was no data available)
> Avoid returning loan when none was obtained

- rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
Set and initialize seem redundant.
Update the doc brief to match the equivalent in node.hpp.
> Clarify node parameters docs

- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/test/test_server.cpp
Resolves the deadlock issue mentioned in https://github.com/ros-planning/navigation2/issues/2273 and https://github.com/ros-planning/navigation2/pull/2304
The unit test which I added could also reproduce the issue.
> Fix action server deadlock issue that caused by other mutexes locked in CancelCallback

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_intra_process_manager.cpp
- rclcpp/test/rclcpp/test_intra_process_manager_with_allocators.cpp
We believe this is the root cause of https://github.com/ros2/demos/issues/501
> use dynamic_pointer_cast to detect allocator mismatch in intra process manager

- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/test/test_server.cpp
For fixing #1599. Some conversations in https://github.com/ros2/rclcpp/pull/1635 are helpful to this PR.
> Returns CancelResponse::REJECT while goal handle failed to transit to CANCELING state

- rclcpp/test/rclcpp/test_node.cpp
Yield CPU for graph changes to propagate. This is a shot in the dark, in hopes we can deal with flakes like [this](https://ci.ros2.org/view/nightly/job/nightly_win_rep/lastCompletedBuild/testReport/rclcpp/TestNode/get_publishers_subscriptions_info_by_topic/).
Repeated Windows CI on `rclcpp`: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14626)](https://ci.ros2.org/job/ci_windows/14626/)
> Fix get_publishers_subscriptions_info_by_topic test in test_node.cpp

- rclcpp/include/rclcpp/publisher_options.hpp
- rclcpp/include/rclcpp/subscription_options.hpp
- rclcpp/test/rclcpp/test_intra_process_manager_with_allocators.cpp
Also, enforce an allocator bound to void is used to avoid surprises. Connected to #1643.
I used `mutable` and kept `MessageT` as template parameter to keep changes local (i.e. not force a change all the way up the call stack due template signature and `const`-ness changes).
CI up to `rclcpp` and `demo_nodes_cpp`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14524)](http://ci.ros2.org/job/ci_linux/14524/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9281)](http://ci.ros2.org/job/ci_linux-aarch64/9281/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12190)](http://ci.ros2.org/job/ci_osx/12190/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build …
> Keep custom allocator in publisher and subscription options alive.

- rclcpp_action/include/rclcpp_action/server.hpp
foxy backport for #1635.
Signed-off-by: Kaven Yau <kavenyau@foxmail.com>
> [foxy backport #1635] Fix action server deadlock issue that caused by other mutexes locked in CancelCallback

- rclcpp/include/rclcpp/publisher_options.hpp
- rclcpp/include/rclcpp/subscription_options.hpp
- rclcpp/test/rclcpp/test_intra_process_manager_with_allocators.cpp
Void allocators are not supposed to even have `allocate` nor `deallocate` methods (see [cppreference](https://en.cppreference.com/w/cpp/memory/allocator)). `allocator::get_rcl_allocator` has an [specialization](https://github.com/ros2/rclcpp/blob/1fc2d58799a6d4530522be5c236c70be53455e60/rclcpp/include/rclcpp/allocator/allocator_common.hpp#L85-L94) to bypass itself if `Allocator` is `std::allocator<void>`, but it doesn't cover custom void allocators (which shouldn't have `allocate` nor `deallocate` methods to begin with).
This patch amends this, keeping a rebound allocator for byte-sized memory blocks around for publisher and subscription options.
Follow-up after 1fc2d58799a6d4530522be5c236c70be53455e60.
> Do not attempt to use void allocators for memory allocation.

- rclcpp/include/rclcpp/service.hpp
Fixes https://github.com/ros2/rmw_connextdds/issues/40.
I don't see why we were using a weak_ptr, and that causes unexpected bugs when something external (e.g. the executor) is holding the rcl service handle but not the rcl node handle.
-----
Ownership diagram:
parent =====> child
weak_parent -----> weak_child
```
(through a rclcpp::Node weak_ptr)
rclcpp::Executor --------------------------------------------
|                          |
|                          |
V  (captured by deleter)   |
rclcpp::Service =======> rcl_service handle=======||        |
||                                          ||        |
||                                          VV        V
||=======================================> rcl_node handle
```
Based on the diagram above, I don't see any problem with …
> [service] Don't use a weak_ptr to avoid leaking

- rclcpp_action/test/benchmark/CMakeLists.txt
Pausing and resuming the measurement inside the timing loop can cause the initial run duration calculation to underestimate how long the benchmark is taking to run, which results in the recorded run taking a lot longer than it should. This is a known issue in libbenchmark.
This test is affected by that behavior, and typically takes a bit longer than the others. The easiest thing to do right now is to just bump the timeout. My tests show that 180 seconds is typically sufficient for this test, so 240 should be a safe point to conclude that the test is malfunctioning.
This test has been timing out for the past 121 consecutive attempts in Rolling: https://build.ros2.org/view/Rci/job/Rci__benchmark_ubuntu_focal_amd64/370/testReport/junit/projectroot.test/benchmark/benchmark_action_client/ …
> Bump the benchmark timeout for benchmark_action_client

- rclcpp/include/rclcpp/type_adapter.hpp
required for https://github.com/ros2/demos/pull/482
I tried a few solutions from the referenced SO post about this, but for various reasons, none of them work for us. So we'll just have to document that this macro must be used outside of any namespace to work properly.
> fix syntax issue with gcc

- rclcpp_lifecycle/test/benchmark/benchmark_lifecycle_client.cpp
This should be the last issue to get the benchmark jobs green, and I intend to backport it to Galactic as well.
Before: [![Build Status](https://build.ros2.org/buildStatus/icon?job=Rci__overlay_ubuntu_focal_amd64&build=25)](https://build.ros2.org/view/Rci/job/Rci__overlay_ubuntu_focal_amd64/25/)
After: [![Build Status](https://build.ros2.org/buildStatus/icon?job=Rci__overlay_ubuntu_focal_amd64&build=26)](https://build.ros2.org/view/Rci/job/Rci__overlay_ubuntu_focal_amd64/26/)
> Fix destruction order in lifecycle benchmark

- rclcpp/include/rclcpp/exceptions/exceptions.hpp
- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
- rclcpp/test/rclcpp/test_node.cpp
Fixes #1649
Allow declaring parameters without an initial value or override.
This was possible prior to Galactic, but was made impossible since we started enforcing the types of parameters in Galactic.
---
Opening for early feedback. I still need to test this more thoroughly for my use-case and add documentation.
> Declare parameters uninitialized

- rclcpp_action/include/rclcpp_action/server.hpp
foxy backport for #1641.
Signed-off-by: Kaven Yau kavenyau@foxmail.com
> [foxy backport #1641] Returns CancelResponse::REJECT while goal handle failed to transit to CANCELING state

- rclcpp_action/src/server.cpp
Fix occasionally missing goal result when a action finished quickly (one thread enter to `execute_result_request_received` and the other enter to `publish_result`).
> Fix occasionally missing goal result caused by race condition

- rclcpp/include/rclcpp/exceptions/exceptions.hpp
- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
- rclcpp/test/rclcpp/test_node.cpp
Backport #1673 to Galactic.
I've released this change into Rolling and haven't noticed any regressions. The only code I found that this affects is in navigation2 and I've got a patch there: https://github.com/ros-planning/navigation2/pull/2347
> [galactic] Declare parameters uninitialized (#1673)

- rclcpp_action/src/server.cpp
* Fix occasionally missing goal result caused by race condition
Signed-off-by: Kaven Yau <kavenyau@foxmail.com>
* Take action_server_reentrant_mutex_ out of the sending result loop
Signed-off-by: Kaven Yau <kavenyau@foxmail.com>
* add note for explaining the current locking order in server.cpp
Signed-off-by: Kaven Yau <kavenyau@foxmail.com>
> [Galactic] Fix occasionally missing goal result caused by race condition (#1677)

- rclcpp/include/rclcpp/allocator/allocator_deleter.hpp
> Remove deprecated (in c++17 and newer) use of std::allocator<>::rebind

- rclcpp/src/rclcpp/executor.cpp
I'm trying to debug an issue in rviz2 where it crashes with this warning and it would be really nice to know the name of the specific node that's giving me trouble. I half expect to just see "rviz" which won't be very helpful, but this isn't the first time I've run into the hunt for "which node am I?".
In general, when new software is ported to ROS2 (and folks are learning about spinning mechanisms in ROS2), this error comes up **alot** and it would be really helpful in debugging to know where to look when launching a large system.
> adding node name to the executor runtime_error

- rclcpp/include/rclcpp/time_source.hpp
- rclcpp/src/rclcpp/time_source.cpp
* lock before rcl_set_ros_time_override
Signed-off-by: Daisuke Sato <daisukes@cmu.edu>
> Fix clock thread issue (#1266) (#1267)

- rclcpp/include/rclcpp/experimental/create_intra_process_buffer.hpp
- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_buffer.hpp
- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/src/rclcpp/intra_process_manager.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
- rclcpp/test/rclcpp/test_intra_process_manager.cpp
This PR brings minor improvements to the intra-process-manager component:
- use `rclcpp::QoS` and the new `qos_check_compatibility` API
- remove not needed `PublihserInfo` and `SubscriberInfo` structures to reduce space requirements.
> cleanup intra-process-manager

- rclcpp/src/rclcpp/utilities.cpp
Leftover from https://github.com/ros2/rclcpp/pull/1622
@marcoag fyi, thanks for pointing it out :)
> remove left over is_initialized() implementation

- rclcpp_components/include/rclcpp_components/component_manager.hpp
- rclcpp_components/src/component_manager.cpp
As a follow-up to #1702, this PR renames the methods to use snake_case so they will be consistent with the other ROS 2 core packages.
Signed-off-by: Rebecca Butler <rebecca@openrobotics.org>
> Deprecate method names that use CamelCase in rclcpp_components

- rclcpp/include/rclcpp/any_service_callback.hpp
https://github.com/ros2/rclcpp/pull/1709 broke `rclcpp_components` on Windows nighties, e.g.: https://ci.ros2.org/view/nightly/job/nightly_win_rel/2002/.
I think this is a bug on Windows implementation of `std::bind`, as the previous code really should work.
This does some `if constexpr` magic using function traits to workaround the issue.
I'm surprised we didn't hit a similar issue when using `std::variant` in `AnySubscriptionCallback` implementation, I have no idea of what's the difference.
> Fix windows CI

- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
- rclcpp/test/rclcpp/test_node.cpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
The main reason to add this method in is to make accesses to the
callback_groups_ vector thread-safe.  By having a
callback_groups_for_each that accepts a std::function, we can
just have the callers give us the callback they are interested
in, and we can take care of the locking.
The rest of this fairly large PR is cleaning up all of the places
that use get_callback_groups() to instead use
callback_groups_for_each().
This is the solution to the problem identified in https://github.com/ros-simulation/gazebo_ros_pkgs/issues/1296 .  In short, when using a thread to deal with `use_sim_time`, it is the case that the callbacks_group_ vector can be accessed by two threads simultaneously.  In certain circumstances (particularly …
> Add in callback_groups_for_each.

- rclcpp/include/rclcpp/utilities.hpp
- rclcpp/include/rclcpp/wait_for_message.hpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_wait_for_message.cpp
Introducing "wait_for_message". Similar to ROS1, given either a node & topic or a previously instantiated subscription object, the function waits for the next incoming message until either received or timed out.
I could further see some more overlays to this explicitly taking some QOS parameters, even though one could achieve this as-is by initializing the subscription explicitly. 
I am using it within some ros control functionality and it'd be great to have this backported to existing distros.
> wait for message

- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
> Use RCLCPP_LIFECYCLE_PUBLIC visibility macro in rclcpp_lifecycle package

- rclcpp/include/rclcpp/client.hpp
- rclcpp/test/rclcpp/test_client.cpp
Fixes https://github.com/ros2/rclcpp/issues/1697.
This modifies a few things in the client API:
- Modifies the async_send_request() methods that take a callback as a second argument to not return a future anymore.
Though this breaks API, nobody was actually using that in the ROS 2 core.
If someone wants to have both a callback and a future, they can capture the future in a lambda and set it.
- Alternative: create a `SharedFutureAndRequestID` class, similar to the `FutureAndRequestID` class introduced here.
- I'm planning to deprecate the current callback signatures that accept a `Future`, and instead have the two listed below.
That wasn't done here to avoid having to create simultaneous PRs in other repos.
- void (SharedResponse)
- void (SharedRequest, SharedResponse)
- Modifies the …
> Updating client API to be able to remove pending requests

- rclcpp/include/rclcpp/wait_for_message.hpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_wait_for_message.cpp
> [Galactic backport] wait for message (#1705)

- rclcpp/test/rclcpp/CMakeLists.txt
Part of ros2/rosidl#606 which deprecates `rosidl_target_interfaces()` in favor of `rosidl_get_typesupport_target()`
> Use rosidl_get_typesupport_target()

- rclcpp/CMakeLists.txt
- rclcpp/package.xml
`rclcpp` implicitly depends on `FindPythonInterp` being found in `ament_cmake_core`. It fails to build when using a branch that switches `ament_cmake` to use `FindPython3`. This PR makes the dependency on a python interpreter explicit, and uses `FindPython3`.
Related to ros2/python_cmake_module#6
Blocks ament/ament_cmake#355
> Use FindPython3 and make python3 dependency explicit

- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
This PR fixes an issue with StaticSingleThreadedExecutor not reseting the timers, so they were always ready and executing callbacks continuosly.
https://github.com/ros2/rclcpp/pull/1692#issuecomment-891791168
Signed-off-by: Mauro Passerino <mpasserino@irobot.com>
> Reset timer trigger time before execute.

- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
This adds tracing instrumentation for message taking and the main "phases" of the executor. This instrumentation completes the loop from `rclcpp::publish()` down to DDS & the network and then back up all the way to the execution of the subscription callback.
I also removed a field from the `rclcpp_publish` tracepoint since it's redundant (we'll know which publisher is publishing thanks to the `rcl_publish` tracepoint, and it's better to have it in `rcl_publish` instead of `rclcpp_publish` so that we can support all client libraries and not just rclcpp).
Requires https://gitlab.com/ros-tracing/ros2_tracing/-/merge_requests/254
> Add tracing instrumentation for executor and message taking

- rclcpp/include/rclcpp/executors/static_executor_entities_collector.hpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/test/benchmark/benchmark_executor.cpp
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
This is a fix for a `StaticSingleThreadedExecutor` bug, which fails when adding a new node while the executor is spinning.
This happens due the `spin()` thread tries to add the new node's guard condition to the waitset, but the waitset has not been resized yet (so fails).
0. `StaticSingleThreadedExecutor` created and spinning in its own thread.
1. Node is added to executor, guard condition stored:
https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp#L330
2. Spin thread tries to add the new guard condition to a _not-yet-resized_ wait set
https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp#L270
3. Resize of the wait set happens when some guard condition of the executor has been …
> Fix bug: Add node while spinning

- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/test/rclcpp/executors/test_static_executor_entities_collector.cpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
- rclcpp/test/rclcpp/test_node.cpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
This PR aims takle https://github.com/ros-simulation/gazebo_ros_pkgs/issues/1296 by backporting https://github.com/ros2/rclcpp/pull/1723 to galactic without breaking ABI. To do this, I added a new non virtual function in node_base class, and added static members to it to keep track of a global map of mutexes. This map stores the mutexes for each node_base instance. However, while using the new ```for_each_callback_group``` method, the pointer of type ```NodeBaseInterface``` has to be typecasted to ```NodeBase```. The global map of mutexes is written as a separate class and access to it is protected by an internal mutex.
* General code cleanup, linting issues
* Modify ```static_executor_entities_collector```
* Modify the corresponding test cases
> Galactic: for_each_callback_group backport

- rclcpp/include/rclcpp/client.hpp
- rclcpp/test/rclcpp/test_client.cpp
- rclcpp_components/test/test_component_manager_api.cpp
- rclcpp_lifecycle/test/test_lifecycle_service_client.cpp
Replaces https://github.com/ros2/rclcpp/pull/1728 (which was accidentally merged and requested).
The last two commits implement the change suggested here, to make this change more backwards compatible.
> Update client API to be able to remove pending requests

- rclcpp/include/rclcpp/any_service_callback.hpp
> remove can_be_nullptr assignment check for QNX case

- rclcpp/src/rclcpp/duration.cpp
- rclcpp/test/rclcpp/test_duration.cpp
> [foxy backport] Guard against integer overflow in duration conversion (#1584)

- rclcpp/src/rclcpp/node.cpp
The documentation for std::string::front() says that calling it
on an empty string is undefined behavior.  It actually seems to
work on all platforms except Windows Debug, where it throws an
error.  Make sure to check for empty first.
We also notice that there is no reason to check the
existing_sub_namespace for empty; the rest of the code handles
that fine.  So remove that check.
Finally, we add an anonymous namespace so that these functions do
not pollute the global namespace.
This should fix the Windows Debug test failure as seen in https://ci.ros2.org/view/nightly/job/nightly_win_deb/2099/testReport/junit/projectroot.test/rclcpp/test_node/
> Make sure to check for empty extension before accessing front.

- rclcpp/include/rclcpp/node_options.hpp
PR makes clear what the `automatically_declare_parameters_from_overrides` flag does and emphasizes that the user should check if parameter already exists on the potential parameter declaration.
PR tackles #1749.
> Improve documentation for auto declaration from overrides

- rclcpp/include/rclcpp/node_interfaces/node_graph.hpp
- rclcpp/include/rclcpp/node_interfaces/node_graph_interface.hpp
- rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
address https://github.com/ros2/rclcpp/issues/1483
> NodeGraph exposure with test cases

- rclcpp/include/rclcpp/clock.hpp
- rclcpp/src/rclcpp/clock.cpp
- rclcpp/test/rclcpp/test_time.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
Part of #1730 
Related to ros2/rosbag2#694
Add a `Clock::sleep_until` method. Handle all 3 clock types, and edge cases for shutdown and enabling/disabling ROS time.
Adds test cases for enable/disable ROStime, and `rclcpp::shutdown` - which needed special interrupts. Tests ROS time via `/clock` messages, and has basic testing for steady/system times, though those are much simpler cases.
> Add Clock::sleep_until method

- rclcpp/include/rclcpp/parameter_event_handler.hpp
- rclcpp/src/rclcpp/parameter_event_handler.cpp
I'm not sure why our cppcheck test does not catch these, but in my editor it pointed them out and they were worth addressing in my opinion.
> fixup some small things that cppcheck noticed in my editor

- rclcpp_lifecycle/include/rclcpp_lifecycle/state.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/transition.hpp
Connected to https://github.com/ros2/rcl/pull/938.
> Update forward declarations of `rcl_lifecycle` types

- rclcpp/include/rclcpp/clock.hpp
- rclcpp/src/rclcpp/clock.cpp
- rclcpp/test/rclcpp/test_time.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
This reverts commit 81df5843f321b08db621c17502ff94193ffd3657.
Attempts to address `nighly_osx_debug` test regressions.
> Revert "Add Clock::sleep_until method (#1748)"

- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/test/rclcpp/test_node.cpp
Currently it is possible for a `rclcpp::Context` to destruct while dependent objects (e.g. `rclcpp::Publisher`, `rclcpp::Subscription`) are still alive. This can lead to segmentation faults, exceptions, or other problems in the RMW layer.
This PR fixes that problem by tying the lifetime of contexts to the lifetimes of the node handles that depend on them. Since the objects that depend on nodes (like Publisher and Subscriber) hold a counted reference to their node handle, we just need to ensure that contexts remain alive as long as any of their dependent node handles are alive. This PR accomplishes that by distributing `std::shared_ptr<rcl_node_t>` instances that are actually an alias for a `std::shared_ptr<NodeHandleWithContext>` which bundles together a `std::shared_ptr<rclcpp::Context>` …
> Fix lifetime of context so it remains alive while its dependent node handles are still in use

- rclcpp/include/rclcpp/clock.hpp
- rclcpp/src/rclcpp/clock.cpp
- rclcpp/test/rclcpp/test_time.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
This revives #1748 which was reverted in #1793 with a couple changes.
Originally the PR caused 5 test failures on OSX. The tests themselves passed, but the return code of the test processes would either be -11,
```
1: -- run_test.py: return code -11
```
or it had an error message and a return code of -6.
```
1: libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
1: -- run_test.py: return code -6
```
All the failing tests created `Clock` instances but never initialized the global default context. The cause of the failures probably had something to do with `Clock` removing its shutdown callback from the global default context in its destructor.
This ties into another problem with the PR: the `Clock::sleep_until` would wake …
> Re-add Clock::sleep_until

- rclcpp/test/rclcpp/test_time_source.cpp
Required by ros2/rcl#948
Part of fixing ros2/rcl#947
> min_forward & min_backward thresholds must not be disabled

- rclcpp/resource/logging.hpp.em
- rclcpp/test/rclcpp/test_logging.cpp
This allows the logger macro to expand "correctly", i.e. macro
argument expression is fully evaluated before use.
Addresses #1819.
Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>
> Use parantheses around logging macro parameter

- rclcpp/CMakeLists.txt
- rclcpp/package.xml
Calls the `ament_cmake_gen_version_h` function to generate and
install a header file containing `rclcpp` version information.
Provides compile-time version information for `rclcpp`.
Closes #1804.
Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>
> [rclcpp] Generate version header

- rclcpp/include/rclcpp/clock.hpp
- rclcpp/src/rclcpp/clock.cpp
Fixes #1829
The rcl and std::chrono steady clocks need to be synchronized because they may have different epoch's. This also warns about some gcc bugs, the discussion of which has happened before here: ros2/ros2#1080 .
> Synchronize rcl and std::chrono steady clocks in Clock::sleep_until

- rclcpp/include/rclcpp/clock.hpp
- rclcpp/src/rclcpp/clock.cpp
- rclcpp/test/rclcpp/test_time.cpp
Resolves #1730
This PR adds a new method`Clock::sleep_for()`. Internally it calls `sleep_until()`. This pattern of reusing the `_until()` method matches [`gcc`'s implementation of `condition_variable::wait_for()` using `condition_variable::wait_until()`](https://github.com/gcc-mirror/gcc/blob/a6e0d593707ae44dec0bdf2bcdc4f539050b46db/libstdc%2B%2B-v3/include/std/condition_variable#L158-L165).
> Add Clock::sleep_for()

- rclcpp/include/rclcpp/node_interfaces/node_base.hpp
- rclcpp/include/rclcpp/subscription_factory.hpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
It's intent to use another way to fix https://github.com/ros2/rclcpp/pull/1754 to prevent the separation of `rcl_node_init` and `rcl_node_fini`.
<del>and changing the creation behavior of subscription that not holding callback group to keep the consistency of other entities to make the test passed.</del>
> make node base sharable

- rclcpp_components/CMakeLists.txt
- rclcpp_components/include/rclcpp_components/component_manager.hpp
- rclcpp_components/include/rclcpp_components/component_manager_isolated.hpp
- rclcpp_components/src/component_container_isolated.cpp
- rclcpp_components/src/component_manager.cpp
- rclcpp_components/test/test_component_manager_api.cpp
Signed-off-by: zhenpeng ge <zhenpeng.ge@qq.com>
Related to https://github.com/ros2/rclcpp/issues/1774
it offer an “executor per component” behavior for container, we can use `use_dedicated_thread` parameter to enable this.
> support dedicated executor for component nodes

- rclcpp_components/include/rclcpp_components/component_manager_isolated.hpp
Signed-off-by: zhenpeng ge <zhenpeng.ge@qq.com>
PR #1781 make windows ci failed.
Acooding to suggestion from @SteveMacenski , try to fix it by instantiating template class `ComponentManagerIsolated`.
> fix failed windows ci of PR1781 by removing unnecessary RCLCPP_COMPONENTS_PUBLIC

- rclcpp/include/rclcpp/subscription.hpp
minor fix, corresponding to `Publisher` constructor.
> use private member to keep the all reference underneath.

- rclcpp/include/rclcpp/function_traits.hpp
- rclcpp/include/rclcpp/wait_set_policies/sequential_synchronization.hpp
- rclcpp/include/rclcpp/wait_set_policies/thread_safe_synchronization.hpp
- rclcpp/test/utils/rclcpp_gtest_macros.hpp
- rclcpp_action/src/client.cpp
Links to https://github.com/ament/uncrustify_vendor/pull/27 ; see that PR for more information and CI.
> Fixes for uncrustify 0.72

- rclcpp/test/rclcpp/test_node.cpp
This test is only for simple types (no arrays) mentioned in documentation chapter "[About parameters in ROS 2](https://docs.ros.org/en/galactic/Concepts/About-ROS-2-Parameters.html)". It's a follow up of #1743 since not all types with function templates are tested yet. The type mappings can be found [here](https://docs.ros.org/en/foxy/Concepts/About-ROS-Interfaces.html#field-types).
> Add tests for function templates of declare_parameter

- rclcpp/include/rclcpp/publisher_base.hpp
- rclcpp/test/rclcpp/test_publisher.cpp
> Add wait_for_all_acked support

- rclcpp/include/rclcpp/exceptions/exceptions.hpp
- rclcpp/include/rclcpp/node_impl.hpp
- rclcpp/test/rclcpp/test_node.cpp
A previous commit (fd8cfa8fe3e61c9dc2bf2e7918a24c883982b6b6) introduced `InvalidParameterTypeException` which was an improved version of `ParameterTypeException` in the sense that it also included parameter name in the error message.
One of the places that raised this exception was `declare_parameter` function. Now as you can see in [this git-blame piece](https://github.com/ros2/rclcpp/blame/master/rclcpp/include/rclcpp/node_impl.hpp#L201-L230), a later commit (24bb65305d47bf8562e2b38432bfb5ed248d9047) added a second version of `declare_parameter` but the author forgot to use `InvalidParameterTypeException` there which leads to less useful messages. This PR fixes the issue.
> Use UninitializedStaticallyTypedParameterException

- rclcpp_components/CMakeLists.txt
Currently any rclcpp component is forced to depend on and link against the component manager. Plugins actually just need access to `rclcpp_component`'s headers which themselves use `rclcpp` and `class_loader`. This adds and exports a new CMake interface library `rclcpp_components::component` that can be depended upon by components.
Part of ament/ament_cmake#365
> Add rclcpp_components::component target

- rclcpp/resource/logging.hpp.em
Renames the std::stringstream in the logging stream macros from ss to something more unique.
> Rename stringstream in macros to a more unique name

- rclcpp/src/rclcpp/detail/resolve_parameter_overrides.cpp
- rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
- rclcpp/src/rclcpp/signal_handler.cpp
- rclcpp/test/rclcpp/test_intra_process_manager.cpp
- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/include/rclcpp_action/client_goal_handle.hpp
- rclcpp_action/include/rclcpp_action/create_client.hpp
- rclcpp_action/include/rclcpp_action/create_server.hpp
- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
- rclcpp_action/include/rclcpp_action/types.hpp
- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
- rclcpp_action/src/server_goal_handle.cpp
- rclcpp_action/test/test_client.cpp
- rclcpp_action/test/test_server.cpp
- rclcpp_action/test/test_server_goal_handle.cpp
Relates to https://github.com/ament/ament_lint/pull/324
> Fix include order and relative paths for cpplint

- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_publisher_with_type_adapter.cpp
- rclcpp/test/rclcpp/test_subscription_with_type_adapter.cpp
They had a bunch of unnecessary infrastructure, so just simplify them to what they actually need.  This also makes them run with less warnings, which is a nice side benefit.
> Cleanup the TypeAdapt tests

- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_publisher.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/managed_entity.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
- rclcpp_lifecycle/src/managed_entity.cpp
- rclcpp_lifecycle/test/test_lifecycle_publisher.cpp
Fixes https://github.com/ros2/rclcpp/issues/1846.
Similar to what was done in rclpy: https://github.com/ros2/rclpy/pull/865.
Demo: https://github.com/ros2/demos/pull/552.
> Automatically transition lifecycle entities when node transitions

- rclcpp_components/src/component_manager.cpp
- rclcpp_components/test/test_component_manager_api.cpp
Signed-off-by: zhenpeng ge <zhenpeng.ge@qq.com>
related to https://github.com/ros2/rclcpp/issues/978#. 
i'm trying to implement composed bringup for Nav2, but it can't work as expected. the reason is that internal nodes (like `local_costmap`, `global_costmap`) in Nav2 couldn't  load parameters from param's file(`use_global_arguments` is setting `false`) https://github.com/ros2/rclcpp/blob/f30329fbec79cb699f41a37cc27c0c475de3edc1/rclcpp_components/src/component_manager.cpp#L164
according to @wjwwood opinion( https://github.com/ros2/rclcpp/issues/978#issuecomment-593718794 ),    `allow_undeclared_parameters` and `use_global_arguments` shouldn't be a parameter,  but the `use_global_arguments`  does have a legitimate use case here (for Nav2), and i think it's useful when we have a large …
> add use_global_arguments for node options of component nodes

- rclcpp/include/rclcpp/time_source.hpp
- rclcpp/src/rclcpp/time_source.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
Previously, we were managing a bunch of internal objects with shared_ptr/weak_ptr.  But this was an unnecessary abstraction, and also lead to flaky tests as in #1861 .
Instead, simplify this quite a lot and just use normal C++ object lifetimes.  This is easier to understand, is less code, and also fixes the flaky test.
Supersedes #1865.
Fixes #1861 
@Barry-Xu-2018 @ralph-lange FYI.
> Cleanup time source object lifetimes

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/test/rclcpp/test_executor.cpp
This PR addresses a problem I recently noticed when you start an executor in a separate thread.
For example:
```
auto executor = std::make_shared<SingleThreadedExecutor>();
std::thread executor_thread([&](){
executor->spin();
});
//// When I reach this line I don't have any way to know whether the executor is already spinning or not.
executor->cancel(); // This call may be uneffective as it may get executed before the executor starts to spin
/// Similarly, if I have to do an operation that requires the executor to be spinning
```
There are hacky solutions to this, for example I added a node with a one shot timer with period 0 to the executor such that I can guarantee that after that timer triggers the executor is definitely spinning.
However this looks very bad and it could be done in a …
> add is_spinning() method to executor base class

- rclcpp/include/rclcpp/any_subscription_callback.hpp
Subscription callbacks of types `ConstSharedPtrCallback` and `ConstSharedPtrWithInfoCallback` were not getting registered.
See: https://gitlab.com/ros-tracing/tracetools_analysis/-/issues/47#note_817008890
Switching to something like this (in `galactic`) would be better, but the change would be less minimal: https://github.com/ros2/rclcpp/blob/468cbab1aa9efb0f18b8d3f5cd410d2a9f21b3c6/rclcpp/include/rclcpp/any_subscription_callback.hpp#L372-L384
> Fix subscription instrumentation for ConstSharedPtr[WithInfo]Callback

- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_impl.hpp
- rclcpp/test/rclcpp/test_node.cpp
I think it's useful if we can use the return value version of `get_parameter_or` because we can make the variable const.
Normally, we can get the parameter value by `declare_parameter`, but I guess it can't be used when we use `automatically_declare_parameters_from_overrides`.
Is it possible to add this or are there any other ways?
> Add return value version of get_parameter_or

- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
- rclcpp_lifecycle/test/test_lifecycle_publisher.cpp
address https://github.com/ros2/rclcpp/issues/1884
> LifecycleNode::on_deactivate deactivate all managed entities.

- rclcpp_components/include/rclcpp_components/component_manager_isolated.hpp
Replace `spin_until_future_complete` with `spin` in `component_manager_isolated.hpp`.
`spin_until_future_complete()` is more inefficient as it needs to check the state of the future and the timeout after every work iteration.
This PR addresses the race-condition issues mentioned in https://github.com/ros2/rclcpp/pull/1781 by using the recently added `is_spinning()` API
Tests on the navigation stack show 10% less CPU usage when using `spin()` rather than `spin_until_future_complete()`
FYI @SteveMacenski @gezp @ivanpauno
> Use spin() in component_manager_isolated.hpp

- rclcpp/include/rclcpp/wait_for_message.hpp
- rclcpp/test/rclcpp/test_wait_for_message.cpp
to fix https://github.com/ros2/rclcpp/issues/1864
> fix one subscription can wait_for_message twice

- rclcpp/CMakeLists.txt
Part of https://github.com/ament/ament_cmake/pull/377 - this uses `ament_generate_version_header` instead of `ament_cmake_gen_version_h` to generate the version header. The installed header is identical.
> Use ament_generate_version_header

- rclcpp/CMakeLists.txt
- rclcpp_action/CMakeLists.txt
- rclcpp_components/CMakeLists.txt
- rclcpp_lifecycle/CMakeLists.txt
Part of ros2/ros2#1150 - this installs headers into a unique directory to prevent include directory search order issues when overriding packages from a merged workspace.
> Install headers to include/${PROJECT_NAME}

- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/test_qos_event.cpp
This PR removes the custom code paths that were checking `rmw_get_implementation_identifier()` on events-related tests.
Connected to ros2/rmw_fastrtps#583
> Remove fastrtps customization on tests

- rclcpp_components/src/node_main.cpp.in
Small improvements identified by clang tidy for the `node_main.cpp.in` file.
```
warning: loop variable is copied but only used as const reference; consider making it a const reference [performance-for-range-copy]
1:   for (auto clazz : classes) {
```
and
```
warning: implicit conversion 'int' -> bool [readability-implicit-bool-conversion]
1:     if (!(name.compare(class_name))) {
```
> small improvements to node_main.cpp.in

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/executors/static_single_threaded_executor.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/test/rclcpp/test_executor.cpp
address https://github.com/ros2/rclcpp/issues/1825
> spin_all with a zero timeout.

- rclcpp/include/rclcpp/callback_group.hpp
- rclcpp/include/rclcpp/memory_strategy.hpp
- rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
- rclcpp/src/rclcpp/callback_group.cpp
- rclcpp/src/rclcpp/memory_strategy.cpp
While doing some profiling of the rclcpp code, I noticed a few different places where we were unnecessarily doing work.  This PR has 3 commits that address each of these problems.
1. The first patch adds a new method to the `CallbackGroup` class that collects all of the pointers at once.  This avoids the overhead of taking and dropping the mutex inside of `CallbackGroup` over and over.  I incidentally don't love the name `collect_all_ptrs`, so I'm happy to rename that to something else.
2. The second patch changes the API of the `MemoryStrategy` class to pass the shared_ptrs as const-ref in the APIs.  Since the default implementation doesn't need to hold an additional reference, this reduces overhead for creating and destroying the shared_ptr class quite a bit.  If a subclass were written …
> Micro-optimizations in rclcpp

- rclcpp/include/rclcpp/timer.hpp
- rclcpp/src/rclcpp/timer.cpp
- rclcpp/test/rclcpp/test_timer.cpp
This PR changes `rclcpp::TimerBase::time_until_trigger` to return `std::chrono::nanoseconds::max()` if the timer is canceled, since is does not seem correct to return the `rcl_timer_get_time_until_next_call` if the timer won't be called at that time.
Signed-off-by: Mauro Passerino <mpasserino@irobot.com>
> time_until_trigger returns max time if timer is cancelled

- rclcpp/Doxyfile
- rclcpp/include/rclcpp/detail/cpp_callback_trampoline.hpp
- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/logger.hpp
- rclcpp/include/rclcpp/parameter.hpp
- rclcpp/include/rclcpp/wait_set_policies/detail/write_preferring_read_write_lock.hpp
- rclcpp_action/Doxyfile
- rclcpp_action/include/rclcpp_action/client_goal_handle.hpp
- rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
- rclcpp_action/include/rclcpp_action/types.hpp
- rclcpp_components/Doxyfile
- rclcpp_lifecycle/Doxyfile
There are a smattering of problems in here:
1.  We weren't properly using PREDEFINE for all of our macros.
2.  The Doxyfiles were referencing tag files that may not exist
(this will be handled by rosdoc2 automatically).
3.  The C++ parser in doxygen can't handle "friend classname",
but can handle "friend class classname"; it shouldn't matter
one way or the other to the compiler.
4.  There were a couple of parameters that were not documented.
5.  The doxygen C++ parser can't handle decltype in all situations.
6.  There was a structure using a C-style declaration.
This patch fixes all of the above issues.  We still aren't totally
clean on a rosdoc2 build, but we are a lot closer.
> Fix a bunch more rosdoc2 issues in rclcpp.

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/service.hpp
- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp/src/rclcpp/client.cpp
- rclcpp/src/rclcpp/service.cpp
- rclcpp/test/rclcpp/test_client.cpp
- rclcpp/test/rclcpp/test_service.cpp
Blocked by:
https://github.com/ros2/rcl/pull/941
Signed-off-by: Mauro Passerino <mpasserino@irobot.com>
> Add client/service QoS getters

- rclcpp_components/cmake/rclcpp_components_register_node.cmake
- rclcpp_components/src/node_main.cpp.in
This PR enables selection of executor type in `rclcpp_components_register_node` in `CMakeLists.txt`. 
So far, `SingleThreadedExecutor` is hard-coded.
FYI, I need this option to use of `MultiThereadedExecutor` because my node contains nested callback.
> Select executor in node registration

- rclcpp/test/rclcpp/test_publisher.cpp
This PR updates a unit test for the `wait_for_acknowledgments()` API by increasing the timeout from 500ms to 6s.
This change allows the test to successfully and reliably pass when run with `rmw_connextdds`. The reason for this change is that Connext DDS usese a 3s periodic heartbeat by default, so it may take quite longer than 500ms to detect and repair a missed sample. 6s guarantees that at least one heartbeat will be published while waiting for all samples to be acknowledged.
The failure of the test was identified while working on ros2/rmw_connextdds#76, after running the Linux CI with only `rmw_connextdds` enabled.
> Increase timeout for acknowledgments

- rclcpp/test/rclcpp/test_client.cpp
- rclcpp/test/rclcpp/test_service.cpp
- rclcpp/test/rclcpp/test_subscription.cpp
This PR updates some unit tests related to the data callbacks for subscriptions, clients, and services, to make them more robust when run on different RMWs.
The changes were identified while investigating [some failures observed when running the tests with `rmw_connextdds`](https://github.com/ros2/rmw_connextdds/pull/76#issuecomment-1071783755) as part of ros2/rmw_connextdds#76.
In particular, all tests at one point try to publish 3 messages and subsequently expect all 3 samples to be notified via callback.
For this to happen reliably, the endpoints should all be using a History depth of at least 3. Moreover, the tests should wait for the counter variable to be increased up to 3 before making any further assertion.
> Update data callback tests to account for all published samples.

- rclcpp/CMakeLists.txt
This package uses rcl_interfaces directly, and we've been getting away with the missing dependency because `rcl` has the entirety of `rcl_interfaces` as part of its link interface even tough it doesn't need to.
If (when) `rcl` scopes its dependency to only the c generator and drops the cpp generator from its link interface, this package will fail to find the cpp symbols at link time. This change remedies that.
Example location where `rclcpp` references `rcl_interfaces` directly:
https://github.com/ros2/rclcpp/blob/49c2dd481342333328ffacb5f949b89b95395e32/rclcpp/include/rclcpp/node.hpp#L35-L38
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16412)](http://ci.ros2.org/job/ci_linux/16412/)
* Linux-aarch64 [![Build …
> Add missing ament dependency on rcl_interfaces

- rclcpp/include/rclcpp/generic_publisher.hpp
- rclcpp/include/rclcpp/publisher_base.hpp
- rclcpp/src/rclcpp/generic_publisher.cpp
- rclcpp/src/rclcpp/publisher_base.cpp
- rclcpp/test/rclcpp/test_generic_pubsub.cpp
> Add publish by loaned message in GenericPublisher

- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
In `__check_parameters`, there are function-scoped parameter
descriptor structures generated by searching the `ParameterInfo`
map provided from other declaratory functions. This PR populates
this temporary structure with the parameter name information.
This way, the change does not show in other data structures, but the
name field is also not empty when used to generate error messages in
`__check_parameter_value_in_range`.
See this [demo node](https://github.com/aprotyas/ros2_playground/tree/master/rclcpp_1906) for testing purposes.
Fixes #1906.
Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>
> [NodeParameters] Set name in param info pre-check

- rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/include/rclcpp/waitable.hpp
- rclcpp/src/rclcpp/waitable.cpp
- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
This PR is a follow-up to https://github.com/ros2/rclcpp/pull/1579 and it adds the last API required to implement executors based on RMW listeners.
Since these executors wouldn't use a waitset, they need an alternative way to select which entities are ready to do work inside a waitable (which potentialyl can be made up of multiple entities).
The `on_ready_callback` listener API already includes an entity ID, which then can be used to call the new `take_data_by_entity_id()` function.
> add take_data_by_entity_id API to waitable

- rclcpp/include/rclcpp/timer.hpp
- rclcpp/test/rclcpp/test_create_timer.cpp
address https://github.com/ros2/rclcpp/issues/1915
> use reinterpret_cast for function pointer conversion.

- rclcpp/include/rclcpp/qos.hpp
- rclcpp/src/rclcpp/qos.cpp
- rclcpp/test/rclcpp/test_qos.cpp
If users set a policy as 'best available', then the middleware will pick a policy
that is most compatible with the current set of discovered endpoints while maintaining
the highest level of service possible.
For details about the expected behavior, see connected changes:
- https://github.com/ros2/rmw/pull/320
- https://github.com/ros2/rmw_dds_common/pull/60
> Add 'best available' QoS enum values and methods

- rclcpp/include/rclcpp/parameter_event_handler.hpp
- rclcpp/src/rclcpp/parameter_event_handler.cpp
- rclcpp/test/rclcpp/test_parameter_event_handler.cpp
> Update get_parameter_from_event to follow the function description

- rclcpp/include/rclcpp/publisher_options.hpp
- rclcpp/include/rclcpp/subscription_options.hpp
This fails with g++ -std=gnu++20.
> Drop wrong template specialization

- rclcpp/include/rclcpp/subscription.hpp
Add statistics for handle_loaned_message().   
If loan message is enabled,  some tests in test_subscription_topic_statistics fail.  This issue is found in https://github.com/ros2/rmw_fastrtps/pull/568#issuecomment-1123412147
> Add statistics for handle_loaned_message

- rclcpp/include/rclcpp/guard_condition.hpp
- rclcpp/src/rclcpp/guard_condition.cpp
- rclcpp/test/rclcpp/test_guard_condition.cpp
Ttrigger guard condition waitset regardless of whether a trigger callback is present
This should address https://github.com/ros2/rclcpp/issues/1917
Also minor cleanup at the class (remove unneded lock and better use of if-else)
> Always trigger guard condition waitset

- rclcpp/resource/logging.hpp.em
In the pull request https://github.com/ros2/rclcpp/pull/1442 the ability
to use `std::string` as the first argument to the logging functions was
(rightfully) removed.
This commit just corrects the documentation of the macro, since it
confused me a bit ;)
> Fix documentation of `RCLCPP_[INFO,WARN,...]`

- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/test/rclcpp/test_any_subscription_callback.cpp
I think this was broken when support for type adaption was added.
Currently if you create a serialized subscription with a callback taking both the message and the message info, the executor throws an exception the first time a message is dispatched.
This fixes the issue.
> Fix subscription.is_serialized() for callbacks with message info

- rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
I could be wrong, but this callback seems to be obsolete – there is no way to set it through the public API.
> Remove unused on_parameters_set_callback_

- rclcpp/include/rclcpp/context.hpp
- rclcpp/include/rclcpp/graph_listener.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base.hpp
- rclcpp/include/rclcpp/node_interfaces/node_logging_interface.hpp
- rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
- rclcpp/src/rclcpp/context.cpp
- rclcpp/src/rclcpp/graph_listener.cpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/src/rclcpp/node_interfaces/node_logging.cpp
- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
fixes https://github.com/space-ros/space-ros/issues/8
~~I might come back and try to de-duplicate some of the code, but I couldn't find a nice solution yet.~~
> fix virtual dispatch issues identified by clang-tidy

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/executors.hpp
- rclcpp/include/rclcpp/future_return_code.hpp
- rclcpp/include/rclcpp/rclcpp.hpp
- rclcpp/src/rclcpp/parameter_client.cpp
- rclcpp/src/rclcpp/time_source.cpp
- rclcpp/test/benchmark/benchmark_client.cpp
- rclcpp/test/benchmark/benchmark_executor.cpp
- rclcpp/test/benchmark/benchmark_service.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/executors/test_static_single_threaded_executor.cpp
- rclcpp/test/rclcpp/test_executor.cpp
- rclcpp/test/rclcpp/test_intra_process_manager_with_allocators.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
- rclcpp/test/rclcpp/test_qos_event.cpp
- rclcpp/test/rclcpp/topic_statistics/test_subscription_topic_statistics.cpp
- rclcpp_action/test/benchmark/benchmark_action_client.cpp
- rclcpp_action/test/benchmark/benchmark_action_server.cpp
- rclcpp_action/test/test_client.cpp
- rclcpp_action/test/test_server.cpp
- rclcpp_components/test/test_component_manager_api.cpp
Introduce executors new spin_for method, replace spin_until_future_complete with spin_until_complete. (#1821)
* Introduce spin_for method.
* Introduce spin_until_complete.
* Deprecate spin_until_future_complete.
* Replace usage of deprecated method.
* Update unit-tests.
Signed-off-by: Hubert Liberacki <hliberacki@gmail.com>
> Add support for spin_until_timeout (#1821)

- rclcpp/include/rclcpp/parameter_map.hpp
- rclcpp/src/rclcpp/detail/resolve_parameter_overrides.cpp
- rclcpp/src/rclcpp/parameter_map.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_parameters.cpp
- rclcpp/test/rclcpp/test_parameter_map.cpp
- rclcpp/test/resources/test_node_parameters/complicated_wildcards.yaml
- rclcpp/test/resources/test_node_parameters/params_by_order.yaml
- rclcpp/test/resources/test_node_parameters/wildcards.yaml
to fix https://github.com/ros2/rcl/issues/954
My intent is to use regex for supporting some complicated wildcard, such as `/**/a/b/*/c/d/*/node`.
I think that the same param name in a node of param file parsed by order seems more reasonable than the order(`/**`, `specific_node`).  Because if there are more wildcards items, such `/**/node`, `/ns/**/node`, etc, I don't think users would like to memory these special rules.
Note: I can also use a 'std::set<..,std::less>' to store the node keys(`*` < `/` < `alpha/num`), and then move all the relative items iterator into `{specific_node, {}}`
> use regex for wildcard matching

- rclcpp/include/rclcpp/create_client.hpp
- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_impl.hpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/test_client.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
- rclcpp/test/rclcpp/test_service.cpp
- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
- rclcpp_lifecycle/test/test_client.cpp
This adds a version of `create_client` that accepts `rclcpp::QoS` instead of `rmw_qos_profile_t`. It's available via `rclcpp::create_client`, `rclcpp::Node::create_client`, and `rclcpp_lifecycle::LifecycleNode::create_client`.
While here I also made the implementation of `rclcpp_lifecycle::LifecycleNode::create_client` use the free function `rclcppp::create_client`.
> Make create_client accept rclcpp::QoS

- rclcpp/include/rclcpp/create_service.hpp
- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_impl.hpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/test_client.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
- rclcpp/test/rclcpp/test_service.cpp
- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
- rclcpp_lifecycle/test/test_service.cpp
Follow up to #1964, this allows using `rclcpp::QoS` with `create_service` and deprecates the version taking `rmw_qos_profile_t`
> Make create_service accept rclcpp::QoS

- rclcpp/src/rclcpp/parameter_map.cpp
to fix https://github.com/ros2/rclcpp/issues/1993
> fix memory leak

- rclcpp/include/rclcpp/node.hpp
I've been burned by ignoring the return value and so has a few others -- adding a note about the lifetime of the registered callback being tied to the returned callback handle further up the documentation should help others avoid making the same mistake.
Signed-off-by: Brian Chen <brian.chen@openrobotics.org>
> [docs] add note about callback lifetime for {on, post}_set_parameter_callback

- rclcpp/include/rclcpp/create_timer.hpp
- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_impl.hpp
- rclcpp/test/rclcpp/test_create_timer.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
- rclcpp/test/rclcpp/test_timer.cpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
- rclcpp_lifecycle/test/test_lifecycle_publisher.cpp
This reverts #1975 because it seems to have caused a build error in `tf2_ros`.
https://github.com/ros2/rclcpp/pull/1975#issuecomment-1231953781
Next steps:
* If the issue is a bug, then please open a PR again to rclcpp with a fix
* If the issue is it changed an API used by tf2_ros, then please open a PR on rclcpp again plus open a PR on the [geometry2 repo](https://github.com/ros2/geometry2/) that updates its use of the API. 
@asymingt + @ivanpauno + @jacobperron  FYI
> Revert "Add a `create_timer` method to `Node` and `LifecycleNode` classes (#1975)"

- rclcpp/include/rclcpp/parameter_event_handler.hpp
force  a compiler warning if callback handles are not captured. 
clarify documentation to show that not capturing returned handles
will result in callbacks immediately being unregistered
see issue https://github.com/ros2/rclcpp/issues/1998
Signed-off-by: Jason Beach
> force compiler warning if callback handles not captured

- rclcpp/include/rclcpp/create_timer.hpp
- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_impl.hpp
- rclcpp/test/rclcpp/test_create_timer.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
- rclcpp/test/rclcpp/test_timer.cpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
- rclcpp_lifecycle/test/test_lifecycle_publisher.cpp
... and fixes the bug introduced in the original PR.
> Revert "Revert "Add a create_timer method to Node and `LifecycleNode` classes (#1975)" (#2009)

- rclcpp/include/rclcpp/parameter_client.hpp
- rclcpp/include/rclcpp/parameter_map.hpp
- rclcpp/src/rclcpp/parameter_client.cpp
- rclcpp/src/rclcpp/parameter_map.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_parameter_client.cpp
- rclcpp/test/resources/test_node/load_complicated_parameters.yaml
- rclcpp/test/resources/test_node/no_valid_parameters.yaml
to implement https://github.com/ros2/rclcpp/issues/1997
> support regex match for parameter client

- rclcpp/include/rclcpp/parameter_client.hpp
- rclcpp/include/rclcpp/parameter_service.hpp
- rclcpp/src/rclcpp/parameter_client.cpp
- rclcpp/src/rclcpp/parameter_service.cpp
> Make ParameterService and Sync/AsyncParameterClient accept rclcpp::QoS

- rclcpp_components/src/node_main.cpp.in
related to https://github.com/ros2/rcl/issues/1009#issuecomment-1248946519
> use unique ptr and remove unuseful container

- rclcpp/include/rclcpp/node_interfaces/node_base.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
- rclcpp/include/rclcpp/node_interfaces/node_graph.hpp
- rclcpp/include/rclcpp/node_interfaces/node_parameters.hpp
- rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
- rclcpp/include/rclcpp/node_interfaces/node_topics_interface.hpp
This may help the compile error we are seeing in https://github.com/ros2/geometry2/pull/555 .  Even if it doesn't, it is the right thing to do.
> Make sure to include-what-you-use in the node_interfaces.

- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_publisher.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/state.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/transition.hpp
- rclcpp_lifecycle/package.xml
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
- rclcpp_lifecycle/src/node_interfaces/lifecycle_node_interface.cpp
- rclcpp_lifecycle/src/state.cpp
- rclcpp_lifecycle/src/transition.cpp
- rclcpp_lifecycle/test/test_client.cpp
- rclcpp_lifecycle/test/test_lifecycle_service_client.cpp
- rclcpp_lifecycle/test/test_service.cpp
- rclcpp_lifecycle/test/test_transition_wrapper.cpp
That is, make sure they are all listed in package.xml, found in the CMakeLists.txt, and properly included where they are used.
There should be no functional change from this PR; I just noticed all of this while reviewing other PRs touching the lifecycle stuff.
> Cleanup the rclcpp_lifecycle dependencies.

- rclcpp/CMakeLists.txt
Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>
Cpplint test is timing out on Windows machines. 
```
3/104 Test   #3: cpplint ................................................***Timeout 120.01 sec
```
| line | duration |
| ----- | ---------- |
|`3:  - C:/ci/ws/install/Scripts/ament_cpplint.exe --xunit-file C:/ci/ws/build/rclcpp/test_results/rclcpp/cpplint.xunit.xml` | +6 seconds |
| `3: Done processing C:\ci\ws\src\ros2\rclcpp\rclcpp\include\rclcpp\node_interfaces\node_time_source_interface.hpp` [File](https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/node_interfaces/node_time_source_interface.hpp) | +6 seconds |
| `03:51:30.157  3: Done processing C:\ci\ws\src\ros2\rclcpp\rclcpp\src\rclcpp\init_options.cpp` …
> Set cpplint timeout to 3 mins

- rclcpp/src/rclcpp/signal_handler.cpp
If rclcpp is inited with rclcpp::SignalHandlerOptions::None,  signal_handler_thread will not be created.
Checking thread whether is joinable before join is a solution to this little bug.
> check thread whether joinable before join

- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
This series of patches cleans up the code that implements `LifecycleNodeInterfaceImpl`, the PIMPL interface for the `LifecycleNode` class.  In particular, it does the following things:
1.  Moves the implementation from completely in a header file into a split header file/source file.  This class is not templated, so there is no reason the implementation has to be in the header file.
2. Marks the `LifecycleNodeInterfaceImpl` class as `final` (nothing can possibly derive from it).
3. Updates some documentation.
4. Marks a number of methods inside of `LifecycleNodeInterfaceImpl` as `const`.
5. Makes quite a bit of the internals of `LifecycleNodeInterfaceImpl` private.
6. Disables copies of `LifecycleNodeInterfaceImpl`.
7. Marks some methods from `LifecycleNode` as const.
The main goal here …
> Cleanup the lifecycle implementation

- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
We should only need to update the current state when it changes, so we do that in the change_state method (which is not const). Then we can just return the current_state_ object in get_current_state, and then mark it as const.
@fujitatomoya FYI.  Once we have this in, I think we can then rebase #1756 and it should make a lot more sense.
> Make lifecycle impl get_current_state() const.

- rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
Signed-off-by: Alexis Paques <paa1ti@bosch.com>
Closes https://github.com/ros2/rclcpp/issues/2029
This ensures the number of threads of a **Multi-threaded executor** is at least 2 unless defined explicitly as 1 (why not use the SingleThreadedExecutor?)
Indeed, if we are calling a service from a callback and call the get function of the future directly, we effectively block until the service request resolves but it can't as the reply will not be processed, causing a deadlock. This is either solved by having a Multi-threaded executor and multiple callback groups for non time critical software (which has to wait for the result anyway).
The default number of threads is `std::thread::hardware_concurrency` which can be 1 for a VM or a small target. 
This means those targets (or VM) will **not** …
> Set the minimum number of threads of the Multithreaded executor to 2

- rclcpp/include/rclcpp/callback_group.hpp
- rclcpp/include/rclcpp/executor.hpp
- rclcpp/src/rclcpp/callback_group.cpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/src/rclcpp/node_interfaces/node_services.cpp
- rclcpp/src/rclcpp/node_interfaces/node_timers.cpp
- rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
- rclcpp/src/rclcpp/node_interfaces/node_waitables.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
a subscriber on a new executor with a callback group triggered to receive a message
related to https://github.com/ros2/rclcpp/issues/1611
> Fix bug that a callback not reached

- rclcpp_lifecycle/include/rclcpp_lifecycle/state.hpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
- rclcpp_lifecycle/src/state.cpp
fix https://github.com/ros2/rclcpp/issues/1746
> Bugfix 20210810 get current state

- rclcpp/include/rclcpp/executors/multi_threaded_executor.hpp
minor comment follow-up for https://github.com/ros2/rclcpp/pull/2030
> MultiThreadExecutor number of threads is at least 2+ in default.

- rclcpp_lifecycle/include/rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp
@clalancette minor doc fix, i think this is just missed from https://github.com/ros2/rclcpp/pull/2027?
> LifecycleNode on_configure doc fix.

- rclcpp/include/rclcpp/node.hpp
- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
- rclcpp/src/rclcpp/parameter_service.cpp
- rclcpp/test/rclcpp/test_node.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
to fix https://github.com/ros2/rclcpp/issues/2035 and https://github.com/ros2/rclcpp/issues/2038
> fix a case that not throw ParameterUninitializedException

- rclcpp/include/rclcpp/clock.hpp
- rclcpp/src/rclcpp/clock.cpp
I think `now()` can be marked as `const`. All it does is [call rcl_clock_get_now()](https://github.com/ros2/rclcpp/blob/91bc312190e61c8915b0152e5c927c987fc22d6c/rclcpp/src/rclcpp/clock.cpp#L71-L80) which [doesn't look like it modifies the clock to me](https://github.com/ros2/rcl/blob/e4f7e1367dfda83d3e309397f9201642ebe38618/rcl/src/rcl/time.c#L268-L280).
* When `get_now` is `rcl_get_ros_time`: https://github.com/ros2/rcl/blob/e4f7e1367dfda83d3e309397f9201642ebe38618/rcl/src/rcl/time.c#L65-L73
* When `get_now` is `rcl_get_system_time`: https://github.com/ros2/rcl/blob/e4f7e1367dfda83d3e309397f9201642ebe38618/rcl/src/rcl/time.c#L44-L48
* When `get_now` is `rcl_get_steady_time`: https://github.com/ros2/rcl/blob/e4f7e1367dfda83d3e309397f9201642ebe38618/rcl/src/rcl/time.c#L36-L40
> Mark rclcpp::Clock::now() as const

- rclcpp/src/rclcpp/qos.cpp
- rclcpp/test/rclcpp/test_qos_parameters.cpp
It really doesn't make much sense to have a KeepLast depth of 0; no data could possibly be stored.  Indeed, the underlying DDS implementations don't actually support this.  It currently "works" because a KeepLast depth of 0 is assumed to be system default, so the RMW layer typically chooses "1" instead.  But this isn't something we should be encouraging users to do, so add a warning.
I'll note that I could easily be convinced to make this throw an exception instead.  That would be a much stronger warning to users not to do this, but it does break existing practice so has some risk of downstream breakage.  Happy to discuss it.
> Add in a warning for a KeepLast depth of 0.

- rclcpp/include/rclcpp/generic_subscription.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/include/rclcpp/subscription_options.hpp
- rclcpp/test/rclcpp/node_interfaces/test_node_topics.cpp
`to_rcl_subscription_options` no longer needs a template parameter, so I'm just removing it to trim bloat.
> Remove templating on to_rcl_subscription_options

- rclcpp/include/rclcpp/client.hpp
- rclcpp/test/rclcpp/test_client.cpp
> fix nullptr dereference in prune_requests_older_than

- rclcpp/include/rclcpp/node_interfaces/node_clock.hpp
- rclcpp/include/rclcpp/node_options.hpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp/src/rclcpp/node_interfaces/node_clock.cpp
- rclcpp/src/rclcpp/node_options.cpp
- rclcpp/src/rclcpp/time_source.cpp
- rclcpp/test/rclcpp/test_node.cpp
- rclcpp/test/rclcpp/test_node_options.cpp
- rclcpp/test/rclcpp/test_time_source.cpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
Signed-off-by: Jeffery Hsu [jefferyyjhsu@gmail.com](mailto:jefferyyjhsu@gmail.com)
This PR adds the option for selecting clock source in Node/LifecycleNode thru NodeOptions.
A similar option is already present in rclcpp::Timer but it is currently missing in Nodes/LifecycleNode. There's currently no way to set Node::now() and all other time-related functions to use clock sources other than ROS_TIME.
> Add clock type to node_options

- rclcpp/resource/logging.hpp.em
When I was building my project (CMAKE_CXX_STANDARD 20) with rclcpp on Windows, it failed with the same error as described in https://github.com/ros2/rclcpp/issues/1973 (c++17 + [permissive flag](https://learn.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance?view=msvc-170) added to MSVC). The same flag is set implicitly with C++20 because is required for C++20 Modules support.
I was trying to investigate why the template in logging macro is not passing standards conformance, but I was not able to find it out. It seems to be an MSVC issue. A similar problem was reported in [Microsoft Developer Community](https://developercommunity.visualstudio.com/t/the-c2039-type-is-not-a-member-of-std-error-in-def/1562967) more than a year ago and has not been resolved yet.
I used …
> Fix logging macros to build with msvc and cpp20

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/detail/cpp_callback_trampoline.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/include/rclcpp/service.hpp
- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
This is to fix seg-faults happening when compiling with `-O2` or `-O3` optimizations.
They happened because we did:
https://github.com/ros2/rclcpp/blob/338eed0c060ab58608fc6e44c6936bde2c4e061e/rclcpp/include/rclcpp/client.hpp#L289
assuming that `auto` was deduced to be a `std::function<void(size_t)>`. 
And then, to the trampoline, we say we were passing a function returning `void*` and with an arg of type `size_t`
https://github.com/ros2/rclcpp/blob/338eed0c060ab58608fc6e44c6936bde2c4e061e/rclcpp/include/rclcpp/client.hpp#L314-L316
But when compiling with optimizations, the `auto new_callback = ...` signature seems to change to other type. So then the `trampoline` function failed when did the cast back:
https://github.com/ros2/rclcpp/blob/338eed0c060ab58608fc6e44c6936bde2c4e061e/rclcpp/inc …
> Set explicitly callback type

- rclcpp/include/rclcpp/generic_publisher.hpp
- rclcpp/include/rclcpp/generic_subscription.hpp
- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/include/rclcpp/publisher_base.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp/src/rclcpp/publisher_base.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_topics.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_type_support.cpp
> Move event callback binding to PublisherBase and SubscriptionBase

- README.md
Change README to point at the ROS Index for API 
Cfr. PR https://github.com/ros2/rclcpp/pull/2058
@clalancette
> API url info fix

- rclcpp/include/rclcpp/node_interfaces/node_interfaces.hpp
- rclcpp/test/rclcpp/node_interfaces/test_node_interfaces.cpp
The addition of the NodeInterfaces class made it stop compiling with older compilers (such as gcc 9.4.0 on Ubuntu 20.04). The error has to do with calling the copy constructor on rclcpp::Node, which is deleted.  Work around this by just getting rid of the nullptr check; it isn't actually needed, I don't think.
I'm honestly not sure that this is the best solution, but it definitely fixes the build on Ubuntu 20.04, and will likely fix the CI failures we are seeing in https://ci.ros2.org/view/nightly/job/nightly_linux-rhel_release/1370/ .  I could use further feedback from @methylDragon and @wjwwood .
> Add in a fix for older compilers.

- rclcpp/include/rclcpp/qos.hpp
- rclcpp/src/rclcpp/qos.cpp
If the user creates SystemDefaultsQoS setting, they are explicitly asking for SystemDefaults.  In that case, we should *not* warn, and just let the underlying RMW choose what it wants.  Implement that here by passing a boolean parameter through that decides when we should print out the warning, and then skip printing that warning when SystemDefaultsQoS is created.
> Fix the keep_last warning when using system defaults.

- rclcpp/include/rclcpp/context.hpp
- rclcpp/src/rclcpp/context.cpp
gcc 12 warns about this when compiling in release mode (i.e., with `-O2`):
```
In file included from /usr/include/c++/12/unordered_map:46,
from /usr/include/c++/12/functional:61,
from /home/ahans/src/ros2_rolling/src/ros2/rclcpp/rclcpp/include/rclcpp/context.hpp:19,
from /home/ahans/src/ros2_rolling/src/ros2/rclcpp/rclcpp/src/rclcpp/context.cpp:15:
In member function ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _Hash, _RangeHash, _Unused, _RehashPolicy, _Traits>::iterator std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _Hash, _RangeHash, _Unused, _RehashPolicy, _Traits>::_M_erase(size_type, __node_base_ptr, __node_ptr) [with _Key = std::shared_ptr<std::function<void()> >; _Value = std::shared_ptr<std::function<void()> >; _Alloc = …
```
> Fix -Wmaybe-uninitialized warning

- rclcpp/src/rclcpp/time_source.cpp
That is, in cache_last_msg(), we were just taking a shared_ptr reference.  While this is pretty fast, it also means that any changes to that message would be reflected internally. Instead, make a new shared pointer out of that message when it comes in, which essentially causes this to be a copy.
This should fix #2088 .  FYI @fujitatomoya and @mjcarroll .
> Fix clock state cached time to be a copy, not a reference.

- rclcpp/include/rclcpp/node_interfaces/detail/node_interfaces_helpers.hpp
- rclcpp/include/rclcpp/node_interfaces/node_interfaces.hpp
- rclcpp/test/rclcpp/node_interfaces/test_node_interfaces.cpp
This adds a default constructor. This allows a class to have an `interfaces` member that get's populated by an argument to it's constructor.
> Add default constructor to NodeInterfaces

- rclcpp/include/rclcpp/context.hpp
- rclcpp/src/rclcpp/context.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_context.cpp
Address #2096 
Signed-off-by: Barry Xu <barry.xu@sony.com>
> Fix bug on the disorder of calling shutdown callback

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
to fix https://github.com/ros2/rclcpp/issues/2067
> Topic node guard condition in executor

- rclcpp/include/rclcpp/timer.hpp
- rclcpp/src/rclcpp/timer.cpp
Based on https://github.com/ros2/rcl/pull/995, this PR adds support for the "on reset" callback for timers.
The issue which originated this need, is to wake up an events based executor when a timer is reset (which could also be caused by a time jump).
@alsora
> Add support for timers on reset callback

- rclcpp/include/rclcpp/qos_event.hpp
- rclcpp/src/rclcpp/qos_event.cpp
This PR contains a couple of small fixes:
- reorder members declaration in `qos_event.hpp`. this follows the same logic applied in https://github.com/ros2/rclcpp/pull/2024
- remove an unprotected read to `on_new_event_callback_`. the `clear_on_ready_callback` already checks if a callback exists and it does that under a mutex.
> fixes for rmw callbacks in qos_event class

- rclcpp/include/rclcpp/context.hpp
Fix https://github.com/ros2/rclcpp/issues/2106 . I also removed the reference to `rclcpp::init` as it does take in input a `Context`, I added instead the method to call to specify the context to use for a given node, please correct me if I was wrong on that.
As an alternative, we can also get rid of that sentence.
> Fix documentation of Context class

- rclcpp/test/rclcpp/test_time_source.cpp
I encounter the falky test about TestTimeSource.callbacks some times.
```
/tmp/ws/src/rclcpp/rclcpp/test/rclcpp/test_time_source.cpp:426
Expected equality of these values:
3
cbo.last_precallback_id_
Which is: 2
```
Flaky test failure history:
https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/602/
https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/597/
https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/547/
https://build.ros2.org/job/Rpr__rclcpp__ubuntu_jammy_amd64/530/
Let me explain why the flaky test happened.
If https://github.com/ros2/rclcpp/blob/432bf21f0261bab209b37ccfe6da550f02751a22/rclcpp/test/rclcpp/test_time_source.cpp#L406 is called and
the `ros_clock` is set with 4.000001000s at this moment,
While calling …
> to fix flaky test about TestTimeSource.callbacks

- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/src/rclcpp/publisher_base.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
This PR avoids a runtime_error exception when trying to publish a `LoanedMessage` on a publisher that has intra-process enabled.
The changes make `can_loan_messages()` return false in that case, which in turn makes `borrow_loaned_message()` allocate a standard message.
> Allow publishing borrowed messages with intra-process enabled

- rclcpp/include/rclcpp/any_service_callback.hpp
- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/include/rclcpp/timer.hpp
Part of https://github.com/ros2/ros2_tracing/issues/34
Requires https://github.com/ros2/ros2_tracing/pull/43
Requires https://github.com/ros2/ros2_tracing/pull/46 to help avoid memory allocations when the tracepoint isn't enabled.
Signed-off-by: Christophe Bedard <christophe.bedard@apex.ai>
> Fix memory leak in tracetools::get_symbol()

- rclcpp_action/include/rclcpp_action/types.hpp
- rclcpp_action/src/types.cpp
- rclcpp_action/test/test_types.cpp
Changes the string representation of `rclcpp_action::GoalUUID`s to match the canonical format described in [RFC 4122](https://www.rfc-editor.org/rfc/rfc4122.html#section-3). (The current representation doesn't contain hyphens and omits the leading zero in the hex of a byte.)
> Fix the GoalUUID to_string representation

- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
Self explanatory, directly lifted from the normal node to lifecycle
> add get_fully_qualified_name to rclcpp_lifecycle

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
Fix clang warning: `bugprone-use-after-move`
https://clang.llvm.org/extra/clang-tidy/checks/bugprone/use-after-move.html
The fix is explicitly break from a for loop after the final message has been delivered.
Even if it we know we will exit the for loop,since we check
https://github.com/ros2/rclcpp/blob/399f4df7396d67b42ccaea651bbd87d66b0d62b3/rclcpp/include/rclcpp/experimental/intra_process_manager.hpp#L454
this is not enough for clang-tidy and it complains.
> Fix clang warning: bugprone-use-after-move

- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
I believe this should avoid the warning we are seeing on Windows of "inconsistent dll linkage".  This looks like it was introduced by #2115.  FYI @mjcarroll @SteveMacenski @fujitatomoya 
Warning message for reference: https://ci.ros2.org/view/nightly/job/nightly_win_rel/2610/msbuild/
> Use the correct macro for LifecycleNode::get_fully_qualified_name

- rclcpp/CMakeLists.txt
- rclcpp_action/CMakeLists.txt
- rclcpp_components/CMakeLists.txt
- rclcpp_lifecycle/CMakeLists.txt
The main reason to do this is so that we can compile rclcpp with the clang static analyzer.  As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version.  So set this as well.
> Update all rclcpp packages to C++17.

- rclcpp/include/rclcpp/strategies/allocator_memory_strategy.hpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
Address #2012
This patch may not be the best fix.   
But I hope to find the best fix by discussing this patch.
> Avoid losing waitable handles while using MultiThreadedExecutor

- rclcpp/test/rclcpp/test_function_traits.cpp
- rclcpp/test/rclcpp/test_loaned_message.cpp
- rclcpp/test/rclcpp/test_serialized_message.cpp
- rclcpp_lifecycle/test/test_lifecycle_publisher.cpp
This does 2 separate things:
* Adds (void)unused_variable things where needed.
* Stops doing some checks on moved-from items in tests.
With this in place, most of the remaining clang static analysis warnings are gone.
> Fixes to silence some clang warnings.

- rclcpp/src/rclcpp/context.cpp
part of https://github.com/ros2/rcl/issues/1036, but independent bug fix.
> use allocator via init_options argument.

- rclcpp_action/src/client.cpp
address https://github.com/ros2/rclcpp/issues/2130
> extract the result response before the callback is issued.

- rclcpp/include/rclcpp/event_handler.hpp
- rclcpp/src/rclcpp/publisher_base.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_qos_event.cpp
> Implement matched event

- rclcpp/include/rclcpp/logger.hpp
- rclcpp/src/rclcpp/logger.cpp
- rclcpp/test/rclcpp/test_logger.cpp
@clalancette @iuhilnehc-ynos could you do review when you have time?
> add Logger::get_effective_level().

- rclcpp/src/rclcpp/executor.cpp
std::function will allocate on every call of take_and_do_error_handling (at least with libstdc++ as in this implementation std::function's small buffer can only fit two pointers but most of the time, the lambdas will contain 3 pointers). This impose multiple heap allocations (and deallocations) on every callback.
This comes with the cost of increased binary size. But I suppose it's worth it as this change also enables better/easier inling and avoids indirect function calls through the std::function machinery.
> Fix unnecessary allocations in executor.cpp

- rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
If the intraprocess buffer still has data after taking, re-trigger the guard condition to ensure that the executor will continue to service it, even if incoming publications stop.
I found this bug when working on #2142.  There is a situation where if an intraprocess publisher sends all of it's messages before the subscription starts servicing it, then the executor will fail to service the entire queue.
Note that in the current `rclcpp` implementation, this really only impacts the `StaticSingleThreadedExecutor`, as the `SingleThreadedExecutor` and `MultiThreadedExector` both automatically trigger the waitset at the end of an executable cycle.  I discovered this because the rclcpp::Waitset based executor also does not recompute work.  I added the test to run against all executors to prevent …
> Trigger the intraprocess guard condition with data

- rclcpp/include/rclcpp/node_interfaces/node_graph_interface.hpp
- rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
Part of ros2/ros2#1159
From rep-2011 work, expose the new RMW endpoint info's type hash to the C++ endpoint struct.
> Add type_hash to cpp TopicEndpointInfo

- rclcpp/include/rclcpp/generic_subscription.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
Follow-up to: https://github.com/ros2/rclcpp/pull/2165
From further discussions, it was found that the `SubscriptionType` enum to change the behavior of the subscription was better thought of as a way to configure the "category" of message that is being delivered by a subscription (i.e. what is being passed in the subscription's handle function.)
Under that view, it is also possible to collapse the two dynamic message related enum options into one (and have the behavior change in the implementation of the take function.)
> Implement deliver message kind

- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_publisher.hpp
- rclcpp_lifecycle/test/test_lifecycle_publisher.cpp
Right now LifecyclePublisher doesn't support publishing `LoanedMessage`s. 
Override publish for loaned message, implementation is the same as in other overloads, check if publisher is activated and if so, pass message to base publisher
> Support publishing loaned messages in LifecyclePublisher

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/callback_group.hpp
- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/executors/executor_entities_collection.hpp
- rclcpp/include/rclcpp/executors/executor_entities_collector.hpp
- rclcpp/include/rclcpp/executors/executor_notify_waitable.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base.hpp
- rclcpp/include/rclcpp/node_interfaces/node_base_interface.hpp
- rclcpp/src/rclcpp/callback_group.cpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/executor_entities_collection.cpp
- rclcpp/src/rclcpp/executors/executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/executor_notify_waitable.cpp
- rclcpp/src/rclcpp/executors/static_executor_entities_collector.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
- rclcpp/src/rclcpp/node_interfaces/node_services.cpp
- rclcpp/src/rclcpp/node_interfaces/node_timers.cpp
- rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
- rclcpp/src/rclcpp/node_interfaces/node_waitables.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_entities_collector.cpp
- rclcpp/test/rclcpp/executors/test_executor_notify_waitable.cpp
Broken off of #2142 so that it can be used as a base for #2140.
This introduces a few main structures:
* ExecutorNotifyWaitable - an object used to collect node and callback group guard conditions from things associated with an executor.
* ExecutorEntitiesCollector - an object to collect entities from executor-associated nodes and callback groups
* ExecutorEntitiesCollection - a collection of entities that are associated with an executor via callback groups and nodes.
CC: @alsora @mauropasse
> Create common structures for executors to use

- rclcpp/include/rclcpp/subscription_base.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
When adding the stubs (with changes to subscription base), we had changed the names of one of the new enums, but I didn't change the name for the getter method...
Since it's new, and I'm treating this as a typo. Can we fix it?
@wjwwood @clalancette
> Fix delivered message kind typo

- rclcpp/test/rclcpp/test_rosout_subscription.cpp
In particular, you should never have a "bare" string in a printf-like call; that could potentially access uninitialized memory. Instead, make sure to format the string with %s.
> Fix a format-security warning when building with clang

- rclcpp/include/rclcpp/experimental/executors/events_executor/events_executor.hpp
- rclcpp/src/rclcpp/experimental/executors/events_executor/events_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
Add mutex to protect events_executor current entity collection and add unit-test.
The mutex is needed because the collection is essentially a list where `refresh_current_collection_from_callback_groups` can add/remove elements and `retrieve_entity` can read/remove elements.
Added a unit-test that without this PR was failing ~75% of the times and now succeeds.
> add mutex to protect events_executor current entity collection

- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/include/rclcpp/client.hpp
Please see https://github.com/ament/ament_lint/blob/271f9bd8e8504309707101850be16caae6471d02/ament_cpplint/ament_cpplint/cpplint.py#L515,
and https://github.com/ros2/rclcpp/blob/72c05ecee023b73f8bd687349c879d1d86df9f9e/rclcpp/include/rclcpp/any_service_callback.hpp#L18 has no `NO_LINT`.
> remove nolint since ament_cpplint updated for the c++17 header

- rclcpp/include/rclcpp/any_service_callback.hpp
- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/include/rclcpp/experimental/buffers/intra_process_buffer.hpp
- rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_buffer.hpp
- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/include/rclcpp/service.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/include/rclcpp/timer.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/node_interfaces/node_timers.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
Part of https://github.com/ros2/ros2_tracing/issues/18
Requires https://github.com/ros2/ros2_tracing/pull/56
> Use TRACETOOLS_ prefix for tracepoint-related macros

- rclcpp/test/rclcpp/executors/test_executors.cpp
This test has had recent flakiness in CI as discussed here: 
https://github.com/ros2/rclcpp/pull/2187#issuecomment-1560543114
It also seems to have a related issue in the rclcpp::Waitset implementation: https://github.com/ros2/rclcpp/pull/2142
I spent quite a bit of time trying to determine what is causing the test to flake, without much success.  I additionally couldn't conclude if it is an issue with the _test implementation_ or if it is something in our implementation.
After discussion with @clalancette and @alsora, I think that the best way forward for now is to remove this test, and rethink our approach for what we are testing here.
Track the re-addition of this test (or a rewrite): https://github.com/ros2/rclcpp/issues/2207
> Remove flaky stressAddRemoveNode test

- rclcpp/test/rclcpp/executors/test_events_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
- rclcpp/test/rclcpp/test_qos_event.cpp
Depends on https://github.com/ros2/rmw_connextdds/pull/76
> Enable callback group tests for connextdds

- rclcpp/include/rclcpp/experimental/subscription_intra_process.hpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
humble backport of https://github.com/ros2/rclcpp/pull/2164
If the intraprocess buffer still has data after taking, re-trigger the guard condition to ensure that the executor will continue to service it, even if incoming publications stop.
Signed-off-by: Michael Carroll <michael@openrobotics.org>
(cherry picked from commit 5f9695afb02f178ec739fa1591bb018a9f9b2be0)
> Trigger the intraprocess guard condition with data (#2164)

- rclcpp/test/rclcpp/executors/test_executors.cpp
address https://github.com/ros2/rclcpp/pull/2167#issuecomment-1597197552
> warning: comparison of integer expressions of different signedness

- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/include/rclcpp_lifecycle/state.hpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
- rclcpp_lifecycle/src/mutex_map.cpp
- rclcpp_lifecycle/src/mutex_map.hpp
- rclcpp_lifecycle/src/state.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
Implements #2172.
- Backports the changes to `LifecycleNodeInterfaceImpl` from #1756. It's OK to apply these changes to Humble because they do not modify the public ABI.
- Improve thread safety when using `State::state_handle_`:
- Add a new `MutexMap` class to associate a mutex with each instance of `State`.
- Add a private static `MutexMap` member to `State`. This type of change is allowed under [REP-0009](https://www.ros.org/reps/rep-0009.html).
- Add a unit test based on the example code from #1746 which fails without the above changes.
> Fix thread safety in LifecycleNode::get_current_state() for Humble

- rclcpp/include/rclcpp/any_subscription_callback.hpp
Since this is a common idiom, especially under this name, we should define the `always_false_v` template within a namespace to avoid conflict with other libraries and user code. This could either be `rclcpp::detail` if it's intended only for internal use or just `rclcpp` if it's intended as a public helper. In this PR, I've initially chosen the former.
> Move always_false_v to detail namespace

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/any_service_callback.hpp
- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_interfaces/node_interfaces.hpp
- rclcpp/include/rclcpp/node_interfaces/node_type_descriptions.hpp
- rclcpp/include/rclcpp/node_interfaces/node_type_descriptions_interface.hpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/node_interfaces/test_node_parameters.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_type_descriptions.cpp
- rclcpp/test/rclcpp/test_parameter_client.cpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
Part of ros2/ros2#1159
<s>Depends on ros2/rcl#1052</s>
Linked with https://github.com/ros2/system_tests/pull/520
Defines and implements new node interface `TypeDescriptionsInterface`, which provides the `~/get_type_description` service from ros2/rcl#1052.
Uses parameter `start_type_description_service` to start the service - defaulting to true!
This will not be a trivial backport to Iron - I propose moving forward with this as the "correct thing to build", then the backport can dump most of it into `node.cpp` for Iron.
> Add new node interface TypeDescriptionsInterface to provide GetTypeDescription service

- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
This ensures that they'll go out to /rosout and the disk.
This should fix #2221
> Switch lifecycle to use the RCLCPP macros.

- rclcpp/test/rclcpp/test_node.cpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
This was a whoopsie in #2224  - left out the implementation of this method in `LifecycleNode` so anybody who tried to compile against that method would get a linker error. Adds it in and a basic smoke test for both `Node` and `LifecycleNode` so that's caught. Already included in backport https://github.com/ros2/rclcpp/pull/2236
> Implement get_node_type_descriptions_interface for lifecyclenode and add test

- rclcpp_lifecycle/test/benchmark/benchmark_lifecycle_client.cpp
- rclcpp_lifecycle/test/benchmark/benchmark_lifecycle_node.cpp
Newer versions of google benchmark (1.8.2 in my case) warn that the compiler may optimize away the DoNotOptimize calls when using the constref version.  Get away from that here by explicitly *not* calling the constref version, casting where necessary.
> Stop using constref signature of benchmark DoNotOptimize.

- rclcpp/include/rclcpp/publisher.hpp
Just trigger the `rclcpp_publish` tracepoint for loaned message publications too.
> Instrument loaned message publication code path

- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp
Backport of https://github.com/ros2/rclcpp/pull/2233. Tested on Humble, works as expected.
> Backport: Switch lifecycle to use the RCLCPP macros

- rclcpp/src/rclcpp/time_source.cpp
minor bug fix that missed acquiring the mutex lock for `associated_clocks_`.
> associated clocks should be protected by mutex.

- rclcpp/src/rclcpp/time_source.cpp
Fixes #2253 
As mentioned in the attached issue, using a `vector` makes it possible for the same clock to be stored multiple times in a `TimeSource`, this PR changes the storage to be `unordered_set` so duplicates are automatically avoided at insertion and removal is constant in time.
I thought a bit about adding a regression test but it wasn't so immediate to me it would be a good idea, the test would have been adding the same clock twice, removing it once then making sure it is not updated anymore. I can add it if you folks think it's useful.
There is also no warning if a user adds a clock that was already added, but that can also be added if needed.
I'll open a matching PR in `rclpy` once this is approved
> Change TimeSource associated clocks storage to unordered_set

- rclcpp/include/rclcpp/exceptions/exceptions.hpp
- rclcpp/src/rclcpp/node_interfaces/node_services.cpp
- rclcpp/src/rclcpp/node_interfaces/node_timers.cpp
- rclcpp/src/rclcpp/node_interfaces/node_topics.cpp
- rclcpp/src/rclcpp/node_interfaces/node_waitables.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_services.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_timers.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_waitables.cpp
Follow up of issue #2247 which is meant to address a range of TODOs specifically for `std::runtime_error` with the description of
```
throw std::runtime_error("Cannot create something, group not in node.");
```
All of the errors follow that same format, so we can create a general class in `exceptions.hpp` that just take a `const std::string &` of whatever `something` is and runs the error in a much cleaner format.
> Adding Missing Group Exceptions

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/executors.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors.cpp
- rclcpp/test/rclcpp/test_executor.cpp
Adds spin_all to `executors.hpp` to be accessible as such: 
```
auto node = std::make_shared<MyNode>();
rclcpp::spin_all(node, 1000ms);
```
Should I also add `spin_once`?
> Add spin_all shortcut

- rclcpp/include/rclcpp/exceptions/exceptions.hpp
- rclcpp/include/rclcpp/parameter_value.hpp
- rclcpp/src/rclcpp/parameter_value.cpp
Fixing a previous TODO to add a custom error/exception handler, similar to PR #2256, relating to issue #2247. This is a really basic error handler to just specifies to the user, if there was an unknown type that was passed.
> Adding Custom Unknown Type Error

- rclcpp/include/rclcpp/service.hpp
replace of https://github.com/ros2/rclcpp/pull/2215
> Do not crash Executor when send_response fails due to client failure.

- rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
address part of https://github.com/ros2/rclcpp/issues/2242
> doc fix: call `canceled` only after goal state is in canceling.

- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
1. Use constref for the loop variable.
2. Do more work outside of the loop.
3. Skip doing unnecessary work where we can inside the loop.
With this in place, I measured about a 7% performance improvement over the previous implementation.
> Revamp list_parameters to be more efficient and easier to read.

- rclcpp/CMakeLists.txt
- rclcpp/package.xml
It is depended on by rclcpp/src/rclcpp/logger.cpp, but the dependency was not explicitly declared (it was being inherited from rcl, I believe).  Fix that here.
> Add rcl_logging_interface as an explicit dependency.

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/rate.hpp
- rclcpp/src/rclcpp/rate.cpp
- rclcpp/test/rclcpp/test_rate.cpp
This is the continue of [#1373] [discussion](https://github.com/ros2/rclcpp/pull/1373#discussion_r1118830044) and related to the https://github.com/ros-planning/navigation2/issues/3325 issue in Nav2
The initial idea is to make `rclcpp::Rate` to work with ROS-time (currently it works only with system and steady times).
What was made:
* Add `rclcpp::Clock` pointer to the `rclcpp::Rate` constructor to allow developer to specify the clock to work with (by-default it is still `RCL_SYSTEM_TIME` if no clock is specified)
* Add `rclcpp::ROSRate` rate class, respective to ROS-time
Current implementation points:
* Getting rid of templates' structure allows developer to select the clock to work with in dynamics
* Renamed `rclcpp::GenericRate` -> to `rclcpp::Rate` and gave it the default clock to …
> Make Rate to select the clock to work with

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
Fixes c++20 construct function not available & volatile deprecation warning.
This will still compile in C++17.
> C++20 compatibility fixes

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
- rclcpp/test/rclcpp/test_publisher_with_type_adapter.cpp
to fix https://github.com/ros2/rclcpp/issues/2291
Based on the document of [TypeAdapter](https://github.com/ros2/rclcpp/blob/bc435776a257fcf76c5b0124bec26f6824342e34/rclcpp/include/rclcpp/type_adapter.hpp#L23-L37), I'd like to update from `TypeAdapter<MessageT>` to `TypeAdapter<MessageT, ROSMessageType>`, rather than adding another if-block to deal with `TypeAdapter<MessageT, ROSMessageType>` as there are no cases in the existing test that could be failed.
BTW: I think https://github.com/ros2/rclcpp/blob/bc435776a257fcf76c5b0124bec26f6824342e34/rclcpp/include/rclcpp/experimental/intra_process_manager.hpp#L397-L416 can be updated as well because of some unuseful code. (Maybe update it in the following PR.)
I'd like to hear your opinions.
> Topic correct typeadapter deduction

- rclcpp/include/rclcpp/experimental/timers_manager.hpp
- rclcpp/src/rclcpp/experimental/timers_manager.cpp
- rclcpp/test/rclcpp/test_timers_manager.cpp
The timers_manager tests were relying too heavily on specific timings; this caused them to be flaky on the buildfarm, particularly on Windows.
Here, we increase the timeouts, and remove one test which just relies too heavily on specific timeouts.  This should make this test much less flaky on the buildfarm.
@alsora @mjcarroll FYI
> Cleanup flaky timers_manager tests.

- rclcpp_action/include/rclcpp_action/client_goal_handle.hpp
- rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp
- rclcpp_action/test/test_client.cpp
This prevents deadlocks in cases, were e.g. get_status() would be called on the handle in a callback of the handle.
Fixes https://github.com/ros2/rclcpp/issues/2243
> fix(ClientGoalHandle): Made mutex recursive to prevent deadlocks

- rclcpp/README.md
- rclcpp_action/README.md
- rclcpp_components/README.md
- rclcpp_lifecycle/README.md
The root README was updated to point to index.ros.org/p/rclcpp (#1620, #2071), but the individual package READMEs, which are displayed by index.ros.org, still link to docs.ros2.org.
> Update API docs links in package READMEs

- rclcpp/include/rclcpp/rate.hpp
- rclcpp/src/rclcpp/rate.cpp
In a recent commit (bc435776a257fcf76c5b0124bec26f6824342e34), we reworked how the Rate class worked so it could be used with ROS time as well.  Unfortunately, we also accidentally broke the API of it by changing the return type of Rate::period to a Duration instead of a
std::chrono::nanoseconds .  Put this back to a std::chrono::nanoseconds; if we want to change it to a Duration, we'll have to add a new method and deprecate this one.
@AlexeyMerzlyakov FYI
> Fix the return type of Rate::period.

- rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_parameters.cpp
Related to : https://github.com/ros2/rclpy/pull/1124/files#r1314262489
> fix the depth to relative in list_parameters

- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
address https://github.com/ros2/rclcpp/issues/2147
> Decouple rosout publisher init from node init.

- rclcpp/include/rclcpp/node.hpp
- rclcpp/test/rclcpp/node_interfaces/test_node_parameters.cpp
This is meant to solve the documentation part of issue #721 since the testing part had already been seemingly completed.
> Documentation for list_parameters 

- rclcpp/test/rclcpp/CMakeLists.txt
So this is a PR in response to some TODOs:
> TODO(brawner) remove when destroying Node for Connext is resolved
This pull requests just removes these older, stale tests which don't have a purpose. The discussion for this takes place in issue #1250, the pull request that these special tests were added was PR #1253. Then, it seems that [this pull request](https://github.com/ros2/rmw_connext/pull/473) in the old rmw_connext repository was responsible for fixing why these tests were added. 
I figured that since that pull request solved the issue, the TODO requirement was met and there is no reason to have special cases on the tests. I assume we should still keep the tests because they're generalized and still provide value.
> Removing Old Connext Tests

- rclcpp/src/rclcpp/signal_handler.cpp
This was flagged by msan as a problem. 
There's a description of why this is a potential problem here: https://google.github.io/styleguide/cppguide.html#Static_and_Global_Variables
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19557)](http://ci.ros2.org/job/ci_linux/19557/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14070)](http://ci.ros2.org/job/ci_linux-aarch64/14070/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20278)](http://ci.ros2.org/job/ci_windows/20278/)
> Update SignalHandler get_global_signal_handler to avoid complex types in static memory

- rclcpp/src/rclcpp/time_source.cpp
We need this because it is possible for one thread to be handling the on_parameter_event callback while another one is detaching the node.  This lock will protect that from happening.
> Add locking to protect the TimeSource::NodeState::node_base_

- rclcpp/test/rclcpp/test_serialized_message.cpp
address https://github.com/ros2/rcutils/issues/431
> remove invalid sized allocation test for SerializedMessage.

- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_interfaces/node_graph.hpp
- rclcpp/include/rclcpp/node_interfaces/node_graph_interface.hpp
- rclcpp/include/rclcpp/rclcpp.hpp
- rclcpp/src/rclcpp/node.cpp
- rclcpp/src/rclcpp/node_interfaces/node_graph.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_graph.cpp
- rclcpp/test/rclcpp/test_node.cpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
This PR is for clients, service counts using it's name.
Related to https://github.com/ros2/ros2cli/pull/771
Signed-off-by: leeminju531 <dlalswn531@naver.com>
> add clients & services count

- rclcpp_lifecycle/include/rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp
The comment in the commit explains this clearly, but on Windows ERROR is a macro.  The reuse of it, even as an enum, causes compilation errors on downstream users.  Push the macro and undefine it so downstream consumers can freely include it.
I found this while trying to get https://github.com/ros/bond_core/pull/83 integrated.  With this in place, I was able to successfully compile.
> Fix rclcpp_lifecycle inclusion on Windows.

- rclcpp/include/rclcpp/rate.hpp
- rclcpp/src/rclcpp/rate.cpp
- rclcpp/test/rclcpp/test_rate.cpp
This is the part of #2307 discussion to completely remove `ROSRate` inherited class, as we can not utilize its `clock` well without the subscription to `/clock` topic (which is being done by `rclcpp::TimeSource` attached to the node)
> Remove useless ROSRate class

- rclcpp/include/rclcpp/logger.hpp
- rclcpp/src/rclcpp/context.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_intra_process_manager.cpp
1. Remove the default Logger copy constructor without copy assignment (rule of three -> rule of zero).
2. Remove an unnecessary capture in a lambda.
3. Mark a variable unused.
4. Mark a method as override.
> Fixes pointed out by the clang analyzer.

- rclcpp/src/rclcpp/context.cpp
- rclcpp/src/rclcpp/rate.cpp
- rclcpp/test/rclcpp/test_rate.cpp
https://ci.ros2.org/view/nightly/job/nightly_win_rep/3129/testReport/projectroot.test/rclcpp/test_rate/
> C:\ci\ws\src\ros2\rclcpp\rclcpp\test\rclcpp\test_rate.cpp(61): error: Value of: r.sleep()
we did not really change the test here.
https://github.com/ros2/rclcpp/blob/rolling/rclcpp/test/rclcpp/test_rate.cpp#L61
originally if it did not miss the cycle, no matter it actually sleeps or not, it will return true.
i think this is intention, since time goes by during calling `sleep` method. if that is racy, it actually does not sleep in here.
> unknown file: error: C++ exception with description "context is already initialized" thrown in the test body.
i think this is just a secondary problem because `ASSERT_TRUE(r.sleep());` will not get to `rclcpp::shutdown();`.
i believe we should use …
> address rate related flaky tests.

- rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_type_descriptions.cpp
In https://github.com/ros2/rcl/pull/1112, the API is updated to populate the service structure, rather than `init`, `get`, and `fini`.  This updates rclcpp to use the new API pattern.
> Adjust rclcpp usage of get_type_description_service

- rclcpp/include/rclcpp/node_options.hpp
Add missing `enable_rosout = true` to node options default values comments
> Add missing 'enable_rosout' comments

- rclcpp/include/rclcpp/create_subscription.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/include/rclcpp/subscription_factory.hpp
- rclcpp/include/rclcpp/topic_statistics/subscription_topic_statistics.hpp
- rclcpp/test/rclcpp/topic_statistics/test_subscription_topic_statistics.cpp
- Depends from https://github.com/ros-tooling/libstatistics_collector/issues/168
- Follow up on the https://github.com/ros-tooling/libstatistics_collector/issues/168 and prerequisite for the https://github.com/ros2/rclcpp/pull/2274
- Untemlpatize the `rclcpp::topic_statistics::SubscriptionTopicStatistics` class. Now we will be using `message_info` instead of typed deserialized messages in the `handle_message` callbacks. 
- Perhaps it will also reduce total build time and final binary size since there will be less code generated per each pub/sub.
action-ros-ci-repos-supplemental: https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos
> Use message_info in SubscriptionTopicStatistics instead of typed message

- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
They are currently unsafe to use; see the comment in the commit for more information.
This was originally brought up by https://github.com/ros2/rmw_cyclonedds/issues/469 , but we also had another report of it from Nav2 (parts reproduced here for context):
From @SteveMacenski 
```
*    It looks like Fast-DDS returns the same shared pointer memory for multiple subscriber callbacks in a row
*    We take the shared_ptr message from the callback and store it for use. So later on, the community member is identifying that Fast-DDS sets the same underlying memory in msg to the new message, even though we have stored the shared pointer in our code and just reusing it, wiping away our program's state
```
From @wjwwood:
```
This is probably a bug in rclcpp: …
```
> Disable the loaned messages inside the executor.

- rclcpp/src/rclcpp/node_interfaces/node_type_descriptions.cpp
In the type description service construction, we were previously passing the shared_ptr to the rcl_service_t with the assumption that rclcpp::Service would do the clean up.  This was an incorrect assumption, and so I have added a custom deleter to fini the service and delete when the shared_ptr is cleaned up.
Fixes leak introduced in #2344
> Add a custom deleter when constructing rcl_service_t

- rclcpp/include/rclcpp/subscription.hpp
This pull request was created to solve a [TODO](https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/subscription.hpp#L328) that was added in pull request #1557, but there's no discussion on the topic. As per the title, the point was to allow the user to use topic statistics when handling a serialized message. I tried to follow the way the other two functions `handle_message` and `handle_loaned_message` handled their topic statistics, but assumed that one couldn't pass a serialized message through the statistics, so I set up a basic serialization process. We only need to make one copy of the message that we create and since `ROSMessageType` is a string in disguise, we can still get all the data from it. Additionally, we still just dispatch the message, before we get an …
> Serialized Messages with Topic Statistics

- rclcpp/include/rclcpp/time.hpp
- rclcpp/src/rclcpp/time.cpp
- rclcpp/test/rclcpp/test_time.cpp
address https://github.com/ros2/rclcpp/issues/2348
> rclcpp::Time::max() clock type support.

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/test/rclcpp/test_publisher.cpp
gcc 13.1.1 complains that these uses inhibit copy elision.
> Updates to not use std::move in some places.

- rclcpp/src/rclcpp/signal_handler.hpp
fix spelling mistake when I was learnig this code 😸
> fix (signal_handler.hpp): spelling

- rclcpp_components/src/component_manager.cpp
fixes: https://github.com/ros2/rclcpp/issues/2362
> fix(rclcpp_components): increase the service queue sizes in component_container

- rclcpp/include/rclcpp/event_handler.hpp
- rclcpp/src/rclcpp/event_handler.cpp
Both the `EventHandler` and its associated pubs/subs share the same underlying rmw event listener:
`EventHandler --> rmw_event_listener <-- Pub/Sub` 
When a pub/sub is destroyed, that listener is destroyed.
There is a data race when the `~EventHandlerBase` calls  `clear_on_ready_callback()`, since it wants to access the listener that could have already been destroyed, thus causing a segfault.
On other hand, the derived `EventHandler` _does_ store a shared_ptr of its associated pub/sub (`parent_handle_`), thus clearing the callbacks on `~EventHandler` instead of `~EventHandlerBase` avoids the race, since the pub/sub are still valid on the `parent_handle_` so the listener is also still valid.
I managed to reproduce the issue on Galactic/Humble/Iron using the example provided here: …
> Fix data race in ~EventHandlerBase

- rclcpp_components/src/node_main.cpp.in
Currently, EventsExecutor is in different namespace from other executors, so I modify node_main.cpp.in template to support EventsExecutor.
> feat(rclcpp_components): support events executor in node main template

- rclcpp_lifecycle/CMakeLists.txt
Addressing occasional timeouts caused by cppcheck on `nightly_win_deb`,
See: https://github.com/osrf/buildfarm-tools-private/issues/20#issuecomment-1857230574 and https://github.com/ros2/rclcpp/pull/2392
CI job to test:
[![Build Status](https://ci.ros2.org/job/ci_windows/20709/badge/icon)](https://ci.ros2.org/job/ci_windows/20709/)
> Increase timeout for rclcpp_lifecycle to 360

- rclcpp/include/rclcpp/callback_group.hpp
- rclcpp/include/rclcpp/guard_condition.hpp
- rclcpp/src/rclcpp/callback_group.cpp
- rclcpp/src/rclcpp/guard_condition.cpp
- rclcpp/src/rclcpp/node_interfaces/node_base.cpp
- rclcpp/test/rclcpp/test_context.cpp
- rclcpp/test/rclcpp/test_guard_condition.cpp
Stop storing the context in the guard condition.
This was creating a circular reference between GuardCondition
and Context, so that Context would never be cleaned up.
Since we never really need the GuardCondition to know
about its own Context, remove that part of the circular
reference.
While we are in here, we also change the get_context()
lambda to a straight weak_ptr; there is no reason for the
indirection since the context for the guard condition
cannot change at runtime.
We also remove the deprecated version of the
get_notify_guard_condition().  That's because there is
no way to properly implement it in the new scheme, and
it seems to be unused outside of rclcpp.
Finally, we add in a test that guarantees the use_count
is what we expect when inside and leaving a scope, ensuring
that …
> Stop storing the context in the guard condition.

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/detail/resolve_intra_process_buffer_type.hpp
- rclcpp/include/rclcpp/experimental/buffers/buffer_implementation_base.hpp
- rclcpp/include/rclcpp/experimental/buffers/intra_process_buffer.hpp
- rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp
- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
- rclcpp/include/rclcpp/experimental/subscription_intra_process_base.hpp
- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/include/rclcpp/publisher_base.hpp
- rclcpp/include/rclcpp/publisher_options.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/src/rclcpp/detail/resolve_intra_process_buffer_type.cpp
- rclcpp/src/rclcpp/intra_process_manager.cpp
- rclcpp/src/rclcpp/publisher_base.cpp
- rclcpp/src/rclcpp/subscription_intra_process_base.cpp
- rclcpp/test/rclcpp/test_intra_process_buffer.cpp
- rclcpp/test/rclcpp/test_intra_process_manager.cpp
- rclcpp/test/rclcpp/test_publisher.cpp
- rclcpp/test/rclcpp/test_ring_buffer_implementation.cpp
- rclcpp/test/rclcpp/test_subscription.cpp
Signed-off-by: Jeffery Hsu [jefferyyjhsu@gmail.com](mailto:jefferyyjhsu@gmail.com)
This PR adds transient local durability support to publishers and subscriptions when intra-process communication is used.
An intra-process buffer already existed on the subscription side. The PR adds the same style buffer to the publisher side and other supporting functions allowing intra process manager to publish saved messages for late joining subscriptions.
> Add transient local durability support to publisher and subscriptions when using intra-process communication

- rclcpp/CMakeLists.txt
This is necessary, most likely because of #2303 .  @alsora @jefferyyjhsu FYI
We've seen test failures from this already, see https://ci.ros2.org/job/ci_windows/20815/
> Increase the cppcheck timeout to 600 seconds.

- rclcpp/include/rclcpp/experimental/buffers/ring_buffer_implementation.hpp
This gets rid of a warning when building under clang.
This fixes the warning like we see in https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1776/clang/new/source.1b6aeccf-f9e7-4428-a820-7d012d9fdb12/#70 .
This is followup from #2303 .  @jefferyyjhsu @alsora FYI.
> Make sure to mark RingBuffer methods as 'override'.

- rclcpp/include/rclcpp/experimental/timers_manager.hpp
- rclcpp/src/rclcpp/experimental/executors/events_executor/events_executor.cpp
- rclcpp/src/rclcpp/experimental/timers_manager.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_timers_manager.cpp
It appears that with the experimental events executor, some usages of the rclcpp API cause broken behavior. Specifically, if multiple timers are configured in a node, and during runtime one of the timers is cancelled via the `TimerBase::cancel` method, this will result in all other timers failing to execute.
A minimal working example of the bug is found here --
[example_package.tar.gz](https://github.com/ros2/rclcpp/files/13494070/example_package.tar.gz)
To reproduce, build the package using `colcon build`, then run `USE_EVENTS_EXECUTOR=1 ros2 run example_package timer_node`. It is observable that both timers get cancelled after the first timer cancels itself:
```
root@753c2035d766:/app/src# USE_EVENTS_EXECUTOR=1 ros2 run example_package timer_node
[INFO] [1701211973.238745755] …
```
> [events executor] - Fix Behavior with Timer Cancel

- rclcpp_components/CMakeLists.txt
- rclcpp_components/src/node_main.cpp.in
> crash on no class found

- rclcpp/QUALITY_DECLARATION.md
- rclcpp_action/QUALITY_DECLARATION.md
- rclcpp_components/QUALITY_DECLARATION.md
- rclcpp_lifecycle/QUALITY_DECLARATION.md
Change 'ROS2' to 'ROS 2' and update links to other quality declarations.
> Update quality declaration documents

- rclcpp/CMakeLists.txt
The comment in the commit explains the reasoning behind it.
This must be merged before https://github.com/ros2/ros2/pull/1524 ; see that pull request for more information about this change.
> Set hints to find the python version we actually want.

- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/test/rclcpp/test_any_subscription_callback.cpp
These have been deprecated since April 2021, so it is safe to remove them now.
> Remove the set_deprecated signatures in any_subscription_callback.

- rclcpp_components/cmake/rclcpp_components_register_node.cmake
> [rclcpp_components] Add missing parameter to `rclcpp_components_register_node` API documentation

- rclcpp_action/include/rclcpp_action/types.hpp
- rclcpp_action/test/test_types.cpp
This PR does:
- Add unit tests to detect collisions on the `rclcpp_action::GoalUUID` hashing algorithm.
- Update the hashing algorithm to use the [FNV-1a algorithm](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function).
The unit tests were failing right away with the previous hashing algorithm, which produced the same output for different `GoalUUID`s, quite often.
> Modify rclcpp_action::GoalUUID hashing algorithm

- rclcpp/test/rclcpp/executors/executor_types.hpp
- rclcpp/test/rclcpp/executors/test_executors_timer_cancel_behavior.cpp
replacement for https://github.com/ros2/rclcpp/pull/2453
this depends on https://github.com/ros2/rclcpp/pull/2456
> enable simulation clock for timer canceling test.

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
After working on https://github.com/ros2/rclcpp/pull/2142 I came to realize that the parameterized `spinSome` (always should have been `spin_some` to match our style and the name of the method being tested) tests were testing some false assumptions and in general were very fragile.
I reworked the nominal test to check that it does not block when there's no work, that it works with one ready item, and that it also executes multiple ready items when they are available.
```
$ ./build/rclcpp/test/rclcpp/test_executors --gtest_filter=*spin_some
Running main() from /home/william/ros2_ws/install/gtest_vendor/src/gtest_vendor/src/gtest_main.cc
Note: Google Test filter = *spin_some
[==========] Running 4 tests from 4 test suites.
[----------] Global test environment set-up.
[----------] 1 test …
```
> refactor and improve the parameterized spin_some tests for executors

- rclcpp/test/rclcpp/executors/test_executors.cpp
This PR partially fixes https://github.com/ros2/rclcpp/issues/2462
The EventsExecutor and the StaticSingleThreadedExecutor were failing a unit-test.
This PR fixes the test for the EventsExecutor.
The waitables were not triggered, so the events executor was not executing them.
This poses the question... Why do the other executors "execute" a waitable that was not triggered?
EDIT: the other executors worked because there was a bug in the `is_ready` method of the `TestWaitable` class. This was returning "true" regardless of whether the waitable was triggered.
Fixed it as a separate commit [0e6c78d](https://github.com/ros2/rclcpp/pull/2465/commits/0e6c78dba83e817d26d2cd8649d46a2513b5cc92)
FYI @wjwwood
> fix spin_some_max_duration unit-test for events-executor

- rclcpp_action/src/server.cpp
part of https://github.com/ros2/ros2/issues/1462
> Do not generate the exception when action service response timeout.

- rclcpp/test/rclcpp/test_timers_manager.cpp
fix flakiness in TestTimersManager check_one_timer_cancel_doesnt_affect_other_timers
the previous version of the test was relying on the assumption that a timer with 1ms period gets called at least 6 times if the main thread waits 15ms. this is true most of the times, but it's not guaranteed, especially when running the test on windows CI servers. the new version of the test makes no assumptions on how much time it takes for the timers manager to invoke the timers, but rather focuses on ensuring that they are called the right amount of times, which is what's important for the purpose of the test
we need to ensure that if a timers manager has N timers and 1 gets cancelled, all the other ones keep getting invoked.
> fix flakiness in TestTimersManager unit-test

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
Backport of #2116 to humble.
Without this, I would need to add `// NOLINT(clang-analyzer-cplusplus.Move)` to every my `publish()` call in humble.
> [humble] Fix clang warning: bugprone-use-after-move (#2116)

- rclcpp/include/rclcpp/generic_subscription.hpp
- rclcpp/src/rclcpp/generic_publisher.cpp
- rclcpp/src/rclcpp/generic_subscription.cpp
- rclcpp/src/rclcpp/subscription_base.cpp
Hi, I'm  developed member of [CARET](https://github.com/tier4/caret) for real-time analysis using [ros2tracing](https://github.com/ros2/ros2_tracing). 
In communication through GenericPublisher/Subscription, message tracking was not possible due to a lack of trace data.
In this PR, added trace points to the GenericPublisher and GenericSubscription.
- GenericPublisher
I have added the following trace points.
- tracepoint : [rclcpp_publish](https://github.com/ros2/ros2_tracing/blob/327e8dfbf0cab3ab3472be409b5d184e4c1eacb9/tracetools/src/tracetools.c#L130-L136)
- GenericSubscription
[There was a recent PR that made `create_generic_subscription` go through AnySubscriptionCallback](https://github.com/ros2/rclcpp/pull/1928). This change caused …
> Add tracepoint for generic publisher/subscriber

- rclcpp/src/rclcpp/time_source.cpp
- rclcpp/test/rclcpp/executors/test_executors_timer_cancel_behavior.cpp
This fixed some issues reported in https://github.com/ros2/rcl/pull/1142
@clalancette, @mjcarroll , @fujitatomoya , @wjwwood
> Flaky timer test fix

- rclcpp/test/rclcpp/test_timers_manager.cpp
Related with this warning https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1846/gcc/new/folder.-1481343024/
> Removed test_timers_manager clang warning

- rclcpp/CMakeLists.txt
I can see a [timeout in rclcpp cppcheck](https://ci.ros2.org/view/nightly/job/nightly_win_deb/3052/consoleText) increasing it a little bit more. [nightly_win_deb build](https://ci.ros2.org/view/nightly/job/nightly_win_deb/3052/#showFailuresLink)
```
2:  - C:/ci/ws/install/Scripts/ament_cppcheck.exe --xunit-file C:/ci/ws/build/rclcpp/test_results/rclcpp/cppcheck.xunit.xml --include_dirs C:/ci/ws/src/ros2/rclcpp/rclcpp/include
2/124 Test   #2: cppcheck ...................................................***Timeout 600.10 sec
```
> Increase the cppcheck timeout to 1200 seconds

- rclcpp/include/rclcpp/experimental/intra_process_manager.hpp
this commit will fix the warning [-Wstringop-overflow=] #2461
> fix: init concatenated_vector with begin() & end()

- rclcpp_action/include/rclcpp_action/server.hpp
- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
- rclcpp_action/test/test_server.cpp
See: https://github.com/ros2/rclcpp/pull/2250
> Remake of "fix: Fixed race condition in action server between is_ready and take"

- rclcpp/test/rclcpp/test_publisher_with_type_adapter.cpp
When I added in the tests for large messages, I made a mistake and reserved space in the strings, but didn't actually expand it.  Thus, we were writing into uninitialized memory.  Fix this by just using the correct constructor for string, which will allocate and initialize the memory properly.
@ahcorde FYI
> Fix uninitialized memory in test

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/timer.hpp
- rclcpp/src/rclcpp/executor.cpp
Follow up to https://github.com/ros2/rclcpp/pull/2343
> fixup var names to snake case

- rclcpp/include/rclcpp/executor.hpp
- rclcpp/include/rclcpp/wait_result.hpp
- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/executor_entities_collection.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_executors_callback_group_behavior.cpp
See: https://github.com/ros2/rclcpp/pull/2494
Which I could not update.
> [wjwwood] Updated "Data race fixes"

- rclcpp_action/include/rclcpp_action/client.hpp
- rclcpp_action/include/rclcpp_action/client_goal_handle_impl.hpp
fixes https://github.com/ros2/rclcpp/issues/2265
Note, this commit fixes a bug, that makes the current version of the tutorial 
not work any more, as the code now acts according to its documentation.
> Callback after cancel

- rclcpp/include/rclcpp/time.hpp
- rclcpp/src/rclcpp/time.cpp
- rclcpp/test/rclcpp/test_time.cpp
rclcpp::Time currently allows a negative time when constructing with int64_t nanoseconds (but not with int32_t seconds even though both can possibly hold a negative value). For a more uniform interface and based off of https://github.com/ros2/rclcpp/issues/525 where time cannot be negative:
- Added the negative time check and throw from the `rclcpp::Time(int32_t seconds, uint32_t nanoseconds, ...)` constructor to the `rclcpp::Time(int64_t nanoseconds, ...)` constructor
- Added a test to check that it throws with negative time
- Removed the tests which allowed for negative time (the cases should already be covered by the other tests?)
Closes https://github.com/ros2/rclcpp/issues/2507.
> Check for negative time in rclcpp::Time(int64_t nanoseconds, ...) constructor

- rclcpp/src/rclcpp/executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
This is a follow up of https://github.com/ros2/rclcpp/pull/2509 which addresses https://github.com/ros2/rclcpp/issues/2508.
> Fixup Executor::spin_all() regression fix

- rclcpp/CMakeLists.txt
- rclcpp/include/rclcpp/executor_options.hpp
- rclcpp/src/rclcpp/executor_options.cpp
Follow up of https://github.com/ros2/rclcpp/pull/2505#issuecomment-2059392440, we need this to potentially add more functionality to Jazzy post release, as well it gives us more flexibility to fix bugs in the future.
We already have this for the `Executor`, so this class is the only one that needs adjustment:
https://github.com/ros2/rclcpp/blob/f7185dc129c40388e66813c96f2ac5dbb73ffe00/rclcpp/include/rclcpp/executor.hpp#L597
> add impl pointer for ExecutorOptions

- rclcpp_lifecycle/src/lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
address https://github.com/ros2/rclcpp/issues/2520
depends on https://github.com/ros2/rclcpp/pull/2527
> call shutdown in LifecycleNode dtor to avoid leaving the device in unknown state (2nd)

- rclcpp_lifecycle/src/lifecycle_node.cpp
https://github.com/ros2/rclcpp/pull/2528 generates the following error when the context is gracefully shutdown. (e.g deferred signal handler of rclcpp.)
```bash
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 run lifecycle lifecycle_talker
^C[INFO] [1717052032.575390927] [rclcpp]: signal_handler(signum=2)
[ERROR] [1717052032.577706294] [lc_talker]: Unable to start transition 5 from current state shuttingdown: Could not publish transition: publisher's context is invalid, at /root/ros2_ws/colcon_ws/src/ros2/rcl/rcl/src/rcl/publisher.c:423, at /root/ros2_ws/colcon_ws/src/ros2/rcl/rcl_lifecycle/src/rcl_lifecycle.c:368
[WARN] [1717052032.577764887] [rclcpp_lifecycle]: Shutdown error in destruction of LifecycleNode: final state(unconfigured)
```
this is because the shutdown in the dtor is called …
> LifecycleNode shutdown on dtor only with valid context.

- rclcpp/test/rclcpp/test_subscription_content_filter.cpp
This PR adds the proper test in `rclcpp` that checks for a successful creation of two content filter topics for the same topic name.
* Related PR https://github.com/ros2/rmw_fastrtps/pull/762
> Add test creating two content filter topics with the same topic name

- rclcpp/test/rclcpp/test_subscription_content_filter.cpp
Reverts ros2/rclcpp#2546
The original PR was targeting `master`, it should target `rolling`. I will cherry-pick the commit in to `rolling`
> Revert "Add test creating two content filter topics with the same topic name"

- rclcpp/test/rclcpp/test_subscription_content_filter.cpp
I wrongly merged this PR https://github.com/ros2/rclcpp/pull/2546 on `master`. This PR targets `rolling`
> Add test creating two content filter topics with the same topic name 

- rclcpp_lifecycle/src/lifecycle_node.cpp
cherry-pick https://github.com/ros2/rclcpp/commit/a3caf1780dfe47f65fc702af3e6e03b1e6af2d33
> lifecycle node dtor shutdown should be called only in primary state.

- rclcpp/include/rclcpp/clock.hpp
- rclcpp_action/include/rclcpp_action/create_server.hpp
* "greater then" -> "greater than"
* Use `///` instead of `//` for the function's one-line description
* Remove extra `]`
> Fix typo in function doc

- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/include/rclcpp/service.hpp
I assume these are copy-paste errors.
> Fix copy-paste errors in function docs

- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
- rclcpp/test/rclcpp/test_any_service_callback.cpp
- rclcpp/test/rclcpp/test_any_subscription_callback.cpp
- rclcpp/test/rclcpp/test_create_subscription.cpp
Unless I'm missing something, the C msgs are not needed in those tests.
> Remove unnecessary msg includes in tests

- rclcpp/src/rclcpp/experimental/executors/events_executor/events_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
This PR fixes a bug noticed by @wjwwood as part of his PR [here](https://github.com/ros2/rclcpp/pull/2537#discussion_r1610822524)
We don't need to add the notify waitable to the current entities collection list there, because it has already been added in the constructor.
The PR includes a unit-test that would detect bugs if the constructor insertion was removed.
> avoid adding notify waitable twice to events-executor collection

- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/multi_threaded_executor.cpp
- rclcpp/src/rclcpp/executors/single_threaded_executor.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_executor.cpp
This issue was found in ros2/rmw_fastrtps#761.  
In code of MoveIt, it used static executor. When the static executor is destructed (The executor is in a cancel state.), and it's time to free up the ownership of entity resources, Fast DDS resources have already been released.   
After spinning is cancelled, the Executor should release ownership of entities at once.
> Release ownership of entities after spinning cancelled

- rclcpp/test/rclcpp/executors/test_executors.cpp
> Fix backport issue bp/jazzy/pr-2556

- rclcpp_lifecycle/CMakeLists.txt
- rclcpp_lifecycle/test/test_lifecycle_node.cpp
- rclcpp_lifecycle/test/test_lifecycle_node_errors.cpp
The full explanation is in the comment, but basically since RHEL doesn't support mocking_utils::inject_on_return, we have to split out certain tests to make sure resources within a process don't collide.
> Fix the lifecycle tests on RHEL-9.

- rclcpp_components/include/rclcpp_components/component_manager.hpp
These methods were marked as deprecated in 2021 (https://github.com/ros2/rclcpp/pull/1716), it's time to let them go.
> remove deprecated APIs from component_manager.hpp

- rclcpp/include/rclcpp/callback_group.hpp
- rclcpp/include/rclcpp/client.hpp
- rclcpp/include/rclcpp/create_client.hpp
- rclcpp/include/rclcpp/event_handler.hpp
- rclcpp/include/rclcpp/loaned_message.hpp
- rclcpp/include/rclcpp/node.hpp
- rclcpp/include/rclcpp/node_impl.hpp
- rclcpp/include/rclcpp/node_interfaces/node_parameters_interface.hpp
- rclcpp/include/rclcpp/parameter_client.hpp
- rclcpp/include/rclcpp/parameter_service.hpp
- rclcpp/include/rclcpp/publisher.hpp
- rclcpp/include/rclcpp/rate.hpp
- rclcpp/include/rclcpp/subscription.hpp
- rclcpp/include/rclcpp/typesupport_helpers.hpp
- rclcpp/include/rclcpp/waitable.hpp
- rclcpp/src/rclcpp/rate.cpp
- rclcpp/src/rclcpp/waitable.cpp
- rclcpp/test/rclcpp/test_client.cpp
- rclcpp/test/rclcpp/test_loaned_message.cpp
- rclcpp/test/rclcpp/test_rate.cpp
- rclcpp_components/include/rclcpp_components/component_manager.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node.hpp
- rclcpp_lifecycle/include/rclcpp_lifecycle/lifecycle_node_impl.hpp
- rclcpp_lifecycle/test/test_client.cpp
- rclcpp_lifecycle/test/test_service.cpp
Most of the deprecated happened since `iron`.
Since Jazzy:
- rate
- typesupport_helpers
- waitable
> Removed deprecated methods and classes

- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
In the current code, inside of the timer we create the subscription and the publisher, publish immediately, and expect the subscription to get it immediately.  But it may be the case that discovery hasn't even happened between the publisher and the subscription by the time the publish call happens.
To make this more reliable, create the subscription and publish *before* we ever create and spin on the timer.  This at least gives 100 milliseconds for discovery to happen.  That may not be quite enough to make this reliable on all platforms, but in my local testing this helps a lot.  Prior to this change I can make this fail one out of 10 times, and after the change I've run 100 times with no failures.
FYI @iuhilnehc-ynos .
@wjwwood If you have time to look at this, I'd appreciate a review. …
> Make the subscriber_triggered_to_receive_message test more reliable.

- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/test_subscription_content_filter.cpp
Even when we want to run them on multiple RMWs, we can do that by compiling once, then setting the environment variable appropriately.
In my local testing, this improved compilation times by about 10%.
> Only compile the tests once.

- rclcpp/include/rclcpp/waitable.hpp
- rclcpp/src/rclcpp/waitable.cpp
- rclcpp/test/rclcpp/node_interfaces/test_node_waitables.cpp
- rclcpp/test/rclcpp/strategies/test_allocator_memory_strategy.cpp
- rclcpp/test/rclcpp/test_memory_strategy.cpp
- rclcpp/test/rclcpp/wait_set_policies/test_dynamic_storage.cpp
- rclcpp/test/rclcpp/wait_set_policies/test_static_storage.cpp
- rclcpp/test/rclcpp/wait_set_policies/test_storage_policy_common.cpp
- rclcpp/test/rclcpp/wait_set_policies/test_thread_safe_synchronization.cpp
I initially started looking at this because clang was complaining
that "all paths through this function will call itself" (see https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/1966/clang/new/fileName.-934007317/).  And it
is correct; if an implementation does not override these methods,
and they are ever called, they will go into an infinite loop
calling themselves.
However, while looking at it it seemed to me that these were really
part of the API that a concrete implementation of Waitable needed
to implement.  It is fine if an implementation doesn't want to do
anything (like the tests), but all of the "real" users in the codebase
override these.
Thus, remove the implementations here and make these pure virtual
functions that all subclasses must implement.
Note that I've …
> Make more of the Waitable API abstract

- rclcpp/src/rclcpp/context.cpp
- rclcpp/test/rclcpp/test_utilities.cpp
We already do this clean-up if some other tasks below fail.
Before:
```
[ RUN      ] TestUtilities.test_context_init_shutdown_fails
[ERROR] [1722555370.075637014] [rclcpp]: rcl context unexpectedly not shutdown during cleanup
[WARN] [1722555370.077175569] [rclcpp]: logging was initialized more than once
[       OK ] TestUtilities.test_context_init_shutdown_fails (3 ms)
```
After:
```
[ RUN      ] TestUtilities.test_context_init_shutdown_fails
[WARN] [1722555108.693207861] [rclcpp]: logging was initialized more than once
[       OK ] TestUtilities.test_context_init_shutdown_fails (3 ms)
```
> Shut down context during init if logging config fails

- rclcpp/test/rclcpp/CMakeLists.txt
The CMake file is checking if `ament_add_gtest` has effectively added any target (which is not guaranteed).
However, probably due to some copy-paste errors, all the executors tests were checking for the same target.
This had no practical difference right nkw, since if one target exist we should assume that they all exist, but it was not correct.
Indeed if the `test_executors` would be removed, all the other tests would fail to compile.
> fix rclcpp/test/rclcpp/CMakeLists.txt to check for the correct targets

- rclcpp/src/rclcpp/experimental/executors/events_executor/events_executor.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_reinitialized_timers.cpp
- rclcpp/test/rclcpp/test_reinitialized_timers.cpp
This PR addresses a bug in the EventsExecutor related to timers. The issue occurs when multiple timers are present in the entities collection, and at least one of them gets re-initialized. Prior to this fix, the collection failed to detect which timers were re-initialized, leading to the following problems:
- The old timer might continue running, triggering its callback.
- The new timer might never start, preventing its callback from being invoked.
The fix consists in invoking the `remove_expired_entities` right before the timers collection is updated.
A regression test was included among the changes, this test will fail with the current rolling HEAD.
> Fix bug in timers lifecycle for events executor

- rclcpp/include/rclcpp/parameter_event_handler.hpp
This was added in #1573, which is a fixed version of #829 (which was reverted in #1572).
The title of #1573/#829 mentions "ParameterEventsSubscriber" but there is no such class. `ParameterEventsSubscriber` was renamed to `ParameterEventHandler`: https://github.com/ros2/rclcpp/pull/829/commits/60533db8d353dd2b3780793f5a12fb7bb245bb92 + https://github.com/ros2/rclcpp/pull/829/commits/894da98dbaafddf427c7baa71f41c6d70ec8ad08. These docs (and PR title) were just not updated. `rclcpp::ParameterEventsSubscriber::get_parameter_from_event()` doesn't exist, but `rclcpp::ParameterEventHandler::get_parameter_from_event()` does.
> Fix name of ParameterEventHandler class in doc

- rclcpp/include/rclcpp/executors/static_single_threaded_executor.hpp
- rclcpp/test/benchmark/benchmark_executor.cpp
- rclcpp/test/rclcpp/executors/executor_types.hpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/executors/test_executors_busy_waiting.cpp
- rclcpp/test/rclcpp/executors/test_executors_timer_cancel_behavior.cpp
- rclcpp/test/rclcpp/executors/test_reinitialized_timers.cpp
- rclcpp/test/rclcpp/executors/test_static_single_threaded_executor.cpp
- rclcpp/test/rclcpp/test_add_callback_groups_to_executor.cpp
This PR marks the `StaticSingleThreadedExecutor` as deprecated.
With the current implementation, all other single threaded executors have better performance than this one and they are more stable.
See https://discourse.ros.org/t/the-ros-2-c-executors/38296 for a recent performance comparison that I run.
> deprecate the static single threaded executor

- rclcpp/include/rclcpp/parameter_value.hpp
More appropriate function argument naming that improves readability and coherence.
Refer to: 
https://github.com/ros2/rclcpp/blob/rolling/rclcpp/src/rclcpp/parameter_value.cpp#L83
> Minor naming fixes for ParameterValue to_string() function

- rclcpp/test/rclcpp/executors/test_executors.cpp
This PR removes a couple of GTEST_SKIP instances from `test_executors.cpp`.
- Unfortunately, the `spin_some_max_duration` test is still broken for the static single threaded executor (despite https://github.com/ros2/rclcpp/issues/2462#issuecomment-2020753899). Here I replaced the `GTEST_SKIP` with the `TestExecutorsStable` fixture.
- Verified that the `test_race_condition_add_node` succeeds with connext dds and events-executor (now that the events executor is supported by that RMW). Here I removed the `GTEST_SKIP`.
> remove unnecessary gtest-skip in test_executors

- rclcpp/src/rclcpp/generic_client.cpp
- rclcpp/test/rclcpp/test_generic_client.cpp
Use newly defined exceptions `rclcpp::exceptions::InvalidServiceTypeError` to make errors clearer.
rclcpp::exceptions::InvalidServiceTypeError was introduced in #2617.
> Use InvalidServiceTypeError for unavailable service type in GenericClient

- rclcpp/src/rclcpp/experimental/executors/events_executor/events_executor.cpp
- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_executors_warmup.cpp
backport fix events-executor warm-up bug and add unit-tests (#2591)
Replaces mergify PR with conflicts: https://github.com/ros2/rclcpp/pull/2625
> backport fix events-executor warm-up bug and add unit-tests (#2591)

- rclcpp/test/rclcpp/test_subscription_content_filter.cpp
Content filtering is still not implemented in `rmw_zenoh`
https://github.com/ros2/rmw_zenoh/blob/60b72f07a7d7254aeed8c39c11174bb52806ee62/rmw_zenoh_cpp/src/rmw_zenoh.cpp#L1690-L1713
These tests generates a segfault, I think we can skip them for now.
> Skip rmw zenoh content filtering tests

- rclcpp/test/rclcpp/test_service_introspection.cpp
part of https://github.com/ros2/rmw/issues/357
- this PR makes sure uniqueness of client GID via single service event.
- at this moment, `rmw_connextdds` is the only rmw implementation that can pass this test.
> verify client gid uniqueness for a single service event.

- rclcpp_action/CMakeLists.txt
The default is 300 seconds, but on Windows this is taking between 250 and 300 seconds (I'm seeing it timeout sometimes). Up the timeout to 600 seconds, which should be more than enough.
> Increase the timeout for the cppcheck on rclcpp_action.

- rclcpp/include/rclcpp/generic_client.hpp
- rclcpp/src/rclcpp/generic_client.cpp
- rclcpp/test/rclcpp/test_generic_client.cpp
Currently, the implementation of `async_send_request` for the GenericClient lacks support for callbacks.   
When a response is received, the user-defined callback can be automatically invoked.
> Implement callback support of async_send_request for service generic client

- rclcpp/include/rclcpp/any_subscription_callback.hpp
- rclcpp/test/rclcpp/test_any_subscription_callback.cpp
* Fix subscription.is_serialized() for callbacks with message info argument
* Add tests + please linters
> [Backport]Fix subscription.is_serialized() for callbacks with message info (#1950)

- rclcpp_lifecycle/src/state.cpp
The function that may not complete successfully is `rcl_lifecycle_state_fini()`, not `rcl_lifecycle_transition_fini()`.
I believe this is a copy-paste error with `rclcpp_lifecycle::Transition::reset()`, which does call `rcl_lifecycle_transition_fini()`.
> Fix error message in rclcpp_lifecycle::State::reset()

- rclcpp/test/rclcpp/CMakeLists.txt
- rclcpp/test/rclcpp/executors/test_events_executor.cpp
Fixed test_events_executors in zenoh
> Fixed test_events_executors in zenoh

- rclcpp/test/rclcpp/test_intra_process_manager.cpp
There are 2 patches here:
1.  Make every pub and sub in test_intra_process_manager.cpp have to pass in both a topic name and a QoS when they are constructing mock pubs and subs for the intra-process manager test.  This just makes it easier to tell whether the pubs and subs should be matched or not.
2.  The intra_process_manager will attempt to match QoS between publishers and subscriptions as they are added to the IPM. This is exactly correct, but the tests were not following the same pattern. Thus, when running these tests under Zenoh, the tests would fail because more things would match than the tests were expecting. Update the test to take the differences in QoS into account, which fixes the test under rmw_zenoh_cpp (and keeps it working for the existing DDS RMWs).
> Fix test_intra_process_manager.cpp with rmw_zenoh_cpp

- rclcpp/include/rclcpp/subscription_options.hpp
- rclcpp/test/rclcpp/test_subscription_options.cpp
closes https://github.com/ros2/rclcpp/issues/2588
> set QoS History KEEP_ALL explicitly for statistics publisher.

- rclcpp/src/rclcpp/node_options.cpp
- rclcpp/test/rclcpp/test_node_options.cpp
While working with NodeOptions, I realized "enable_logger_service" was copied with the assignment operator.
Here is a little PR to fix the issue. I also added some additional checks for primitives members in `TEST(TestNodeOptions, copy)`. 
Let me know what you think
> Fix NodeOptions assignment operator

- rclcpp/include/rclcpp/subscription_options.hpp
- rclcpp/test/rclcpp/test_subscription_options.cpp
Backport of https://github.com/ros2/rclcpp/pull/2650
closes https://github.com/ros2/rclcpp/issues/2588
* set QoS History KEEP_ALL explicitly for statistics publisher.
* test_subscription_options adjustment.
> [Backport] set QoS History KEEP_ALL explicitly for statistics publisher. (#2650)

- rclcpp_action/src/client.cpp
- rclcpp_action/src/server.cpp
Related bug: #2242. I managed to create a situation in which I can easily replicate it as many times as I wanted.
This bug was already fixed in rolling (#2495) and iron (#2531).
I just backported the fix based on the iron fix. Now I test it and works perfectly all the times I run my node.
I tried to do it as clean as possible (fortunately the iron fix didn't touch header files and all the function prototypes where the same between iron and humble).
> fix: Fixed race condition in action server between is_ready and take (humble)

- rclcpp/include/rclcpp/generic_client.hpp
This is a minor fix.  
Since the current rmw does not provide an interface to obtain serialized request and response data, both generic_client and generic_service are currently handling deserialized untyped data.   
In the code comments, it was mistakenly written as serialized data.
> Correct the incorrect comments in generic_client.hpp

- rclcpp/test/rclcpp/test_client.cpp
This test is being disabling this test because we don't have allocated time to fix it, also, Iron is getting EOL soon.
Fixes: https://github.com/ros2/rclcpp/issues/2611
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22046)](http://ci.ros2.org/job/ci_linux/22046/)
* Linux-aarch64 [![Build Status](https://ci.ros2.org/job/ci_linux-aarch64/16326/badge/icon)](https://ci.ros2.org/job/ci_linux-aarch64/16326/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1564)](http://ci.ros2.org/job/ci_linux-rhel/1564/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22776)](http://ci.ros2.org/job/ci_windows/22776/)
> Skip client_qos test

- rclcpp_action/include/rclcpp_action/server_goal_handle.hpp
Changes from pull request #2668 to re-target the branch.
Both typos from the previous PR need to be fixed in the downstream ([`humble`](https://github.com/ros2/rclcpp/tree/humble)).
> Fix documentation typo in server_goal_handle.hpp

- rclcpp/include/rclcpp/any_service_callback.hpp
The `callback_end` tracepoint was triggered at the end of the `dispatch()` method, but there is more than 1 `return`.
Relates to https://github.com/ros2/ros2_tracing/pull/144
> Make sure callback_end tracepoint is triggered in AnyServiceCallback

- rclcpp/src/rclcpp/executor.cpp
- rclcpp/src/rclcpp/executors/static_single_threaded_executor.cpp
- rclcpp/test/rclcpp/executors/test_executors.cpp
Fix for https://github.com/ros2/rclcpp/issues/2664 in rolling
Note, this is not my preferred fix for this. But I would like to merge this now,
to get a fix into jazzy ASAP.
@alsora @mjcarroll fyi
> fix(Executor): Fix segfault if callback group is deleted during rmw_wait

- rclcpp/test/rclcpp/executors/test_executors.cpp
- rclcpp/test/rclcpp/test_client_common.cpp
- rclcpp/test/rclcpp/test_generic_service.cpp
- rclcpp/test/rclcpp/test_service.cpp
- rclcpp/test/rclcpp/test_service_introspection.cpp
When running the tests with RTI Connext as the default RMW, some of the tests are failing.  There are three different failures fixed here:
1.  Setting the liveliness duration to a value smaller than a microsecond causes Connext to throw an error.  Set it to a millisecond.
2.  Using the SystemDefaultsQoS sets the QoS to KEEP_LAST 1. Connext is somewhat slow in this regard, so it can be the case that we are overwriting a previous service introspection event with the next one.  Switch to the ServicesDefaultQoS in the test, which ensures we will not lose events.
3.  Connext is slow to match publishers and subscriptions.  Thus, when creating a subscription "on-the-fly", we should wait for the publisher to match it before expecting the subscription to actually receive data from it.
With these …
> Omnibus fixes for running tests with Connext.

- rclcpp_components/src/component_manager.cpp
- rclcpp_components/test/test_component_manager_api.cpp
Improves situation for #978.
Instead of arbitrarily only allowing forward_global_arguments and use_intra_process_comms as extra arguments for loading a component, this PR enables support for all obvious boolean node options.
#978 discusses more problematic options like `allow_undeclared_parameters`, which are still unsupported.
At least, this PR adds an error message if such or other unsupported extra arguments are passed.
> Add parsing for rest of obvious boolean extra arguments and throw for unsupported ones

- rclcpp/include/rclcpp/clock.hpp
- rclcpp/src/rclcpp/clock.cpp
- rclcpp_action/src/server.cpp
This commit is only relevant if the events executor is used.
This commit adds a background thread, to create events for the expire timer of the action. 
Without this the action server will not expire old goal results leading to memory and performance issues.
For now, this commit is a draft. There is still a (minor) issue, that the clock used in the background
thread does not work correct in the use_sim_time case (it still runs on system time).
This is an alternative to https://github.com/ros2/rclcpp/pull/2661
In contrast to #2661, it reuses the rcl internal timer and therefore existing code to recompute the
expire times.
@alsora  @mauropasse @mjcarroll thoughts ?
> fix: Fixed expiring of goals if events executor is used
